### ISSUE TITLE
unknown pbf field type exception error while using tiles in iOS app

### ISSUE THREAD

**Issue by AEiosApp** [systemed/tilemaker#101]
Hi, I'm trying to use tilemaker for preparing tiles for my iOS app.
I'm using MapBox sdk v.3.7.0

Everything works fine with tiles that I've got from openmaptiles.org (tiles are packed in app bundle resources).

But when I try to use tiles that I've got from other source and converted with tilemaker, I'm getting error: 
`OfflineMapSwiftV1[4000:5484379] [ERROR] {}[Style]: Failed to load tile 12/2189/1522=>12 for source openmaptiles: unknown pbf field type exception`

Any ideas?

**Comment by systemed** [comment]
Can you give a workable example of how you've produced the tiles? (i.e. the .pbf you downloaded, your tilemaker command line)

**Comment by AEiosApp** [comment]
The source data I've got from [here](https://mapzen.com/data/metro-extracts/metro/rome_italy/)

Mac terminal command:
`tilemaker rome_italy.osm.pbf --output=Romemap/`

Tilemaker process completed without errors.

I've tried to add also "mvt_version" parameter ton config.json file, but it haven't helped.
What is the format for this parameter?
`"mvt_version": 2,`
or
`"mvt_version": "2",`

**Comment by systemed** [comment]
It's a number not a string, but tilemaker defaults to 2 (assuming you're using the latest source) so you shouldn't need to add it. I'm using tilemaker with the current Mapbox SDK with no issues so not sure what's going on here.
