### ISSUE TITLE
Name of streets, places &...

### ISSUE THREAD

**Issue by emdadgar2** [systemed/tilemaker#107]
Hi,
How I can configure tilemaker to show names (street name, waterway name &...)

Thanks

**Comment by systemed** [comment]
Make sure your Lua script outputs the name tag. Help on writing a Lua script is in the configuration guide - https://github.com/systemed/tilemaker/blob/master/CONFIGURATION.md . This will put the names in the vector tiles.

Then the rest is up to whatever display client you're using, and the style you design for it!
