### ISSUE TITLE
Config file for mapbox

### ISSUE THREAD

**Issue by ajaybhargav** [systemed/tilemaker#108]
While browsing in issues I found link to repo where mapbox compatible config file is available but its too old. I wanted to know, is the config still valid? or any other resource available for the same.
https://github.com/flamed0011/tilemaker/blob/master/resources/mbx_compatible_config.json

Maybe a newbie question, is there any example on how to use the generated mbtiles (served by the ruby server in resource folder) with mapbox-gl? I am searching here and there but not getting enough information. Please help.

**Comment by pnorman** [comment]
> While browsing in issues I found link to repo where mapbox compatible config file is available but its too old. I wanted to know, is the config still valid? or any other resource available for the same.
> https://github.com/flamed0011/tilemaker/blob/master/resources/mbx_compatible_config.json

Mapbox has made legal threats to those implementing their Mapbox Streets schema, so @systemed decided not to make a config file that generated their schema.

You are of course free to make one yourself if you want to disregard their threats, but I recommend talking to your lawyer about if the risks are worth it before doing that.

**Comment by ajaybhargav** [comment]
I have dropped using mapbox or generating own tiles as of now. Thanks anyways for informing about the risks involved.

**Comment by TimSC** [comment]
I makde a start in resources/config-openmaptiles.json and resources/process-openmaptiles.lua which produce a fairly decent map using the openmaptiles schema. You probably would need to render using one of their mapbox themes. See also #110
