### ISSUE TITLE
[FIXED] Couldn't open .pbf file

### ISSUE THREAD

**Issue by vaysy** [systemed/tilemaker#109]
Hi,

I tried on ubuntu, docker on many devices/servers.. and I have always the following error : 
`docker run -v /Users/Local/Downloads/:/srv -i -t --rm tilemaker test.osm.pbf --output=c:\temp\`
**Couldn't open .pbf file c:\temp\test.osm.pbf**

Thanx by advance for any help

**Comment by systemed** [comment]
Have you tried without docker (i.e. building from source)? Can you provide a link to the pbf?

**Comment by vaysy** [comment]
I used a wrong folder... it's working now ;)

**Comment by paulsUsername** [comment]
I have the same issue. Could you let me know how you resolved it?
