### ISSUE TITLE
How to render mbtiles like openmaptiles.org or maputnik ?

### ISSUE THREAD

**Issue by vaysy** [systemed/tilemaker#110]
Hi,

I generate a mbtiles with tilemaker and default config.json but it's not enough.
Where can I found a complete config.json to render all water, land, roads, text fields and buildings to render a full view ?

Thanx a lot by advance

**Comment by systemed** [comment]
Sorry, there isn't one publicly available that I know of.

**Comment by mathisloge** [comment]
#108

**Comment by TimSC** [comment]
I makde a start in resources/config-openmaptiles.json and resources/process-openmaptiles.lua which produce a fairly decent map using the openmaptiles schema. You probably would need to render using one of their mapbox themes.

**Comment by qlerebours** [comment]
I think it can be closed @systemed

**Comment by systemed** [comment]
Closing in favour of #139.
