### ISSUE TITLE
I can not display my tiles (by tilemaker).

### ISSUE THREAD

**Issue by 1254859753** [systemed/tilemaker#114]
I want to render these tiles via Mapbox. Who can provide a example for me? Thanks very much!

**Comment by systemed** [comment]
Please stop posting comments on every issue asking the same question - thank you.

This is not an issue with tilemaker, it's a generic question about serving and viewing vector tiles. You would be better off asking at https://help.openstreetmap.org/ .

**Comment by 1254859753** [comment]
Ok, I know. Sorry about this and thank you very much!
