### ISSUE TITLE
Big slowdown from merging geometries

### ISSUE THREAD

**Issue by systemed** [systemed/tilemaker#115]
When outputting features to the vector tile, currently we merge successive geometries of the same type and attributes: https://github.com/systemed/tilemaker/blob/master/src/tilemaker.cpp#L145

This causes a 100%+ slowdown. Without merging:

    real	0m24.999s
    user	0m28.820s
    sys	0m1.082s

With:

    real	0m53.344s
    user	1m23.208s
    sys	0m4.432s

Filesize is 7.9Mb unmerged, 7.2Mb merged. (Oxfordshire extract, waterways style.)

Ideally we should eliminate the slowdown, but if we can't, this should be a configurable option.

**Comment by TimSC** [comment]
I've added a config and command line option to disable merging geometries in b265e84
