### ISSUE TITLE
About shpfiles

### ISSUE THREAD

**Issue by 1254859753** [systemed/tilemaker#116]
Dear TileMaker Developer,
       I want to get some vectors tiles from a shpfile. Can I use TileMaker to clip a shpfile?

**Comment by systemed** [comment]
Tilemaker currently needs an .osm.pbf file. You can supply shapefiles as additional data but it requires at least one .osm.pbf (though see #80).

**Comment by systemed** [comment]
.osm.pbf files are no longer compulsory.
