### ISSUE TITLE
Is it the correct behaivior that the `CheckNextObjectAndMerge` method always works even if the include_ids option is true?

### ISSUE THREAD

**Issue by shun-tak** [systemed/tilemaker#120]
## Goal

I am drawing 3D maps. I would like to distinguish buildings and render textures depending on `ID mod # of textures`.

e.g. I have 2 textures and I want to render 2 types of buildings.
If `feature.id % 2 == 0` then I render the building with a texture type 1.
Else I render the building with a texture type 2.

## Issue

We can get IDs with config option `include_ids: true`, but features are merged by the `CheckNextObjectAndMerge` method when geometry type and attribute match, even though each ID is different.
To avoid merging we have to add ID to the feature's attribute like `way:Attribute("id", way:Id())`. By doing this, it becomes possible to distinguish the ID and achieve my goal. However, the size of the generated PBF vector tile will increase because duplicated data (ID as an attribute) is added.

There is another solution that does not execute `CheckNextObjectAndMerge` method even if the include_ids option is true. Is there some reason why such condition is not implemented or is it just kind of a bug?

Thanks in advance. I appliciate your kindness and for creating this good tool.

**Comment by TimSC** [comment]
A work around would be to use https://github.com/TimSC/tilemaker/tree/inputs This has a "--combine 0" option that disables merging of geometries.

**Comment by shun-tak** [comment]
Thank you for updating!
https://github.com/systemed/tilemaker/pull/119
