### ISSUE TITLE
How to configure fields?

### ISSUE THREAD

**Issue by wboykinm** [systemed/tilemaker#121]
I'm interested in pulling building height data into MVTs generated with tilemaker. Using the "default" config file, I edited [this line](https://github.com/systemed/tilemaker/blob/master/config.json#L21) to read

`{ "id": "building", "description": "building", "fields": { "height": "Integer" }}`

Tilemaker then runs smoothly and produces outputs [that render in Mapbox GL when given static properties](https://github.com/wboykinm/bird/blob/master/lib/styles.js#L76):

<img width="620" alt="screenshot 2018-10-15 10 29 13" src="https://user-images.githubusercontent.com/735463/46957284-40aaa680-d065-11e8-974a-a010cb60222b.png">

Unfortunately, when I try to [use the height info for dynamic styling](https://github.com/wboykinm/bird/blob/master/lib/styles.js#L77-L85), I get this error:

`Expected value to be of type number, but found null instead.`

It appears that my adjustment to the config file above is producing `NULL`s. What is the proper way to pass usable building height data (or indeed any data from osm properties) through to generated MVTs?

**Comment by systemed** [comment]
Oh wow, that looks nice!

The bit of tilemaker that maps OSM keys into MVT fields is the `config.lua` file. (The `vector_layers` part of the JSON config is a slightly confusing Mapbox addition which documents what the client will find in the tiles, but it doesn't actually change anything. tilemaker can now generate that automatically.)

So you'd need to make `config.lua` take the OSM data and write it into the vector tiles. You should be able to do this by editing https://github.com/systemed/tilemaker/blob/master/process.lua#L43, and adding a couple of new lines:

    local metres = to_number(way:Find("height")) or 5
    way:AttributeNumeric("height", metres)

That takes the height tag from OSM; converts it to a number; falls back to a default height of 5 if there's no height tag; and writes it to the vector tile as the "height" attribute.

There's doubtless lots more you could do in terms of parsing the weird and wonderful values that are no doubt in the height tag, but that should do for a start. Lua's really well-suited to doing this sort of OSM tag-mangling (it's used for the same purpose in OSRM and osm2pgsql).

**Comment by wboykinm** [comment]
@systemed That's a marvelous explanation, and makes this super-extensible. Thanks so much! 

I am however running into what appears to be a coalesce failure, and my troglodytic searching around the lua docs is not turning up an answer. 

Given:

```
if building~="" then
  local metres = (to_number(way:Find("height"))) or 5
  way:AttributeNumeric("height",metres)
  way:Layer("building", true)
end
```

Any idea what's causing this? 

`libc++abi.dylib: terminating with uncaught exception of type kaguya::LuaRuntimeError: process.lua:44: attempt to call global 'to_number' (a nil value)`

It seems to happen no matter where I put the `metres` declaration. For reference I'm using a [geofabrik extract](http://download.geofabrik.de/north-america/us/vermont.html).

**Comment by systemed** [comment]
Gah! Mea culpa. Should be `tonumber` (no underscore).

**Comment by wboykinm** [comment]
@systemed That did the trick! 

<img width="1074" alt="screenshot 2018-10-15 16 00 04" src="https://user-images.githubusercontent.com/735463/46974975-7070a300-d093-11e8-8e4b-1067b0cc06a2.png">

Thanks again!

**Comment by tgdbepe4** [comment]
Where you place exacty this:
