### ISSUE TITLE
tangram not rendering tiles

### ISSUE THREAD

**Issue by mkandulavm** [systemed/tilemaker#123]
Hi

I have downloaded mvt format tiles as mbtiles for a region using 
https://github.com/tilezen/tilepacks

I have this offline mbtiles rendering in tangram.

However the generated mbtiles using tilemaker are not rendering and there are no errors.

I think I need to modify scene.yaml in tangram, but I am not getting any clear instructions on how to do this.  Can you please help ?

**Comment by clement-igonet** [comment]
Two parts are to consider:
- the way to produces vector tiles with tilemaker (config.json and process.lua)
- the way to interpret vector tiles with tangram (scene.yaml).
We miss a full success story from making tiles with tilemaker to render them with any solution (openlayer, leaflet, mapbox, tangram and so on...)

**Comment by systemed** [comment]
Yes, a ready-to-go config (aka "success story") is the subject of #139, but that will almost certainly use Mapbox GL. Tangram is a bit of a minority taste these days I'm afraid, and I think it would need a specialist developer to come up with a solution for that.

**Comment by clement-igonet** [comment]
Note that tangram is a Linux Foundation project. So, we can hope we won't be accused of copying the data structure they use from nextzen. Whereas mapbox does not accept we reproduce their tile vector structure. We should take that seriously into account, even if mapbox is "popular".

**Comment by clement-igonet** [comment]
> Yes, a ready-to-go config (aka "success story") is the subject of #139, but that will almost certainly use Mapbox GL. Tangram is a bit of a minority taste these days I'm afraid, and I think it would need a specialist developer to come up with a solution for that.

OK thks.Good to know.
I'll have a try with OpenMapTiles and convenient renderers.
