### ISSUE TITLE
kaguya::LuaRuntimeError

### ISSUE THREAD

**Issue by nuharaf** [systemed/tilemaker#125]
Hi , I tried using tilemaker using pbf data from my local Openstreetmap organization (indonesia), however this error always generated

> terminate called after throwing an instance of 'kaguya::LuaRuntimeError'
>   what():  Could not find node 1367963610
> Aborted (core dumped)

If I use pbf file from geofabrik, it succesfully generate tile.
This is probably problem with the pbf file itself instead of tilemaker, but I don't know how to fix it.

output from osmium fileinfo
```
File:
  Name: Yogyakarta.pbf
  Format: PBF
  Compression: none
  Size: 23472955
Header:
  Bounding boxes:
    (109.902,-8.41387,110.834,-7.54129)
  With history: no
  Options:
    generator=osmconvert 0.8.2
    osmosis_replication_timestamp=2018-10-30T21:15:02Z
    pbf_dense_nodes=true
    pbf_optional_feature_0=Sort.Type_then_ID
    pbf_optional_feature_1=timestamp=2018-10-30T21:15:02Z
    timestamp=2018-10-30T21:15:02Z
```

and

```
File:
  Name: indonesia.osm.pbf
  Format: PBF
  Compression: none
  Size: 657209302
Header:
  Bounding boxes:
    (92.7648,-11.6066,141.022,6.99933)
  With history: no
  Options:
    generator=osmium/1.8.0
    osmosis_replication_base_url=http://download.geofabrik.de/asia/indonesia-updates
    osmosis_replication_sequence_number=1981
    osmosis_replication_timestamp=2018-08-21T20:15:02Z
    pbf_dense_nodes=true
    timestamp=2018-08-21T20:15:02Z
```

Thanks you for this piece of software

**Comment by pnorman** [comment]
It sounds like the PBF was clipped in a way that removed nodes that were referenced by ways still in the PBF.

**Comment by nuhamind2** [comment]
I thought so too, I tried _naively_ clip data from geofabrik with osmium, but the generated file seem lack some metadata (bounding box as i recall) and tilemaker complain about it.
Anyway, I am still digging about osmium itself, since I am quite new about this whole map stack.

**Comment by ogre** [comment]
I am getting exact same error with unmodified file http://download.geofabrik.de/europe/poland-latest.osm.pbf
How can I help to fix this ?

**Comment by ogre** [comment]
Looking at different posts, it seems that missing nodes are usually due to clipping at extract boundaries that geofabrik prepares. But I checked, my node is not near Poland border:
[https://www.openstreetmap.org/node/2513305472](url)
so chances it was clipped are small - it must have been other issue then ?
Can tilemaker handle missing nodes situations? If not, what can I do to fix input data ?

**Comment by iyan31** [comment]
Hello @nuharaf, I also stumble the same problem. What I did is I re-clip the data (from Indonesia.pbf) using Osmosis and .poly files, and it works. I just found out from #31 that Osmosis also have clipincompleteEntities option which may come in handy to avoid future problem.

**Comment by addam** [comment]
To be specific, this command worked for me:
`osmosis --read-pbf myfile.osm.pbf --bounding-box clipIncompleteEntities=true --write-pbf myfile-fixed.osm.pbf`

**Comment by kathir-bit** [comment]
thanks addam...its working
