### ISSUE TITLE
'make' ERROR on Ubuntu 18.04 Bionic

### ISSUE THREAD

**Issue by toton6868** [systemed/tilemaker#126]
Here is the error code 

```
In file included from ./include/helpers.h:7:0,
                 from src/pbf_blocks.cpp:2:
./include/geomtypes.h:22:69: error: template argument 3 is invalid
 typedef boost::variant<Point,Linestring,MultiLinestring,MultiPolygon> Geometry;
                                                                     ^
./include/geomtypes.h:22:69: error: template argument 4 is invalid
In file included from src/pbf_blocks.cpp:2:0:
./include/helpers.h:32:29: error: ‘MultiPolygon’ does not name a type; did you mean ‘Polygon’?
 void ConvertToClipper(const MultiPolygon &mp, ClipperLib::Paths &out);
                             ^~~~~~~~~~~~
                             Polygon
./include/helpers.h:33:29: error: ‘MultiPolygon’ does not name a type; did you mean ‘Polygon’?
 void ConvertToClipper(const MultiPolygon &mp, ClipperLib::PolyTree &out);
                             ^~~~~~~~~~~~
                             Polygon
./include/helpers.h:35:57: error: ‘MultiPolygon’ has not been declared
 void ConvertFromClipper(const ClipperLib::PolyTree &pt, MultiPolygon &mp);
                                                         ^~~~~~~~~~~~
Makefile:13: recipe for target 'src/pbf_blocks.o' failed
make: *** [src/pbf_blocks.o] Error 1
rm include/vector_tile.pb.cc include/osmformat.pb.cc

```

**Comment by TimSC** [comment]
That is strange, I compiled tilemaker using the Ubuntu 18.04 Live CD no problem. Do you have any further ideas as to the cause? (I am developing using Linux Mint 19.1 which is based on Ubuntu 18.04)

**Comment by systemed** [comment]
(In particular, the Boost version might be relevant here.)

**Comment by qlerebours** [comment]
I installed everything yesterday and I didn't get the error on Ubuntu 18.04
I installed boost using standard `sudo apt-get install libboost-all-dev `

**Comment by carlos-mg89** [comment]
For me, the error is no exactly the same, but it's related with the libboost packages.

I've been able to follow up the guide without issues, until I ran the docker run command to process an osm.pbf I downloaded from Geofabrik. I have Ubuntu 18.04 by the way.

After running the docker run command, I've received this error:

> tilemaker: error while loading shared libraries: libboost_program_options.so.1.65.1: cannot open shared object file: No such file or directory

However, I was able to install the libboost packages without issues. I ran `sudo apt-get install libboost-all-dev`. Any ideas¿?

If I try to install again the libboost-program-options (sudo apt install libboost-program-options-dev) it says I have 1.65.1.0ubuntu1 already installed.

**Comment by carlos-mg89** [comment]
At least, running tilemaker directly seems to work :) So it looks like the issue is with the docker image.

**Comment by systemed** [comment]
I don't know the first thing about Docker, I'm afraid. Leaving this open in case anyone does.

**Comment by carlos-mg89** [comment]
@systemed It worked on Docker, on another computer that also has Ubuntu 18.04. So it's clearly something (most likely software related) on my another PC. Thanks!
