### ISSUE TITLE
Control feature write order

### ISSUE THREAD

**Issue by systemed** [systemed/tilemaker#132]
Mapbox GL renders features in the order they appear in the source tiles (see https://github.com/mapbox/mapbox-gl-js/issues/4361). This is particularly relevant when trying to achieve correct z-index for bridges/tunnels.

We should be able to sort features within a tile. This is probably best achieved by setting an optional (single-byte?) z-index value when writing to a layer, and then sorting features by this value before writing.

**Comment by Nakaner** [comment]
Resolved by #393
