### ISSUE TITLE
docker quit with no error

### ISSUE THREAD

**Issue by kathur2rain** [systemed/tilemaker#136]
I downloaded 2 osm.pbf file, the first one is Antarctica.osm.pbf from Geofabrik.de about 29M, the second one is CH from https://download.gisgraphy.com/openstreetmap/pbf/  about 324M, after run docker run command, Antarctica.osm.pbf generate pbf tiles successfully while the CH one quit when block count reach  "Block 6495 group 0 ways 0 relations 0"

I guess it's a problem in ram limit? or some disk storage limit?

**Comment by Diniden** [comment]
I'm getting some success with running the process with adding the -m flag to the docker command with 8G

so `-m 8G`
