### ISSUE TITLE
[Help] Generate planet tiles process 

### ISSUE THREAD

**Issue by qlerebours** [systemed/tilemaker#138]
I'd like to generate my own tiles, covering the whole planet, to use with mapbox gl js library.

I checked a lot of documentation, i'm currently at this point:

 - I downloaded OSM data (.osm.pbf)
 - I read documentation of TileMaker, that can generate tile for openlayer from .osm.pbf. I know I will need much RAM thanks to [this issue][1]. That's why I planned to use EC2 instance, probably thanks to Amazon Spot
 - I know that after this point, I can upload the files to AWS S3 and serve them through CloudFront.

This is the only proccess I found to do that, but there some points that needs to be clarified.
My main question is: *Is this proccess valid* ? I have concerns about the following points:

 - What will approximately be the final size of the planet tiles directory?
 - Assuming that I plan to use the tiles only for showing basic map data (contours, countries and cities names, I don't need cities details like buildings etc), is it possible to omit the rest of the data ? How ? Using [tilemaker configuration][2] ?
 - Do I need graphic memory on my EC2 instance or is the r4.16xlarge suitable? (You can find ec2 instances [here][3])
 - How many times will it take (approximatively) to generate the tiles file?

As I asked before, do you think this proccess should work?

  [1]: https://github.com/systemed/tilemaker/issues/57
  [2]: https://github.com/systemed/tilemaker/blob/master/CONFIGURATION.md
  [3]: https://www.ec2instances.info/?selected=r4.16xlarge,x1.16xlarge,x1.32xlarge

**Comment by asinha08** [comment]
No reply to this question. Any help on this question would be help full.

**Comment by asinha08** [comment]
@qlerebours , were you able to generate mbtiles?

**Comment by qlerebours** [comment]
I already commented on the following issues, where you can find data about problems I had, etc:
 - https://github.com/openmaptiles/openmaptiles/issues/654
 - https://github.com/openmaptiles/openmaptiles/issues/669

**Comment by TimSC** [comment]
I think the master branch keeps the input data in memory. I've been working slowly long term to scale up the system https://github.com/systemed/tilemaker/issues/57 I have a branch that almost can read planet scale inputs by only loading selectively. https://github.com/TimSC/tilemaker/tree/scaleup5 

The input is assumed to be tile extracts at a particular zoom level. Generating that is non-trivial but possible (I have a custom stack working on a smaller fork anyway).

Note that this does address any low zoom problems when a single tile gets really big!
