### ISSUE TITLE
Assertion failed: (fp_ != 0), function FileReadStream

### ISSUE THREAD

**Issue by crofty** [systemed/tilemaker#14]
Thanks for sharing this tool, I'm keen to try it out but I'm running into an issue.

```
$ tilemaker liechtenstein-latest.osm.pbf --output=tiles/
Assertion failed: (fp_ != 0), function FileReadStream, file ./include/rapidjson/filereadstream.h, line 44.
zsh: abort      tilemaker liechtenstein-latest.osm.pbf --output=tiles/
```
I'm on OSX, and I installed the dependencies with homebrew:

```
$ brew install protobuf                    
Warning: protobuf-2.6.1 already installed
$ brew install boost                              
Warning: boost-1.58.0 already installed
$ brew install lua51   
Warning: lua51-5.1.5_2 already installed
$ brew install luabind
Warning: luabind-0.9.1_1 already installed
$ brew install sqlite3
Warning: sqlite-3.8.11 already installed
```

It seemed to install correctly:

```
$ make                             
protoc --proto_path=include --cpp_out=include include/osmformat.proto include/vector_tile.proto
g++ -O3 -Wall -Wno-unknown-pragmas -Wno-sign-compare -std=c++11 -o tilemaker include/osmformat.pb.cc include/vector_tile.pb.cc src/tilemaker.cpp -I/usr/local/include -I./include -I./src -I/usr/local/include/lua5.1 -I/usr/include/lua5.1 -L/usr/local/lib -lz -llua5.1 -lboost_program_options -lluabind -lsqlite3 -lboost_filesystem -lboost_system -lprotobuf
$ make install
```

I've tried with both [liechtenstein-latest.osm.pbf](http://download.geofabrik.de/europe/liechtenstein-latest.osm.pbf) and [london_england.osm.pbf](https://s3.amazonaws.com/metro-extracts.mapzen.com/london_england.osm.pbf).

Any ideas what the issue could be?

**Comment by systemed** [comment]
I'm on holiday on a poor mobile connection so can't trivially check right now, but it looks like it can't find the input JSON configuration file: make sure that's in your current directory or specify its location with a command line switch. (Same applies for the Lua file.)

**Comment by crofty** [comment]
Thanks Richard, that was my issue.

Copying config.json and process.lua from this repo into my working directory fixed the problem.

Enjoy your hols!
