### ISSUE TITLE
PostGIS?

### ISSUE THREAD

**Issue by andrestone** [systemed/tilemaker#145]
Hi!

First of all, thanks for building a unbinding, free open-source project. I could learn a lot from here.

My question: Is there any use case where a static vector tile generation like this project can be more appropriate than PostGIS?

Cheers.

**Comment by systemed** [comment]
Any use case where you don't want to maintain a PostGIS database. For example, creating vector tiles for offline use on a phone.

**Comment by andrestone** [comment]
Gotcha! I've got so focused on finding the solution for my own problem that I forgot that "offline" even existed 🤣 

Thanks again.
