### ISSUE TITLE
Question about including features based on zoom level

### ISSUE THREAD

**Issue by crofty** [systemed/tilemaker#15]
Thanks for this tool, it's been really good to use.

I have a question about whether it is possible to include features depending on zoom level.  Say I have a roads layer, I'd like this layer to only include ways of type "motorway" and "primary" at zoom 8, but then at zoom 9 I'd also like the same layer to include ways of type "secondary".

Is it possible to do this with a single "roads" layer, or do I have to split the road types into individual layers and use the config.json to specify the zoom levels for each layer?

**Comment by systemed** [comment]
You can't do currently that with a single layer, I'm afraid. Typically you'd have (say) a "major_roads" layer and a "secondary_roads" layer, and have the former at both z8 and z9, the latter at z9 only. But I'll keep this open because it might be worth considering for the future!

**Comment by crofty** [comment]
Thanks.  I'll split into individual layers for now.  
I was originally trying to structure my tiles in a similar way to the Mapbox Streets ones - they have a single roads layers with more categories of road becoming available as the zoom level increases.

Splitting the road categories into individual layers is a valid workaround.

**Comment by systemed** [comment]
Cool. I think what I'll do in due course is enhance the config so you can do things like this:

	"roads": { "minzoom": 12, "maxzoom": 14 },
	"minor_roads": { "minzoom": 13, "maxzoom": 14, "write_to": "roads" },

so that you can define an independent layer (`minor_roads`) and target it from your Lua code, but it's actually written out to the `roads` layer in the tiles at the specified zooms.

**Comment by flamed0011** [comment]
I think this will work. Here is an example based on your proposal. lf I want to write all street data to the road layer, but want to distribute bridges either to road (below 12) or to bridge (above 12) I would do:
```javascript
"road": { "minzoom": 0, "maxzoom": 15 },
"road_bridge": {"minzoom": 0, "maxzoom": 12, "writeto": "road"},
"bridge": { "minzoom": 12, "maxzoom": 15 },
```

```lua
local road = way:Find("highway")
local bridge = way:Find("bridge");
if road~="" then
  if bridge~="" then
    way:Layer("road_bridge", false)
    way:Layer("bridge", false)
  else
    way:Layer("road", false)
  end
end
```
Hope there is no mistake :8ball:

**Comment by systemed** [comment]
I've now implemented this as above: add a `write_to` value for the layer, and it'll be assigned to that layer when the tiles are created. (Note that you can only refer to a layer that's already been defined, so a layer with `"write_to": "roads"` has to come after the `"roads"` layer.)

It works fine for me on a quick test, but let me know how you get on!

**Comment by crofty** [comment]
That looks great, thanks for that.  I'll give it a try soon.

**Comment by flamed0011** [comment]
Thanks alot, you are great.
