### ISSUE TITLE
Layer zoom vs settings zoom

### ISSUE THREAD

**Issue by ClaudioBrocco** [systemed/tilemaker#150]
Hi, great project, thank you!

I have any doubt about the difference between minzoom for the layer and the settings.

If we take the example in resource folder, I see

"layers": {
		"place":            { "minzoom": 4,  "maxzoom": 14 },
...

and 

"settings": {
		"minzoom": 8,
...

at zoom level 4, are the places available or not?

Thank you

**Comment by systemed** [comment]
The global minimum zoom (i.e. within `settings`) controls what level tiles are output at.

So if you have `"minzoom": 8` in settings, no tiles will be generated at zoom level 4, no matter what you put in `layers`.

**Comment by ClaudioBrocco** [comment]
Oh, thank you
