### ISSUE TITLE
Filters based on polygon size

### ISSUE THREAD

**Issue by ClaudioBrocco** [systemed/tilemaker#159]
Hi,

Is it possible in any way to identify and filter the polygons/nodes according to size/extension?

The specific example is to include lakes of a certain size in low zoom levels, while smaller lakes in higher zoom levels (biggest lakes vs. smaller lakes). Filters based on tags are not useful in these cases and neither is the use of shapefiles which are not very useful for Europe.

thank you, fantastic project

**Comment by systemed** [comment]
Yes - you can use way:Area() in your Lua profile. There's a PR in #152 to improve this which I'm hoping to review in the next few days.

**Comment by ClaudioBrocco** [comment]
Oh great, are there examples for this function?

**Comment by systemed** [comment]
This is now merged. In the current code, assuming you're using Boost 1.67 or later, then calling `way:Area()` will return the area of the way in square metres.

You could therefore write lakes only above a certain size like this:

    if way:Area()>10000 then way:Layer("lakes",true) end

**Comment by ClaudioBrocco** [comment]
Thank you! Great!!!
