### ISSUE TITLE
Coastlines

### ISSUE THREAD

**Issue by sabas** [systemed/tilemaker#16]
I tried to render a seaside area (Genoa, Italy), but I got into a problem with coastline. In my extract the coastline isn't closed in the data, so when I try to render it, it closes the segment instead of filling the land.
Tried with both natural=coastline and the place=peninsula multipolygon (I wonder what this is, but... :-) )

![immagine](https://cloud.githubusercontent.com/assets/1304918/9698792/4d4669f2-53c6-11e5-9976-e56242295059.png)

Can you suggest a solution?
I thought I have to render water polygons from openstreetmapdata, or there's a way to close (correctly) the coastline  when creating the extract or when running tilemaker?

Thanks

**Comment by systemed** [comment]
Interesting question. I *doubt* that natural=coastline will be realistic to process on its own. The best approach might be for Tilemaker to support shapefiles, so that you can import (say) openstreetmapdata.com's water polygons. But that'll require both shapefile support and the ability to supply a bounding box to Tilemaker (so that it doesn't render the whole world by accident :) ).

**Comment by pnorman** [comment]
> I *doubt* that natural=coastline will be realistic to process on its own

Provided there is at least **some** coastline in the extract, it's technically possible, relying on the orientation of the coastline. But this would be difficult, and it would be good to have shapefile support for Natural Earth and other sources

**Comment by systemed** [comment]
I've now added shapefile support in a branch: https://github.com/systemed/tilemaker/tree/shapefiles

The configuration docs are updated to explain how it works, but in brief, you import shapefiles directly into a layer by specifying them in the JSON file. Shapefiles must be WGS84 (pure lat/long) and are clipped to the bounding box of the .pbf, unless you specify another bounding box.

Have a play and let me know how you get on. I'm hoping this will land in Tilemaker 1.2 so all feedback is very welcome.

**Comment by sabas** [comment]
Tried making the branch but I can't link libshp apparently (misses the inclusion of shapefil.h) although I've installed it.
```
# ldconfig -p | grep libshp
	libshp.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libshp.so.1
```

**Comment by systemed** [comment]
It looks like it needs `libshp-dev` on Ubuntu. I've added that to the docs - try again?

**Comment by sabas** [comment]
Ok, compiled.
I went to add in the default config.json
```
    "coastlines": {
  "minzoom": 11, "maxzoom": 14,
  "source": "/root/coast/water-polygons-generalized-3857/water_polygons_z7.shp",
  "simplify_below": 13, "simplify_level": 0.0003
                }
        },
```
It goes in segfault, the core (gdb tilemaker core) has
```
Core was generated by `tilemaker Arenzano---43144.pbf --output=arenzano.mbtiles'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f86cdd3294b in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
```

File is http://osm-toolserver-italia.wmflabs.org/estratti/comuni/pbf/Arenzano---43144.pbf

**Comment by systemed** [comment]
Hm. That works fine for me using the `water_polygons_z7.shp` file from openstreetmapdata.com and your .pbf. The error reported is a Lua one - are you using the default Lua script?

**Comment by systemed** [comment]
I've added brief error-trapping to pick up any Lua syntax errors.

**Comment by sabas** [comment]
Recompiled, now exits at the lua errors trap.
```
Error found in Lua script when reading node_keys - check your script for syntax errors.
```
I found my problem in the conversion, I'm a fool and deleted the process.lua, so it wasn't there... :-D
