### ISSUE TITLE
Generating low zoom tiles is deathly slow

### ISSUE THREAD

**Issue by systemed** [systemed/tilemaker#162]
Using the OpenMapTiles schema, each z6 tile takes forever, even though there's _theoretically_ not much in it.

This is presumably because we're writing out all of `landcover` (unsimplified) and `waterway` (simplified).

We could consider an object size filter, which at each zoom level, filters out those items that will be too small to be seen. (It can already be addressed by using multiple layers and `write_to`, but it would be good to automate this to reduce complexity for users.)

We should also obviously test whether my "presumably" is in fact the issue or if something else is happening!

**Comment by typebrook** [comment]
Possibly caused by changes on minzoom from #160 
waterway: z9 -> z6
landcover: z11 -> z6
see this [part](https://github.com/systemed/tilemaker/pull/160/files#diff-9cba7dd7dcd5c2eb47221d40668d9fb5).

**Comment by typebrook** [comment]
@systemed 
ea8afbc should fixed this, could be closed now?

**Comment by systemed** [comment]
Yes, that's made a big difference so we can close this. https://github.com/systemed/tilemaker/commit/e6962f9ddef79793334a012e5b5675efe177c656 is a major improvement when using ocean/coastline polygons too. Still some optimisation work that can be done but I think this can be closed for now.
