### ISSUE TITLE
Change vector tile attribute storage

### ISSUE THREAD

**Issue by systemed** [systemed/tilemaker#163]
Currently we store attributes for each OutputObject (i.e. a geometry+attributes combination that will be eventually written to a vector tile) as a `std::map`, one map per OutputObject.

This is doubly inefficient:

- `std::map` has a mammoth overhead in itself (32 bytes per entry)
- values and (particularly) keys will be repeated thousands of times throughout the tileset

It would be better to have a vector in OutputObject of key and value pair ids, referencing a global dictionary. That could potentially be as little as 4 bytes per pair (1 byte for key id, 3 bytes for value id).

That leaves open the question of the structure used to store the global dictionary. It needs to be ordered/indexed (i.e. so we can retrieve a value by id) but also searchable by value (so when we're creating it, we only add a new entry if it's not already there). Bonus points if it's memory-efficient.

[This 10-year old StackOverflow post](https://stackoverflow.com/questions/2561992/c-need-indexed-set) suggests a map+vector combination. That seems compelling, but given that there are so many new container implementations - sparse_hash and the like - it seems worth considering alternatives.)

ping @pnorman who knows more about this sort of thing than I ever will.

**Comment by pnorman** [comment]
I'm out of date too.

**Comment by tomhughes** [comment]
So if you can go to C++17 then there's a couple of way to reduce the overhead of the map..

First use a `std::unordered_map`which should have lower overhead per node and I don't believe you need ordering. That's available from C++11 on.

Second use a `std::string_view` as the key to avoid duplicating the string from the vector. That needs C++17 though.

So that would give you something like:

```
struct attribute {
   std::string;
   vector_tile::Tile_Value;
}

std::vector<attribute> attributes;
std::unordered_map<std::string_view, attribute *>;
```

**Comment by tomhughes** [comment]
Talking to @systemed the requirement as I understand it is to allocate integer indexes for the items and then to output them in order so I am inclined to suggest keeping everything in a map or set until then end and then moving them to a vector for output, something like:

```
class attribute {
   int index;
   std::string key;
   vector_tile::Tile_Value value;
}

std::unordered_set<attribute> attributes;
```

with `index` filled in by incrementing a counter as attributes are created. To use an unordered set would require a hash and comparison functions on the attribute class that just passed things on to the string.

Then for output:

```
std::vector<attribute>  sorted_attributes(std::move_iterator(attributes.begin()).
                                          std::move_iterator(attributes.end()));

std::sort(sorted_attributes.begin(), sorted_attributes.begin(), []( const auto &a, const auto &b) {
   return a.index < b.index;
));
```

after which the attributes are in `sorted_atttibutes` which can be output in order.

**Comment by systemed** [comment]
Implemented in https://github.com/systemed/tilemaker/commit/04b93a92ca7230c356fe65ece42ea4ec9c428750  - thanks @tomhughes for the theory!
