### ISSUE TITLE
Polygon not processed

### ISSUE THREAD

**Issue by addam** [systemed/tilemaker#168]
There is a polygon in my Openstreetmap excerpt that does not make it into any of the vector tiles. Unfortunately, it's an important one: river Vltava (Moldau) in center of Prague.
![tilemaker](https://user-images.githubusercontent.com/278643/84052712-3616f080-a9b1-11ea-813e-b167368ff473.png)
![mapnik](https://user-images.githubusercontent.com/278643/84052725-3911e100-a9b1-11ea-88d1-d53156d7ac80.png)

It is quite possible that there is an error in the polygon itself. It has a lot of holes and overlapping points (which are considered self-intersections). Still, I need to get it rendered somehow.

There are a lot of errors in the console ("Can't add Attribute class if no Layer set") but none of them seems related to geometry. What can I do to analyse the error in more detail and fix it?

Here is the polygon extracted in .shp [vltava.zip](https://github.com/systemed/tilemaker/files/4747116/vltava.zip)

**Comment by addam** [comment]
It may be the same problem as #143

**Comment by systemed** [comment]
Yep, it's almost certainly an error in the polygon geometry. "Can't add Attribute class if no Layer set" generally indicates that tilemaker has refused to add the shape to a layer because it's invalid; subsequent calls to set its attributes therefore fail. Running with `--verbose` will give the geometry issues.

**Comment by addam** [comment]
Aha, thanks. The error is:
`Relation 19221 has too few pointss 6366`

So it seems to me this bugreport can be linked to #143 and closed.

**Comment by systemed** [comment]
It would be interesting to work out exactly what it is that Boost::Geometry is choking on here. I wonder if it's the two inners abutting each other at https://www.openstreetmap.org/relation/19221#map=19/50.09467/14.44120 .

Ideally it would be good if we could drop any problem inners, so we don't lose the entire multipolygon. https://stackoverflow.com/questions/37112106/how-to-find-self-intersection-in-a-polygon-using-boost looks like it may be relevant.
