### ISSUE TITLE
Broken areas with zoom over 15

### ISSUE THREAD

**Issue by rdsa** [systemed/tilemaker#169]
I'm working on an indoor map using Mapbox GL JS to render the tiles and need to generate tiles for high (18-22) zoom levels. When I generate tiles with zoom > 15 some areas start to break. The higher the zoom the more they break. This is for zoom 18:
![image](https://user-images.githubusercontent.com/21676175/84096476-6625ba00-a9d8-11ea-9090-0dd2d329346d.png)

Same location for zoom 15:
![image](https://user-images.githubusercontent.com/21676175/84097363-bf8ee880-a9da-11ea-8a63-6b6cf868fd88.png)

If I use zoom 15 or less nothing breaks but because of, I think, overzooming, some corners look crooked so I need higher zoom tiles for a better result.

**Comment by systemed** [comment]
By default, Tilemaker doesn't support creating tiles at higher zoom levels (it increases memory consumption and 99% of people only need zoom level 14/15).

If you compile with `-DFAT_TILE_INDEX` then retry, it should be happier.

**Comment by rdsa** [comment]
I'm getting those results with the flag `-DFAT_TILE_INDEX`.

I've tested and this problem happens without the flag for zoom level 16 (this is the highest zoom level that works without the flag) or with the flag on any zoom level greater than 15.

**Comment by rdsa** [comment]
I _think_ I understand what's causing the problem but I have no idea how to solve it as my knowledge on Boost (and C++ in general) is non-existent...

There are two problems, I'll use the images that I uploaded before (zoom level 16) to illustrate:

- First, let's look at the light grey areas, south of the "Quadra" building. Those two areas have 4 nodes each and on zoom level 16 they are split into two tiles, 3 nodes in one tile and the last node in the other tile. This single node is not considered a Geometry and therefore it's simply removed and we end up with a missing part of the area.

- Second, if we look at the "Quadra" building we can see it's not missing any parts but it's name is duplicated. This building has 5 nodes and was also split into two tiles, one with 3 nodes and the other with 2 nodes. Now, unlike the first case, those 2 nodes are considered a Geometry so we actually have two Geometries of the same building and that's causing the duplicated name.

I guess this could happen at any zoom level, but it's obviously more frequent on higher zoom levels as there are more tiles and the chance of areas being split is higher.

I think this is the general idea of what's happening.

**Comment by systemed** [comment]
My current guess is that it might be an issue with the logic used in https://github.com/systemed/tilemaker/blob/6e713f542bfe7ccb733f0ecf4c1cd61773700177/src/coordinates.cpp#L50 to determine which tiles cover a given geometry, but I've not looked into it any further than that.

**Comment by rdsa** [comment]
After some more debugging I found it!

The problem is this line:
https://github.com/systemed/tilemaker/blob/6e713f542bfe7ccb733f0ecf4c1cd61773700177/src/write_geometry.cpp#L133

It removes **all** ways that have 3 nodes, including split areas like the ones I mentioned above. Changing it to:

```c++
if (closePath && len<2) return false;
```

works but I'm not sure what side effects this could have (other than a performance hit).

The second problem I mentioned (duplicate names) still happens. Not sure how to solve this one as those are different geometries in different tiles.

**Comment by systemed** [comment]
Superb! Thank you.

In theory the areas you're looking at have four nodes (ABCA), and that line is meant to filter out areas that have three nodes (which can only be ABA, i.e. not a polygon at all).

_But_ the bug is that `len` is actually the number of nodes minus one, because in lines 114-116 we wrote the start point without incrementing `len`. So your fix makes perfect sense.
