### ISSUE TITLE
pass zoomLevel to way_function & node_function

### ISSUE THREAD

**Issue by flamed0011** [systemed/tilemaker#17]
I'm currently working on a lua process to parse osm.pbf into .mbtiles. The goal is to have a source file which is compatible with the different [mapbox stlyes](https://github.com/mapbox/mapbox-gl-styles/tree/master/styles). The [Mapbox Streets v6 Documentation](https://www.mapbox.com/developers/vector-tiles/mapbox-streets-v6/) gives some details about how the source is handled:

> The roads layers are some of the most complex ones in Mapbox Streets. Starting at zoom level 12,
> tunnels and bridges are broken out of the #road layer into either #tunnel or #bridge.

It would be great to have some information about the zoom layer in way_function and node_function to decide to which layer the way/node should be written. 
A workaround would be to have different config und lua, dependent on the zoom level:
```bash
...
tilemaker --config=./config_zoom_10.json --process=./process_zoom_10.lua test.osm.pbf --output=test.mbtiles
tilemaker --config=./config_zoom_11.json --process=./process_zoom_11.lua test.osm.pbf --output=test.mbtiles
...
```
This doesn't work well because tilemaker overwrites the database content on each call. Because of that it would be necessary to write into different .mbtiles files and then merge them together at the end.

A solution would be to introduce a "overwriteDatabase" switch in the config.json file.

**Comment by systemed** [comment]
What I'm thinking of doing is described here: https://github.com/systemed/tilemaker/issues/15#issuecomment-134551581

That would provide flexibility for situations like this, without growing Tilemaker's memory requirements. (Adding one or two bytes for every way/node to specify zoom levels is ok for a town but requires a bunch more RAM for a whole country!)

Would that meet your requirements?

**Comment by flamed0011** [comment]
Sorry, didn't notice the other issue. I will continue there...
