### ISSUE TITLE
Some tiles have a grey overlay

### ISSUE THREAD

**Issue by leonardehrenfried** [systemed/tilemaker#171]
This week I build a docker image from the current master and after having built our tiles with it, I noticed a grey overlay or "mist" on some of the tiles.

## Current master
![Screenshot from 2020-06-12 14-45-40](https://user-images.githubusercontent.com/151346/84504802-db390e00-acbc-11ea-81d1-08448d53574c.png)

## Version 1.6.0
![Screenshot from 2020-06-12 14-45-42](https://user-images.githubusercontent.com/151346/84504800-daa07780-acbc-11ea-8f8d-4947ab2878b7.png)

I'm using maptiler/tileserver-gl to render raster and vector tiles and I'm seeing this problem with both version 2.6.0 and 3.0.0.

The overlay is visible starting from zoom level 15 and up.

We use the following config files:

- https://github.com/stadtnavi/digitransit-ansible/blob/master/roles/tilemaker/templates/process-openmaptiles.lua
- https://github.com/stadtnavi/digitransit-ansible/blob/master/roles/tilemaker/templates/config-openmaptiles.json

I can build a simple reproduction case in case it is helpful. I can also try to pinpoint the precise commit if that helps.

**Comment by leonardehrenfried** [comment]
Is this perhaps related to #169 because it is also talking about higher zoom level 15?

**Comment by systemed** [comment]
Interesting - haven't seen that before. I doubt it's related to #169 (though who knows). It's _probably_ a large multipolygon which is being clipped incorrectly and filling just that tile only for some reason.

If you can extract the single vector tile from the .mbtiles, then the best thing to do is to dump out what's been written, which should give some clues as to what layer it's in and hence the source of the multipolygon. [vtzero](https://github.com/mapbox/vtzero) has a good set of utilities in the `example/` directory for debugging vector tiles, or you can use [vt2geojson](https://github.com/mapbox/vt2geojson).

**Comment by leonardehrenfried** [comment]
I've used vt2geojson to convert one of the problematic tiles to geojson: https://gist.github.com/leonardehrenfried/82779db6ab3c155cd578d7a195d2b7cc

**Comment by leonardehrenfried** [comment]
This is the same tile after the rollback to version 1.6.0 of tilemaker: https://gist.github.com/leonardehrenfried/f29ef1b63e537a80c1ea8cad4ddeb020

**Comment by systemed** [comment]
The problematic tile gist is truncated, I think? It seems to end halfway through the buildings layer.

**Comment by leonardehrenfried** [comment]
Sorry, I noticed that. I fixed it. Can you take another look (URLs are the same)?

**Comment by systemed** [comment]
Hm. It's a building polygon - on the GeoJSON, you can click on one of the sections that's shaded more lightly, and you'll see it shows as `vt_layer: building`. So my guess is that it's an OSM building with an invalid geometry which is confusing tilemaker.

The best way to tackle this would be (I think) to tweak the Lua profile so it writes the way ID to the buildings layer; then find that way in OSM; see what's wrong with it; and use that as a testcase to improve tilemaker's handling. If we can't handle polygons like this, we should drop them completely.

I'm pretty busy for the next week so unlikely to be able to get to it myself immediately, I'm afraid, but that's how I'd do it. Happy to look at it again when I've got a bit more free time!

**Comment by leonardehrenfried** [comment]
Well, thanks for your work already. In the meantime, I will work towards getting the OSM id into the tile.

**Comment by leonardehrenfried** [comment]
Ok, I managed to go through the debugging steps you mentioned.

Here is the map tile with the building ids: https://gist.github.com/leonardehrenfried/d2ebbfecb7882521eeaefa3c149fb975

The problematic way is the following: https://www.openstreetmap.org/way/145619187

From visual inspection there is nothing wrong with it. Or is there?

**Comment by leonardehrenfried** [comment]
Does tilemaker have a test suite where I could add a regional extract?

**Comment by systemed** [comment]
Great, thanks for that. It looks like the northwest corner is exactly on the top tile boundary, which is interesting. I'll investigate.

**Comment by systemed** [comment]
This looks like a weird boost::geometry edge case. After much digging, I've found something that seems to work, but I'd be interested to know how you get on.

In https://github.com/systemed/tilemaker/blob/master/src/output_object.cpp#L56 , change

    geom::intersection(mp,clippingBox,out);

to

    geom::intersection(mp,clippingPolygon,out);

Recompile and regenerate the tiles and let me know how you get on. I've run it with the OpenMapTiles schema for the affected area and it seems to fix it for me.

**Comment by leonardehrenfried** [comment]
I can confirm that chaning this line also fixes our problem. Thanks so much or your time and knowledge!

**Comment by systemed** [comment]
Excellent! I'll push a change tomorrow.
