### ISSUE TITLE
Boost.Geometry simplify can create self-intersecting polygons

### ISSUE THREAD

**Issue by systemed** [systemed/tilemaker#181]
This can break rendering - for example, I found that the Devon coastline around Exmouth would go AWOL at z9-11.

In https://github.com/systemed/tilemaker/commit/da0fc24a4ee84b2a45a41931cabc14b21ac6d760 I've added a check for when `simplify` makes a polygon invalid; in that case, it'll revert to the unsimplified version. This isn't ideal (particularly with intricate geometries like coastlines) but clearly better than breakage.

The most likely fix for this will be when `dissolve` is merged into Boost.Geometry master. It's currently a (partly unmaintained) extension which isn't realistic for tilemaker users to build.

See https://github.com/boostorg/geometry/pull/460 for comments on `simplify`, https://github.com/boostorg/geometry/issues/447 for a `dissolve` status ticket.

**Comment by swiss-knight** [comment]
I also met this problem several time, which may be related in some way.
It seems that boost cannot handle multipolygons:

```
Problem geom: MULTIPOLYGON()
Boost.Geometry Centroid calculation exception
```

**Comment by systemed** [comment]
Well, Boost.Geometry can certainly handle multipolygons, it's just degenerate ones that it can't necessarily make valid (sometimes for good reason!).

**Comment by systemed** [comment]
Closing in favour of #246.
