### ISSUE TITLE
Not using all threads

### ISSUE THREAD

**Issue by systemed** [systemed/tilemaker#183]
On `great-britain-latest.osm.pbf`, at z14, it drops down to one thread after a while (even on a 24-threaded machine).

**Comment by kleunen** [comment]
You start the number of threads, and then divide the tiles at the zoom level acros the threads. So if you need to generate 192 tiles with a 24 threaded machine, you give each thread 8 tiles. But probably some tiles are generated faster than others. Leaving some threads to do more work than others. 

It is better to have 192 tasks, or even tasks for all tiles on all zoom levels. And start pushing them into threads as soon as they are available. This way you can keep all threads busy until the last tile is finished:

[Task scheduling](https://eli.thegreenplace.net/2016/the-promises-and-challenges-of-stdasync-task-based-parallelism-in-c11/)

**Comment by kleunen** [comment]
We can use the boost asio thread pool. But this will raise the minimum boost version to 1.65 or 1.66. is that issue?

**Comment by systemed** [comment]
Ubuntu 18.04 installs Boost 1.65 so I think that's fine (given that 16.04 goes out of LTS in a couple of months).

**Comment by kleunen** [comment]
The thread pool was introduced in 1.66, so that is a problem ?

**Comment by systemed** [comment]
I guess it's not 100% ideal, but [this ppa](https://launchpad.net/~mhier/+archive/ubuntu/libboost-latest) has builds going back to 14.04, so it should be ok. I'll just need to update the installation instructions.

**Comment by kleunen** [comment]
I think it is worthwile. There are some other small tiny header only libraries also available:
https://github.com/maginatics/threadpool

But I would rather stick to boost::asio, it is a very good library

**Comment by systemed** [comment]
Go for it!

**Comment by kleunen** [comment]
See #197
