### ISSUE TITLE
Aborted (core dumped)

### ISSUE THREAD

**Issue by KushnirDV** [systemed/tilemaker#186]
Hi. Could you help me please?
Why script is aborted?

root@developer:/home/user/tilemaker# tilemaker --input /mnt/data/osm_files/malta-latest.osm.pbf --output /mnt/data/osm_files/malta-latest.mbtiles --config resources/config-openmaptiles.json --process resources/process-openmaptiles.lua
mbtiles file exists, will overwrite (Ctrl-C to abort, rerun with --merge to keep)
Layer place (z4-14)
Layer poi (z12-14)
Layer poi_detail (z14-14) -> poi
Layer housenumber (z14-14)
Layer waterway (z8-14)
Layer waterway_detail (z12-14) -> waterway
Layer transportation (z8-14)
Layer transportation_main (z9-14) -> transportation
Layer transportation_mid (z11-14) -> transportation
Layer transportation_detail (z13-14) -> transportation
Layer transportation_name (z8-14)
Layer transportation_name_mid (z12-14) -> transportation_name
Layer transportation_name_detail (z14-14) -> transportation_name
Layer building (z13-14)
Layer water (z6-14)
Layer ocean (z4-14) -> water
Layer water_name (z14-14)
Layer water_name_detail (z14-14) -> water_name
Layer aeroway (z11-14)
Layer aerodrome_label (z10-14)
Layer park (z11-14)
Layer landuse (z11-14)
Layer landcover (z6-14)
Layer mountain_peak (z11-14)
Reading .shp ocean
Unable to open coastline/water_polygons.shp or coastline/water_polygons.SHP.
Reading .pbf /mnt/data/osm_files/malta-latest.osm.pbf
Can't add Attribute class if no Layer set     
Can't add Attribute class if no Layer set
Can't add Attribute class if no Layer set
Can't add Attribute class if no Layer set
Can't add Attribute class if no Layer set
Can't add Attribute class if no Layer set
Can't add Attribute class if no Layer set
Can't add Attribute class if no Layer set     
Can't add Attribute class if no Layer set
Can't add Attribute network if no Layer set

Stored 333271 nodes, 47081 ways, 147 relations
terminate called after throwing an instance of 'std::runtime_error'
  what():  unrecognized token: "0x4d504258"
Aborted (core dumped)

**Comment by systemed** [comment]
What version of SQLite do you have?

**Comment by systemed** [comment]
https://github.com/systemed/tilemaker/commit/f7a1aa7563733588e418491b8e07d65bd922162c should fix this.

**Comment by systemed** [comment]
Tested and works.

**Comment by KushnirDV** [comment]
Hi.
Sorry for delay.

sqlite3 --version
3.8.2 2013-12-06 14:53:30 27392118af4c38c5203a04b8013e1afdb1cebd0d

Also, 
I changed the code your suggested and there were not any an extra notification in console.

**Comment by systemed** [comment]
Sorry, I don't quite understand - is it working now or not?

**Comment by KushnirDV** [comment]
Hi. 
Unfortunately it is not working now.
I have the same result in console.

**Comment by systemed** [comment]
Ok. I suggest you comment out the line reading

	db << "PRAGMA application_id = 0x4d504258;";

in src/mbtiles.cpp, so that there's nothing between these two lines:

	db << "PRAGMA synchronous = OFF;";
	db << "CREATE TABLE IF NOT EXISTS metadata (name text, value text, UNIQUE (name));";

Recompile and reinstall and you should be good to go.

**Comment by KushnirDV** [comment]
Thank you so much.
It works.
