### ISSUE TITLE
How to generate city names and street names？

### ISSUE THREAD

**Issue by kender1314** [systemed/tilemaker#187]
I executed the command
`docker build . -t tilemaker`
and
`docker run -v /data/tilemaker-data:/srv -i -t --rm tilemaker /srv/ireland-and-northern-ireland.osm.pbf --config resources/config-openmaptiles.json --process resources/process-openmaptiles.lua --output=/srv/ireland-and-northern-ireland.mbtiles`

Contents in the config-openmaptiles.json  :
--------------------------------------------------------------------
{
	"layers": {
		"place":            { "minzoom": 4,  "maxzoom": 14 },

		"poi":              { "minzoom": 12, "maxzoom": 14 },

		"poi_detail":       { "minzoom": 14, "maxzoom": 14, "write_to": "poi"},

		"housenumber":      { "minzoom": 14, "maxzoom": 14 },

		"waterway":         { "minzoom":  8,  "maxzoom": 14, "simplify_below": 12, "simplify_level": 0.0003, "simplify_ratio": 2 },
		"waterway_detail":  { "minzoom": 12,  "maxzoom": 14, "write_to": "waterway" },

		"transportation":             { "minzoom": 8,  "maxzoom": 14, "simplify_below": 13, "simplify_level": 0.0003 },
		"transportation_main":        { "minzoom": 9,  "maxzoom": 14, "simplify_below": 13, "simplify_level": 0.0003, "write_to": "transportation" },
		"transportation_mid":         { "minzoom": 11, "maxzoom": 14, "write_to": "transportation" },
		"transportation_detail":      { "minzoom": 13, "maxzoom": 14, "write_to": "transportation" },
		"transportation_name":        { "minzoom": 8,  "maxzoom": 14 },
		"transportation_name_mid":    { "minzoom": 12, "maxzoom": 14, "write_to": "transportation_name" },
		"transportation_name_detail": { "minzoom": 14, "maxzoom": 14, "write_to": "transportation_name" },

		"building":          { "minzoom": 13, "maxzoom": 14 },

		"water":             { "minzoom": 6,  "maxzoom": 14, "simplify_below": 12, "simplify_length": 1, "simplify_ratio": 2},
		"ocean":             { "minzoom": 4,  "maxzoom": 14, "source": "coastline/water_polygons.shp", "simplify_below": 13, "simplify_level": 0.0005, "write_to": "water" },
		"water_name":        { "minzoom": 14, "maxzoom": 14 },
		"water_name_detail": { "minzoom": 14, "maxzoom": 14, "write_to": "water_name" },

		"aeroway":           { "minzoom": 11, "maxzoom": 14 },
		"aerodrome_label":   { "minzoom": 10,  "maxzoom": 14 },
		"park":              { "minzoom": 11, "maxzoom": 14 },
		"landuse":           { "minzoom": 11, "maxzoom": 14 },
		"landcover":         { "minzoom": 6, "maxzoom": 14, "simplify_below": 13, "simplify_level": 0.0003, "simplify_ratio": 2 },
		"mountain_peak":     { "minzoom": 11, "maxzoom": 14 }
	},
	"settings": {
		"minzoom": 1,
		"maxzoom": 14,
		"basezoom": 14,
		"include_ids": false,
		"name": "Tilemaker to OpenMapTiles schema",
		"version": "3.0",
		"description": "Tile config based on OpenMapTiles schema",
		"compress": "gzip"
	}
}
----------------------------------------------------------------------------

The resulting map looks like this
![image](https://user-images.githubusercontent.com/37035331/96215224-ff309700-0faf-11eb-9666-5125049e9160.png)
No city name, no street name

How can these names be generated?
Thanks！

**Comment by systemed** [comment]
What style are you using?

**Comment by kender1314** [comment]
> What style are you using?

basic-preview

**Comment by systemed** [comment]
Link?

**Comment by kender1314** [comment]
> Link?

Sorry, I didn't understand what you mean, and I just contacted the map service not long ago. This map service was created on Centos 7 in a virtual machine.

**Comment by systemed** [comment]
Can you supply a link to the style. I have absolutely no idea what or where "basic-preview" is.

**Comment by kender1314** [comment]
I used the docker image of this project to build a container,[https://github.com/maptiler/tileserver-gl]( https://github.com/maptiler/tileserver-gl). docker image[https://hub.docker.com/r/maptiler/tileserver-gl]( https://hub.docker.com/r/maptiler/tileserver-gl)

**Comment by kender1314** [comment]
> I used the docker image of this project to build a container,https://github.com/maptiler/tileserver-gl. docker imagehttps://hub.docker.com/r/maptiler/tileserver-gl

**Comment by systemed** [comment]
This looks like https://github.com/maptiler/tileserver-gl/issues/267 to me.

My guess is that tileserver-gl is pulling down a style that expects the name to be in the `name_en` attribute. tilemaker writes it to the `name:latin` attribute. 

If you change line 436 of `process-openmaptiles.lua` from

	obj:Attribute("name:latin", obj:Find("name"))

to

	obj:Attribute("name_en", obj:Find("name"))

then it may fix it.

**Comment by kender1314** [comment]
> name_en

let me try

**Comment by kender1314** [comment]
> This looks like [maptiler/tileserver-gl#267](https://github.com/maptiler/tileserver-gl/issues/267) to me.
> 
> My guess is that tileserver-gl is pulling down a style that expects the name to be in the `name_en` attribute. tilemaker writes it to the `name:latin` attribute.
> 
> If you change line 436 of `process-openmaptiles.lua` from
> 
> ```
> obj:Attribute("name:latin", obj:Find("name"))
> ```
> 
> to
> 
> ```
> obj:Attribute("name_en", obj:Find("name"))
> ```
> 
> then it may fix it.

Thank you very much, I solved this problem. As you said, Openmaptiles has modified the logic to generate data in v3. [maptiler/tileserver-gl#267](https://github.com/maptiler/tileserver-gl/issues/267). After I changed to klokantech/tileserver-gl (the version used here is 2.x), the data can be displayed normally. Thank you again for your help, hope the ecology of tilemaker will get better and better.
