### ISSUE TITLE
Geometry is empty in OsmLuaProcessing::LayerAsCentroid

### ISSUE THREAD

**Issue by kender1314** [systemed/tilemaker#188]
When I execute these commands to generate china-latest.mbtiles.

`time docker run -v /data/tilemaker-data:/srv -i -t --rm tilemaker /srv/china-latest.osm.pbf --config resources/config-openmaptiles.json --process resources/process-openmaptiles.lua --output=/srv/china-latest.mbtiles`

Several errors occurred in the docker container:
-------------------------------------------------------
Reading .shp ocean
Reading .pbf /srv/china-latest.osm.pbf
Can't set minimum zoom if no Layer sets 0        
Can't add Attribute class if no Layer set
Can't add Attribute subclass if no Layer set
Can't add Attribute class if no Layer set        
Can't add Attribute class if no Layer set        
Can't set minimum zoom if no Layer sets 0        
Can't add Attribute class if no Layer set        
Can't set minimum zoom if no Layer sets 0        
Can't add Attribute class if no Layer set
Can't add Attribute subclass if no Layer set
Can't set minimum zoom if no Layer sets 0        
Can't add Attribute class if no Layer set        
Can't set minimum zoom if no Layer sets 0        
Can't add Attribute class if no Layer set
Can't set minimum zoom if no Layer sets 0        
Can't set minimum zoom if no Layer sets 0        
Can't add Attribute class if no Layer set        
Can't add Attribute class if no Layer set
Can't set minimum zoom if no Layer sets 0        
Can't add Attribute class if no Layer set
Can't add Attribute subclass if no Layer set
Can't set minimum zoom if no Layer sets 0        
Can't set minimum zoom if no Layer sets 0        
Can't set minimum zoom if no Layer sets 0        
Can't add Attribute class if no Layer set
Can't add Attribute subclass if no Layer set
Can't set minimum zoom if no Layer set
Can't add Attribute class if no Layer set
Can't add Attribute subclass if no Layer set
Can't set minimum zoom if no Layer set
Can't add Attribute class if no Layer set
Can't add Attribute subclass if no Layer set
Can't set minimum zoom if no Layer set
Can't add Attribute class if no Layer set
Can't add Attribute subclass if no Layer set
Can't set minimum zoom if no Layer sets 0        
Can't add Attribute class if no Layer set
Can't add Attribute subclass if no Layer set
Can't set minimum zoom if no Layer sets 0        
Can't set minimum zoom if no Layer sets 0        
Can't add Attribute class if no Layer set
Can't add Attribute subclass if no Layer set
Can't add Attribute class if no Layer set        
Can't set minimum zoom if no Layer sets 0        
Can't add Attribute class if no Layer set
Can't set minimum zoom if no Layer sets 0        
Can't add Attribute class if no Layer set        
Can't set minimum zoom if no Layer sets 0        
Can't set minimum zoom if no Layer set
Can't set minimum zoom if no Layer sets 0        
Can't set minimum zoom if no Layer sets 0        
Can't set minimum zoom if no Layer sets 0        
Can't add Attribute class if no Layer set        
Can't add Attribute class if no Layer set        
Can't add Attribute name:latin if no Layer set
Can't add Attribute class if no Layer set        
Can't add Attribute class if no Layer set        
Can't set minimum zoom if no Layer sets 0        
Can't set minimum zoom if no Layer sets 0        
Can't add Attribute class if no Layer set        
Can't set minimum zoom if no Layer set
Can't add Attribute class if no Layer set        
Can't add Attribute class if no Layer set        
Can't set minimum zoom if no Layer sets 0        
Can't add Attribute class if no Layer set
Can't add Attribute subclass if no Layer set
Can't add Attribute class if no Layer set        
Can't set minimum zoom if no Layer sets 0        
Can't set minimum zoom if no Layer set
Can't set minimum zoom if no Layer sets 0        
Can't set minimum zoom if no Layer sets 0        
Can't set minimum zoom if no Layer set
Can't set minimum zoom if no Layer sets 0        
Can't set minimum zoom if no Layer sets 0        
Can't set minimum zoom if no Layer sets 0        
Can't add Attribute class if no Layer set        
Can't add Attribute class if no Layer set        
Can't set minimum zoom if no Layer sets 0        
Can't set minimum zoom if no Layer sets 0        
Can't add Attribute class if no Layer set
Can't add Attribute subclass if no Layer set
Can't set minimum zoom if no Layer set
Can't set minimum zoom if no Layer set
Can't set minimum zoom if no Layer set
Can't set minimum zoom if no Layer set
Can't set minimum zoom if no Layer set
Can't set minimum zoom if no Layer set
Can't add Attribute class if no Layer set        
Can't set minimum zoom if no Layer sets 0        
Can't add Attribute class if no Layer set        
Can't set minimum zoom if no Layer sets 0        
Can't add Attribute class if no Layer set
Can't add Attribute subclass if no Layer set
Can't add Attribute class if no Layer set        
Can't set minimum zoom if no Layer sets 0        
Can't add Attribute class if no Layer set
Can't add Attribute subclass if no Layer set
Can't set minimum zoom if no Layer set
Can't add Attribute class if no Layer set
Can't add Attribute subclass if no Layer set
Can't set minimum zoom if no Layer set
Can't add Attribute class if no Layer set
Can't add Attribute subclass if no Layer set
Can't set minimum zoom if no Layer sets 0        
Can't add Attribute class if no Layer set
Can't add Attribute subclass if no Layer set
Can't set minimum zoom if no Layer sets 0        
Can't set minimum zoom if no Layer sets 0        
Can't set minimum zoom if no Layer sets 0        
Can't set minimum zoom if no Layer sets 0        
Can't set minimum zoom if no Layer sets 0        
Can't set minimum zoom if no Layer sets 0        
Can't add Attribute class if no Layer set        
Can't add Attribute class if no Layer set
Can't set minimum zoom if no Layer sets 0        
Can't set minimum zoom if no Layer set000        
Can't add Attribute class if no Layer set
Can't set minimum zoom if no Layer set
Can't add Attribute class if no Layer set
Can't set minimum zoom if no Layer set
Can't add Attribute class if no Layer set
Geometry is empty in OsmLuaProcessing::LayerAsCentroid
Can't set minimum zoom if no Layer set
Can't add Attribute class if no Layer set
Can't set minimum zoom if no Layer set
Can't add Attribute class if no Layer set
Can't set minimum zoom if no Layer set000        
Can't set minimum zoom if no Layer set
Can't add Attribute class if no Layer set
Can't add Attribute subclass if no Layer set
Can't set minimum zoom if no Layer set
Can't set minimum zoom if no Layer set
Geometry is empty in OsmLuaProcessing::LayerAsCentroid
Can't set minimum zoom if no Layer set
Can't add Attribute class if no Layer set
Geometry is empty in OsmLuaProcessing::LayerAsCentroid
Can't set minimum zoom if no Layer set000        
Can't add Attribute class if no Layer set
Can't set minimum zoom if no Layer set
Can't set minimum zoom if no Layer set
Can't add Attribute class if no Layer set
Can't set minimum zoom if no Layer set000        
Can't add Attribute class if no Layer set
Can't add Attribute subclass if no Layer set
Can't set minimum zoom if no Layer set
Can't add Attribute class if no Layer set
Can't add Attribute subclass if no Layer set
Can't add Attribute class if no Layer set        
Can't add Attribute class if no Layer set
Can't set minimum zoom if no Layer set
Can't add Attribute class if no Layer set
Can't add Attribute subclass if no Layer set
Geometry is empty in OsmLuaProcessing::LayerAsCentroid
Can't set minimum zoom if no Layer set000        
Can't add Attribute class if no Layer set
Can't set minimum zoom if no Layer set
Can't add Attribute class if no Layer set
Can't add Attribute class if no Layer set
Geometry is empty in OsmLuaProcessing::LayerAsCentroid
Can't add Attribute rank if no Layer set
Can't add Attribute class if no Layer set
Can't add Attribute subclass if no Layer set
Geometry is empty in OsmLuaProcessing::LayerAsCentroid
Can't set minimum zoom if no Layer set
Can't add Attribute class if no Layer set
Can't add Attribute subclass if no Layer set
Can't set minimum zoom if no Layer set
Can't add Attribute class if no Layer set
Can't add Attribute class if no Layer set
Can't add Attribute class if no Layer set
Can't add Attribute class if no Layer set
Can't add Attribute class if no Layer set
Can't add Attribute class if no Layer set
Can't add Attribute class if no Layer set
Can't add Attribute class if no Layer set
Can't add Attribute class if no Layer set
Can't add Attribute class if no Layer set
Can't add Attribute class if no Layer set
Can't add Attribute class if no Layer set
Can't add Attribute class if no Layer set
Can't add Attribute class if no Layer set
Can't set minimum zoom if no Layer set
Can't add Attribute class if no Layer set
Can't set minimum zoom if no Layer set000        
Can't add Attribute class if no Layer set
Can't add Attribute subclass if no Layer set
Can't set minimum zoom if no Layer set
Can't add Attribute class if no Layer set
Can't add Attribute subclass if no Layer set
Geometry is empty in OsmLuaProcessing::LayerAsCentroid
Geometry is empty in OsmLuaProcessing::LayerAsCentroid
Can't set minimum zoom if no Layer set
Can't set minimum zoom if no Layer set
Can't add Attribute class if no Layer set
Can't add Attribute class if no Layer set
Can't add Attribute class if no Layer set
Can't add Attribute network if no Layer set
Can't add Attribute class if no Layer set
Can't add Attribute class if no Layer set
Can't add Attribute network if no Layer set
Geometry is empty in OsmLuaProcessing::LayerAsCentroid
Can't set minimum zoom if no Layer set
Geometry is empty in OsmLuaProcessing::LayerAsCentroid
Geometry is empty in OsmLuaProcessing::LayerAsCentroid
Geometry is empty in OsmLuaProcessing::LayerAsCentroid
Can't set minimum zoom if no Layer set
Can't add Attribute class if no Layer set
Geometry is empty in OsmLuaProcessing::LayerAsCentroid
-------------------------------------------------------

"Geometry is empty in OsmLuaProcessing::LayerAsCentroid"

What caused this problem?
After this error occurs, the execution process will take more time.

My .pbf data is downloaded from [here](https://download.geofabrik.de/).

I created the coastline folder and imported ocean data.

**Comment by systemed** [comment]
Invalid geometries in the source data. It’s not significant, OSM is full of them.
