### ISSUE TITLE
center missing in generated tiles

### ISSUE THREAD

**Issue by DigNZ** [systemed/tilemaker#189]
Issue #106 Had this listed, looks like bounds, minzoom and maxzoom were included but center was not. Its causing an issue previewing tiles on some viewers.

**Comment by systemed** [comment]
`center` will be written to the metadata if you set `default_view` in your JSON config file - it should be `[lat,lon,zoom]`.

**Comment by DigNZ** [comment]
Ah I see, I thought it was calculated from the bounds. All good.
