### ISSUE TITLE
tilemaker > mapbox-gl-js stack example

### ISSUE THREAD

**Issue by flamed0011** [systemed/tilemaker#19]
This is not an issue, but maybe it helps someone to learn how to use the tilemaker > mapbox-gl-js stack:

At https://github.com/flamed0011/tilemaker you can find a process.lua to process a .osm.pbf (e.g. extracts from http://extract.bbbike.org) to vector tiles which are compatible with mapbox-gl-js.

An example to render these tiles via (a modified) mapbox-gl-js you can find at https://github.com/flamed0011/mapbox-gl-js-cordova-offline-example . The example extracts the tiles directly from the database without a server and renders the data in a cordova app. Important references are https://github.com/mapbox/mapbox-gl-styles and https://www.mapbox.com/developers/vector-tiles/mapbox-streets-v6/ .

I wil update the readme files of the two repos with more details. The process.lua is not really clean for now, but work in progress. Maybe it would be great to put a process_osm.lua to this repo?

**Comment by systemed** [comment]
That looks really good. I'll take a proper look later, but I'm thinking about adding a `resources/` directory to the tilemaker repo which includes extra styles and things like that. (Similarly to your cordova app, I've put together a quick Ruby server that serves individual .pbf tiles from an .mbtiles.)

**Comment by systemed** [comment]
Config files added to the new `resources/` directory. Thank you!
