### ISSUE TITLE
--merge is misleading

### ISSUE THREAD

**Issue by uvwxy** [systemed/tilemaker#192]
>  --merge                      merge with existing .mbtiles (overwrites otherwise)

it should rather be

>  --merge                      overwrite tiles in existing .mbtiles

because the resulting output is not as expected.

If I run tilemaker on two .pbf files with `--merge` my expectation was that the results from both files are usable/viewable, and not just the first + overwritten by the second.

I assume this is not a trivial issue.

**Comment by kleunen** [comment]
I have noticed this issue too. I set the boundingbox on the edge of a tile, but tilemaker generates tiles also outside the boundingbox. I have made an attempt to fix this, but have not been able too fix it

**Comment by systemed** [comment]
This should be fixed now in #225 and #224.
