### ISSUE TITLE
process-openmaptiles.lua doesn't do admin boundaries

### ISSUE THREAD

**Issue by systemed** [systemed/tilemaker#196]
Schema details at https://openmaptiles.org/schema/#boundary .

For a first pass we should support `admin_level` and `maritime` from OSM data only. The rest are nice-to-haves (and hard-to-implements) really.

**Comment by kleunen** [comment]
But if i use the carto style? I can get borders?

**Comment by systemed** [comment]
We pretty much use an exact copy of the OpenMapTiles style - it's just the processing chain that's different (i.e. Lua vs whatever OMT use). So yes, as long as you can get the data into the tiles, I'd expect the OMT style to render it properly.

**Comment by kleunen** [comment]
But if I use the carto style ? Then which config.json should I use. Because the carto github does not have this config.json file ?

**Comment by systemed** [comment]
Ah, do you mean openstreetmap-carto? The vector tile ports of that are https://github.com/geofabrik/openstreetmap-carto-vector-tiles/blob/master/README_VECTOR_TILES.md and https://github.com/pnorman/openstreetmap-cartographic . I don't believe there's a tilemaker config.json or (more difficult) process.lua for either of those. It would be quite an interesting thing to do though, and probably not too hard.

**Comment by kleunen** [comment]
I see, now i understand. It is quite complicated how these maps are generated.

**Comment by kleunen** [comment]
The SQL queries use a "pull" model (pull in the OSM data from the DB). While this renderer uses a "push" model, a OSM point/way is pushed into the renderer and the selected attributes are applied.

**Comment by systemed** [comment]
Exactly that!

I'd be happy to have a look at doing an osm-carto-like Lua script for tilemaker - it's not something I can promise to do immediately but when I have some spare time it might be interesting.

**Comment by kleunen** [comment]
yes, that would be nice. I guess using a PostGis/postgresql db as input is the standard in OSM world nowadays ?

**Comment by systemed** [comment]
Postgres is very much the standard for storing OSM data in a database, but it's not compulsory for making vector tiles - there's a couple of other approaches (tilemaker, tippecanoe, and a few others like Grandine tiler).

**Comment by systemed** [comment]
Work in progress:

![Screenshot 2021-03-21 at 01 20 05](https://user-images.githubusercontent.com/694425/111890669-9c6e7c00-89e3-11eb-99c7-2d57335c9490.png)

**Comment by systemed** [comment]
Fixed in https://github.com/systemed/tilemaker/commit/40834a06a535f8b44eb50d506f76a07fa0d3152f.

**Comment by kleunen** [comment]
Looks very good
![image](https://user-images.githubusercontent.com/230050/111982318-1b110980-8b09-11eb-9c59-08a3be897d3f.png)
