### ISSUE TITLE
Return an alternative with data allocation in memory

### ISSUE THREAD

**Issue by freeExec** [systemed/tilemaker#216]
Set via command line, use storage as file or RAM.

It seems that it should be easy to implement, the choice between `managed_mapped_file` and `managed_windows_shared_memory`.

For my tasks, 16GB of RAM is enough, and creating such large files looks like unnecessary and overhead

**Comment by kleunen** [comment]
It would definitly be useful, but it is not as easy to implement as you suggest. Many of the datatypes which are stored are dependent now on 'managed_mapped_file'. When you can do is put the osm_store.data on tmpfs, that way no file is created.

**Comment by kleunen** [comment]
Have a look at #217

**Comment by systemed** [comment]
Fixed in #217.
