### ISSUE TITLE
ocean missing

### ISSUE THREAD

**Issue by kleunen** [systemed/tilemaker#220]
I rendered now one quarter of the planet (south america). But what I see now is that when I zoom out, the ocean is there:

![image](https://user-images.githubusercontent.com/230050/114093590-98839a80-98bb-11eb-8aea-033eaa24dbe4.png)

But when I zoom in, the ocean is missing:

![image](https://user-images.githubusercontent.com/230050/114093985-0def6b00-98bc-11eb-89bd-6bc6e5f4aa53.png)

The bounding box is: -180.000000,-90.000000,0.000000,0.000000
The export of this part of the planet is actually only 2.4G. 
But somewhere around 14M tiles are generated. 

I can see cities like sao paulo: 
![image](https://user-images.githubusercontent.com/230050/114094167-468f4480-98bc-11eb-9b83-bc5ed88cc90a.png)

**Comment by systemed** [comment]
Hm, that's odd. What are you using for the .osm.pbf file - is it just a plain South America .osm.pbf from Geofabrik?

**Comment by kleunen** [comment]
No i did an extract on the full planet. Maybe i will try extract from geofabrik with only brazil. I also changed something to further reduce memory on generation of tiles. Maybe this has some influence.

**Comment by kleunen** [comment]
it's an issue only in my local branch :D
oops :D
