### ISSUE TITLE
Tiles generation fails with "Boost.Geometry Inconsistent Turns exception"

### ISSUE THREAD

**Issue by QuentinC** [systemed/tilemaker#231]
Hello,

I'm trying to generate France mbtiles from geofabrik export (france-latest.osm.pbf).
I'm using the provided config and process files, on the current master branch. It's running on docker.

When running, tiles generation stops at zoom level 13 with:
```
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::geometry::inconsistent_turns_exception> >'
 what():  Boost.Geometry Inconsistent Turns exception
```

I don't have the issue when building smaller regions.

Here is the full log file: [france.log](https://github.com/systemed/tilemaker/files/6398329/france.log)

Thanks !

**Comment by systemed** [comment]
Oh boy, this will be fun to track down ;)

I'll have a look, but obviously tracking something down with a dataset as big as France is going to be slow. There will be a dodgy geometry somewhere in France which is confusing tilemaker - if by any chance you can find which part of France it is (i.e. which region) then that might make it quicker. But I'll have a go anyway.

**Comment by systemed** [comment]
https://github.com/systemed/tilemaker/commit/244614b2daea3d0506e4676b393e0f306b305543 fixes this.

Do let me know what object ID it outputs with the "inconsistent turns" message when you run the new code - I'd be interested to know! (I tested it on a renumbered extract so didn't see the original ID.)

**Comment by QuentinC** [comment]
Woh that was fast !! Thanks a lot, it works for France now !
Here is the faulty geometry: `Inconsistent turns error while processing OutputGeometryType::LINESTRING: 199993833`

I will continue to test this amazing software with bigger exports (Europe, and maybe Planet but I only have 128gb of ram at the moment so not sure of the result !)

**Comment by systemed** [comment]
That's odd - I can't see anything odd about that way. Just a weird edge case, I guess! Interested to know how you get on with bigger areas.
