### ISSUE TITLE
Huge pbf file breaks while reading file

### ISSUE THREAD

**Issue by QuentinC** [systemed/tilemaker#233]
Hello,

I've been working on making this working on bigger and bigger files today.
I've have been able to import France and UK perfectly with the help of https://github.com/systemed/tilemaker/commit/244614b2daea3d0506e4676b393e0f306b305543 but I haven succeeded to import Europe at all.

The program "just" exits while resizing the OSM store.
Here is an example of the last log lines on the console: 
```
Resizing osm store to size: 50176M
Resizing osm store to size: 51200M
Resizing osm store to size: 52224M
Resizing osm store to size: 53248M
Resizing osm store to size: 54272M
Resizing osm store to size: 55296M
Resizing osm store to size: 56320M
Resizing osm store to size: 57344M
Resizing osm store to size: 58368M
Resizing osm store to size: 59392M
Resizing osm store to size: 60416M
Resizing osm store to size: 61440M
Resizing osm store to size: 62464M
Resizing osm store to size: 63488M
Resizing osm store to size: 64512M
Resizing osm store to size: 65536M
root@tileserver:/data# ys 0 relations 0
root@tileserver:/data#
```
My server have 128GB RAM and 500GB of SSD SWAP so the memory shouldn't be the issue...
I've tried to use a file store, with initial size set using `osmium fileinfo` but I got the same result.

Same result also with renumbered .osm.pbf ...

Is there any way to add more logs in order to identify the issue ? 

Thanks a lot !

**Comment by kleunen** [comment]
Are you sure the process does not get killed by the OOM killer ? 
have a look at the output of 'dmesg' command to see if the kernel has killed your process.

**Comment by kleunen** [comment]
One way to know where it crashes is to run the application in gdb and get a backtrace when it crashes. But you would have to use the debug build, which is slow.

**Comment by kleunen** [comment]
I tried reproducing, but up to this point, for me it is not crashing:

Resizing osm store to size: 65536M
Resizing osm store to size: 73728M
Block 149608 group 0 ways 0 relations 0

Are you using the Europe extract from geofabrik ? and the openmaptiles config/process ?

**Comment by QuentinC** [comment]
I've launched the process yesterday, and it's still running ! (crossing fingers)
I'm using a file based store, and it's currently resizing to 140GB !

Yes I'm using the extract from geofabrik and the config/process provided by this repo.

This indeed looks like an OOM issue, I will let this run finish, seems on a good way !

**Comment by QuentinC** [comment]
Well It just failed...
I didn't have an issue with OOM, but I got this error in the dmesg log:
`[mai 1 21:41] traps: tilemaker[87624] general protection ip:55ffe7b428f1 sp:7ffc873840f0 error:0 in tilemaker[55ffe7991000+1ba000]`
I don't know what this mean yet, I will investigate but it might no be the fault of the software...

**Comment by kleunen** [comment]
Yes it might be a hardware issue? Maybe test memory and cpu?

**Comment by kleunen** [comment]
Is it amd ryzen ?

**Comment by QuentinC** [comment]
It's running on a VM hosted on a Dell R620 (Xeon E5-2609).
It's not exactly new so it might be a hardware issue

**Comment by kleunen** [comment]
Yes. I would recommend checking the cpu, memory and also disk. Possibly it is the disk, because you do a large conversion it gets swapped to disk. Maybe this gets corrupted?

**Comment by QuentinC** [comment]
Hello,
I've been running this for 5 days now on an other server, but without SSD.
It's obviously very slow (I have done 360k blocks at the moment), but it didn't crash !
I've ordered an NVME SSD  to help.

It really seems to be a hardware related issue.

**Comment by kleunen** [comment]
Yes, a fast SSD is really needed.

**Comment by QuentinC** [comment]
I had to reboot my server so my test with Europe hasn't been able to complete.
I am closing this issue for now as I didn't have any fail with this server, It was surely hardware related.

One last question, reading blocks takes a lot of time, and there is no indicator on the progress. Is there a way to know at least how much blocks that the process as to read ?

Anyway thanks for this great project !

**Comment by kleunen** [comment]
Osmium is able to count the number of nodes/ways/relations and possibly the fileoffset can be used as an indication. I don't think the file contains information on the total number of blocks.
