### ISSUE TITLE
There are cases where polygons are not displayed

### ISSUE THREAD

**Issue by toshelp** [systemed/tilemaker#235]
When I checked with https://github.com/systemed/tilemaker/commit/12b34febc71df71da26529a58f48bbd750c7c194, I found that island polygons were not displayed in some cases.
I used TileserverGL v3.1.1  for the check.

environment
os: ubuntu20.04 docker image (host ubuntu20.04)
boost: v1.71
pbf source : [scotland.pbf](http://download.geofabrik.de/europe/great-britain/scotland-latest.osm.pbf)
coastline source: [coastline](https://osmdata.openstreetmap.de/download/water-polygons-split-4326.zip)

scotland zoom7
![scotland_z7_coastline](https://user-images.githubusercontent.com/72679776/117161224-b54cb880-adfc-11eb-8f9a-6a3d4d655dbc.png)

scotland zoom6
![scotland_z7_coastline](https://user-images.githubusercontent.com/72679776/117161242-b7167c00-adfc-11eb-8425-b6ebfbcb3ea7.png)

No problem occurs except for zoom 7.

**Comment by kleunen** [comment]
I removed some within checks from the polygon clipping, possibly, i should not have done this. 
https://github.com/systemed/tilemaker/commit/12b34febc71df71da26529a58f48bbd750c7c194#diff-3cdbb3e4f11f8cb51d139e1746bd6f49c782699317324c570ca6737bdef97f78L94-L99

We can try putting it back and see if it makes a difference ?

**Comment by kleunen** [comment]
I also see this message in my console from mapbox:
Max vertices per segment is 65535: bucket requested 70960

**Comment by kleunen** [comment]
I tried putting back:
#diff-3cdbb3e4f11f8cb51d139e1746bd6f49c782699317324c570ca6737bdef97f78L94-L99

But it seems to make no difference. 

Possibly this 'Max vertices per segment is 65535: bucket requested 87640' is at fault here. The polygon is too complex when inside a single tile and reappears again after simplification at lower zoom levels.

**Comment by systemed** [comment]
I'm not sure that the latest commit is the issue - I think the problem was introduced earlier. Somewhere between b15c937 and 9afb9f1, I think.

**Comment by toshelp** [comment]
https://github.com/systemed/tilemaker/commit/f41aa522967ebe1d93310bee6093926500626165 seems to have an effect. 
However, reverting https://github.com/systemed/tilemaker/commit/f41aa522967ebe1d93310bee6093926500626165, https://github.com/systemed/tilemaker/issues/215 will be reproduced.

I also found some polygons that were not affected by this change. I think there is another issue.
![scotland_polygons](https://user-images.githubusercontent.com/72679776/117231224-c4158880-ae59-11eb-9182-e06d277de91b.png)

**Comment by kleunen** [comment]
> I think there is another issue.

Possibly that is caused by these polygons having more > 65535 vertices ?

**Comment by kleunen** [comment]
> However, reverting [f41aa52](https://github.com/systemed/tilemaker/commit/f41aa522967ebe1d93310bee6093926500626165), #215 will be reproduced.

Even without f41aa52 issue #215 should be resolved with the PR #234

**Comment by kleunen** [comment]
> [f41aa52](https://github.com/systemed/tilemaker/commit/f41aa522967ebe1d93310bee6093926500626165) seems to have an effect.
> However, reverting [f41aa52](https://github.com/systemed/tilemaker/commit/f41aa522967ebe1d93310bee6093926500626165), #215 will be reproduced.

I reverted f41aa52, but I still see the issue

**Comment by kleunen** [comment]
I went back to '1d06388'

And even this did not resolve the issue. So I think it is not related to a specific commit.

**Comment by kleunen** [comment]
If I go back to 435daf3

the issue is resolved

**Comment by kleunen** [comment]
So it is 4399349 and 6b111cc which are causing the problems. The minzoom related stuff.

**Comment by systemed** [comment]
That's strange - they shouldn't be interacting with this at all.

**Comment by kleunen** [comment]
I am not 100% sure about the commits. I tried commit '6b111cc', and it still works. 
I am missing something here ..

**Comment by systemed** [comment]
I don't think tilemaker is 100% deterministic when running multi-threaded, which may explain the unpredictable results.

**Comment by kleunen** [comment]
I see, hmm, that is not good :D

Maybe try the rendering with HEAD in single threaded ?

**Comment by toshelp** [comment]
I tried HEAD(https://github.com/systemed/tilemaker/commit/12b34febc71df71da26529a58f48bbd750c7c194) with a single thread, but didn't resolve the issue.
I used the ```--thread 1``` option to run tilemaker.

**Comment by kleunen** [comment]
I guess it is then an issue with a certain commit, but which one ..

**Comment by kleunen** [comment]
> > [f41aa52](https://github.com/systemed/tilemaker/commit/f41aa522967ebe1d93310bee6093926500626165) seems to have an effect.
> > However, reverting [f41aa52](https://github.com/systemed/tilemaker/commit/f41aa522967ebe1d93310bee6093926500626165), #215 will be reproduced.
> 
> I reverted [f41aa52](https://github.com/systemed/tilemaker/commit/f41aa522967ebe1d93310bee6093926500626165), but I still see the issue. Does this resolve the issue for you ?

I believe toshelp is correct, f41aa52 causes this issue. Maybe the other island is related to the max vertices

**Comment by kleunen** [comment]
I guess the rounding makes the polygon invalid ? maybe self intersecting ? Maybe start simplifying these polygons earlier ? Before zoom level 7?

**Comment by systemed** [comment]
I guess it must... seems odd but hey. If we're fixing the simplification then the best thing to do would be to default simplifyRatio to 2.0 rather than 1.0 (in sharedData.cpp):

    double simplifyRatio  = it->value.HasMember("simplify_ratio" ) ? it->value["simplify_ratio" ].GetDouble() : 1.0;

as keeping the same ratio for every zoom level doesn't make a lot of sense.

**Comment by kleunen** [comment]
i will give it a try

**Comment by kleunen** [comment]
Simplification does not seem to resolve the issue

**Comment by kleunen** [comment]
Try #236

**Comment by toshelp** [comment]
I changed simplify_level, but the result was not what I expected.
It seems that there are cases where simplification does not work.

```
config-openmaptiles.json
- "ocean":  { "minzoom": 0,  "maxzoom": 14, "source": "coastline/water_polygons.shp", "simplify_below": 13, "simplify_level": 0.0005, "write_to": "water", "index": true },  
+ "ocean":  { "minzoom": 0,  "maxzoom": 14, "source": "coastline/water_polygons.shp", "simplify_below": 13, "simplify_level": 0.01, "write_to": "water", "index": true }, 
```

simplify_level 0.0005
![simplify_0 0005](https://user-images.githubusercontent.com/72679776/117409582-4d0cec80-af4c-11eb-8c56-c4a19c30ded0.png)

simplify_level 0.01
![simplify_0 01](https://user-images.githubusercontent.com/72679776/117409635-5bf39f00-af4c-11eb-815b-c107f8975934.png)

**Comment by kleunen** [comment]
Can you try #236 ? 
For me, this works ok. Also, the tile transitions are ok with this.

**Comment by toshelp** [comment]
I tried #236 and the results are very improved!
It may be a problem in my environment, but I'll take a look at the following.
![floorpatch](https://user-images.githubusercontent.com/72679776/117418040-ed1b4380-af55-11eb-8a25-e382e0f0ebfb.png)

**Comment by kleunen** [comment]
Possibly. I have not seen this issue. But maybe i did not check correctly.

**Comment by kleunen** [comment]
@toshelp I have not checked correctly. I also see this island not being rendered at zoom level 6. So it is not related to your local configuration. I do see: 

31dcdf25-daac-4a55-bad6-4440c1afd9ae:1 Max vertices per segment is 65535: bucket requested 80960
E @ 31dcdf25-daac-4a55-bad6-4440c1afd9ae:1
31dcdf25-daac-4a55-bad6-4440c1afd9ae:1 Max vertices per segment is 65535: bucket requested 87650
E @ 31dcdf25-daac-4a55-bad6-4440c1afd9ae:1
31dcdf25-daac-4a55-bad6-4440c1afd9ae:1 Max vertices per segment is 65535: bucket requested 71050
E @ 31dcdf25-daac-4a55-bad6-4440c1afd9ae:1
31dcdf25-daac-4a55-bad6-4440c1afd9ae:1 Max vertices per segment is 65535: bucket requested 79650
E @ 31dcdf25-daac-4a55-bad6-4440c1afd9ae:1
31dcdf25-daac-4a55-bad6-4440c1afd9ae:1 Max vertices per segment is 65535: bucket requested 71110
E @ 31dcdf25-daac-4a55-bad6-4440c1afd9ae:1
31dcdf25-daac-4a55-bad6-4440c1afd9ae:1 Geometry exceeds allowed extent, reduce your vector tile buffer size

Perhaps this is the issue for the other islands

**Comment by toshelp** [comment]
I tried the latest #236 (https://github.com/kleunen/tilemaker/commit/57da2775299ab60a72e0fbb6644451d2643a261e) but it didn't resolved.
It's strange... :confused:

**Comment by toshelp** [comment]
I have no clear rationale, but I think this issue is similar to #181, #191.

**Comment by kleunen** [comment]
Yes, that is possible. The max vertices is also an issue. I think @systemed can better comment on this. 

I think the floor instead of round is better. But maybe in some other cases it causes other issues ? 

The default for C++ is truncating and not flooring, so before the initial commit, this was the behaviour.

**Comment by systemed** [comment]
I remember that island (Scarp) was up for sale a few years ago!

I wonder if the best way to debug this will be to take the vector tile, convert it to GeoJSON (https://github.com/mapbox/vt2geojson), and then examine the result (perhaps in QGIS or similar). That will at least show us what the problem geometry actually is.

It might be, for example, that the small islands (to the north of Scarp) are being simplified into something that then overlaps with Scarp, causing an invalid self-intersecting geometry.

Ultimately a lot of these problems would be fixed if the `dissolve` extension was brought into boost::geometry, but that hasn't happened and it doesn't look like something trivial to implement.

**Comment by kleunen** [comment]
dissolve combines nearby polygons ?

**Comment by systemed** [comment]
It fixes self-intersections in polygons. Here's an explanation: https://barendgehrels.blogspot.com/2011/02/dissolving-pentagram.html

And here's the extension code (but it probably doesn't compile) with some comments: https://github.com/boostorg/geometry/blob/develop/include/boost/geometry/extensions/algorithms/dissolve.hpp#L535

You can _sometimes_ simulate this by buffering with a small margin (to 'inflate' the shape), then unbuffering with the -ve of that margin (to return it to its previous size). I don't know whether that'd work in the case of boost::geometry though.

**Comment by kleunen** [comment]
Yes, i think you linked it before for me, but I could not find it. 

The dissolve extention had a recent commit:
Latest commit 6b74f7c on 18 Sep 2020

Some maybe it does compile, is worth a try.

**Comment by kleunen** [comment]
Another possibility is to use a simplification algorithm that does not generate self-intersections:
[Polygon Simplification](https://www.dca.fee.unicamp.br/projects/prosim/publications/congress/wu-roci-2003-rfm.pdf)

**Comment by kleunen** [comment]
I think the self-intersection occurs after converting the coordinates to integers (scaled coordinates). Because tilemaker first performs simplification, then checks if the simplified polygon is valid. If it is not, it takes the original polygon. Which in almost all cases is valid polygon. 

The problem however is that converting to scaled coordinates, might introduce a self-intersecting polygon. Due to rounding errors, this may occur. 

So ideally the approach is as follows: 
1. Convert the polygon to a scaled polygon (or linestring), coordinates are integers. 
2. Perform a simplification to get a set of coordinates which does not have self-intersection (make simplification self-intersection aware). 
3. Write the coordinates

Step 1 may actually introduce self-intersection which can not be removed by the simplification. But the simplification may actually be able to correct this. If you perform the simplification with a distance of 0 (so no simplification), and just try to find a minimal polygon which does not have self-intersection.

**Comment by kleunen** [comment]
@toshelp Can you try #236 again ?

**Comment by toshelp** [comment]
I tried #236(https://github.com/kleunen/tilemaker/commit/3a1d126a226721e19f248883c1b233ac16632ec9) again, but didn't resolved.
I think it's a really hard problem.

**Comment by kleunen** [comment]
[Simplify without intersection](https://www.jasondavies.com/simplify/)

**Comment by kleunen** [comment]
Yes, tippecanoe is using wagyu library:
[wagyu quick clip](https://github.com/mapbox/tippecanoe/blob/master/mapbox/geometry/wagyu/quick_clip.hpp)

I implemented a non self-intersecting simplifier #239. So it seems these issues are not caused by the simplifier, actually, i think my simplifier makes it worse on the scotland extract.  

Also actually, maybe the clipper of boost geometry is not incorrect. It is just the fact that if these coordinates are very close to each other, they might introduce self-interesection due to the rounding of the double. This may always occur. Libraries such as [CGAL](https://www.cgal.org/) use arbiterary precision to prevent these issues. But this is very computational expensive. 

Tilemaker also does first clipping and then simplifying. In theory it makes more sense to do this the other way around: first simplify and then clip. I think other renderers actually do it this way. 

It is a difficult issue like you said :D

**Comment by kleunen** [comment]
I made a small extract of the tiree island, and when I run the validate after the clipping (without simplification), on the multipolygon, and on the outer and inners of the different polygons, i get: 

Output multipolygon has the wrong orientation
Outer polygon has something mysterious wrong with it, Boost validity_failure_type 0

something mysterious wrong? what is that :D

**Comment by systemed** [comment]
Ha! Type 0 should mean that it's actually valid: https://www.boost.org/doc/libs/1_63_0/libs/geometry/doc/html/geometry/reference/enumerations/validity_failure_type.html

**Comment by kleunen** [comment]
Yes, this is the polygon that is valid: 
Outer polygon has something mysterious wrong with it, Boost validity_failure_type 0
-6.76819 68.8278
-6.76812 68.8277
-6.76802 68.8275
-6.76795 68.8274
-6.76792 68.8273
-6.76796 68.8271
-6.76803 68.827
-6.76811 68.827
-6.76819 68.8269
-6.76819 68.8278

Seems alright to me

![image](https://user-images.githubusercontent.com/230050/117679593-b4c37180-b1b0-11eb-9bac-5cde157b541e.png)

**Comment by kleunen** [comment]
oh wait, i am doing something wrong here

**Comment by kleunen** [comment]
Ah yes, this is one of those collapsed polygons: 
![image](https://user-images.githubusercontent.com/230050/117681434-63b47d00-b1b2-11eb-9fd7-9806a0c72459.png)

**Comment by kleunen** [comment]
@toshelp Can you try PR #239 ? For me, the output is better, still not perfect.

**Comment by kleunen** [comment]
@toshelp Please try #239

**Comment by toshelp** [comment]
I'm tried #239, and looks nice view!
It may not be perfect as you say, but it's a better solution.

**Comment by kleunen** [comment]
excellent, good news.

**Comment by kleunen** [comment]
@systemd You converted the vector tiles to geojson, but would it be useful for maptiler to generate geojson directly ? Can geojson also be stored in the mbtiles file ? And how can they be rendered ? 

I think geojson does not have this rounding of coordinates, right ?

**Comment by toshelp** [comment]
Thank you for #239, I'm very happy!
I'll close this :)
