### ISSUE TITLE
Multi-core optimization

### ISSUE THREAD

**Issue by buddhistSystem** [systemed/tilemaker#238]
I have an 18G oms.pbf file.
When I execute the following command using docker.
```
docker run -v /tmp:/app osmtw/tilemaker \
    --output /app/highways.mbtiles \
    --input /app/highways.osm.pbf \
    --config resources/config-openmaptiles.json \
    --process resources/process-openmaptiles.lua
    --combine
```
cpu uses only one core, and the execution process is very slow.
![image](https://user-images.githubusercontent.com/38576008/117412893-e554a280-af47-11eb-917b-2a940c127c50.png)

can you optimize the use of multi-core.

**Comment by systemed** [comment]
Is that single-core throughout the process?

.pbf reading (the first half of the run) is single-threaded but tile generation (the second half) should be multi-threaded.

**Comment by buddhistSystem** [comment]
![image](https://user-images.githubusercontent.com/38576008/117416432-f3a4bd80-af4b-11eb-8171-a734c981c5fb.png)
![image](https://user-images.githubusercontent.com/38576008/117416508-07502400-af4c-11eb-90af-437ab49f2774.png)
The docker container has been running for an hour,I am not sure if he has finished reading

**Comment by kleunen** [comment]
It is still reading, at a certain moment you will see how many shapes are loaded: 
Stored 9639463 nodes, 1192436 ways, 7462 relations
Shape points: 0, lines: 0, polygons: 19
Generated points: 628203, lines: 365421, polygons: 977403

From this point on, it is multi-core. But an 18G file will take a long time to load.

**Comment by kleunen** [comment]
You can use one of the prebuilt executables from CI: 
https://github.com/systemed/tilemaker/suites/2667959237/artifacts/58763551

And I would recommend using the store to reduce memory:
./tilemaker --store osm_store.dat
    --output /app/highways.mbtiles \
    --input /app/highways.osm.pbf \
    --config resources/config-openmaptiles.json \
    --process resources/process-openmaptiles.lua

You have 64G memory available, but maybe add an additional 64G of swap. Because even with the store, it takes a lot of memory.

**Comment by buddhistSystem** [comment]
Thanks for your answer

**Comment by buddhistSystem** [comment]
I really have 64G memory on this computer, not swap

**Comment by kleunen** [comment]
Yes, i understand. But actually 64G may not be enough to process 18G osm.pbf! So maybe add an additional 64G. It depends on how many layers you have enabled.

**Comment by buddhistSystem** [comment]
I use I use  prebuilt executables execute this command.
```
./tilemaker --store osm_store.dat
--output /app/highways.mbtiles
--input /app/highways.osm.pbf
--config resources/config-openmaptiles.json
--process resources/process-openmaptiles.lua
```
Fifteen hours passed.
![image](https://user-images.githubusercontent.com/38576008/117519719-4d05fe80-afd7-11eb-980a-249633eb625a.png)
![image](https://user-images.githubusercontent.com/38576008/117519741-69a23680-afd7-11eb-8889-0ddbf3def47b.png)
May I know if that's normal?

**Comment by kleunen** [comment]
Yes. That is normal.

**Comment by kleunen** [comment]
You are nearing the point where it starts generating. This also will take hours

**Comment by kleunen** [comment]
But it would be a good idea to at least include the water polygons:

From the main page:
_If you want to include sea tiles, then create a directory called coastline in the same place you're running tilemaker from, and then save the files from https://osmdata.openstreetmap.de/download/water-polygons-split-4326.zip in it, such that tilemaker can find a file at coastline/water_polygons.shp._

Because otherwise the map looks quite odd, without seas and oceans.

**Comment by buddhistSystem** [comment]
highways.osm.pbf is worldwide highway vector data.
I downloaded the full amount of data from OpenStreetMap and use osmium-too to split the higways data.

https://github.com/osmcode/osmium-tool

May not need ocean data.

**Comment by kleunen** [comment]
ok, just have a look. Usually it is better to start testing at country level to see if everything is OK.

**Comment by buddhistSystem** [comment]
You are right, 64G memory is not enough to process 18G osm.pbf!
So I increased the memory to 128G and split osm.pbf by continent.
Successfully made mbtiles.
Slice generation is multi-threaded.
![image](https://user-images.githubusercontent.com/38576008/117766679-869e6a00-b262-11eb-8366-7a2767e35b2d.png)

**Comment by kleunen** [comment]
Excellent

**Comment by kleunen** [comment]
@systemed Maybe it is good to open the discussion section on tilemaker github, it is possible to have a discussion area on the project. Discussion like this is good to keep for reference.
