### ISSUE TITLE
Weird behavior with "coastlines" shp file

### ISSUE THREAD

**Issue by QuentinC** [systemed/tilemaker#240]
Hello,

I've been trying to use tilemaker with the "coastlines-split" from here: [coastlines-split-4326.zip](https://osmdata.openstreetmap.de/download/coastlines-split-4326.zip)

As this seems related to https://github.com/systemed/tilemaker/pull/239 I've also tried with this branch, but with the same result.
I am not using simplification for now.

The result is not the expected one, some lines are missing, and some other are running straight through the land...

Level 6:
![6](https://user-images.githubusercontent.com/3394508/118885521-2cec0e80-b8f8-11eb-82c5-8aa2a9003991.jpg)
Level 7:
![7](https://user-images.githubusercontent.com/3394508/118885523-2d84a500-b8f8-11eb-97d7-672494ce2d85.jpg)
Level 8:
![8](https://user-images.githubusercontent.com/3394508/118885524-2d84a500-b8f8-11eb-94cc-88baeefc53da.jpg)
Level 9 seems fine:
![9](https://user-images.githubusercontent.com/3394508/118885525-2e1d3b80-b8f8-11eb-89d2-9da8f5f454f7.jpg)

Here is my basic config file:
```
{
	"layers": {
		"coastline":	     { "minzoom":  0, "maxzoom": 14},
		"coastline_hig":     { "minzoom":  6, "maxzoom": 14,"source": "data/res/coastlines.shp",  "source_columns": ["featurecla"], "write_to": "coastline" }
	},
	"settings": {
		"minzoom": 0,
		"maxzoom": 10,
		"basezoom": 10,
		"include_ids": false,
		"bounding_box": [-5, 46, 1, 50],
		"default_view": [-2.6, 48, 7],
		"combine_below": 14,
		"name": "Tilemaker to OpenMapTiles schema",
		"version": "3.0",
		"description": "Tile config based on OpenMapTiles schema",
		"compress": "gzip",
		"filemetadata": {
			"tilejson": "2.0.0", 
			"scheme": "xyz", 
			"type": "baselayer", 
			"format": "pbf"
		}
	}
}
```

Here is the resulting mbtiles file: [out.zip](https://github.com/systemed/tilemaker/files/6511619/out.zip)

I am doing anything wrong ?

Thanks !

**Comment by kleunen** [comment]
Most likely this is in the input, can you open the shapefile in qgit ?

**Comment by QuentinC** [comment]
I dont have any issue with this shape file in QGIS:

Level 0:
![0](https://user-images.githubusercontent.com/3394508/119185588-29cb5c80-ba77-11eb-958e-e117a21f3fbe.png)
Level 1:
![1](https://user-images.githubusercontent.com/3394508/119185591-2afc8980-ba77-11eb-8b5d-3cade0192246.png)
Level 2:
![2](https://user-images.githubusercontent.com/3394508/119185593-2b952000-ba77-11eb-9178-c17ae07fa08c.png)
Level 3:
![3](https://user-images.githubusercontent.com/3394508/119185596-2b952000-ba77-11eb-8646-a8ca1877aea3.png)

**Comment by kleunen** [comment]
I will have a look. I don't think it is misconfiguration

**Comment by kleunen** [comment]
You are only using the shapes file ? So no osm.pbf file ? Or using france pbf from geofabrik ?

**Comment by QuentinC** [comment]
At first I were using France PBF, and I've seen the issue.
I've made these tests for the GitHub issue without any PBF, keeping only the shape file.

I am running tilemaker using the docker image (build from this repo), with the only options being config and process files, with mbtiles output.

**Comment by kleunen** [comment]
Ah yes, i am able to convert and see the same result. But i have no clue where this might be coming from, to be honest.

**Comment by systemed** [comment]
Out of interest, does the same happen if you use `"basezoom": 14`?

**Comment by QuentinC** [comment]
@systemed Yes it's the same with `"basezoom": 14`.
I'm running with `"basezoom": 12` to increase generation speed !

**Comment by toshelp** [comment]
Can you try removing the "combine_below" setting?

```
		"default_view": [-2.6, 48, 7],
-		"combine_below": 14,
		"name": "Tilemaker to OpenMapTiles schema",
```

**Comment by QuentinC** [comment]
Hello,

It seems to work without issue with this modification !

Here is the generated mbtiles:
[testshp.zip](https://github.com/systemed/tilemaker/files/6532398/testshp.zip)
