### ISSUE TITLE
Missing railway station roof in Portsmouth

### ISSUE THREAD

**Issue by aguahombre** [systemed/tilemaker#241]
I noticed that the railway station roof at the Gosport ferry station in Portsmouth UK is shown as ocean.
Shown below using the tilemaker server.

![image](https://user-images.githubusercontent.com/17591364/119142885-e228de80-ba3e-11eb-865f-f5c889a15dcf.png)

On OSM the roof is shown correctly.

The source tiles were generated from an extract of the europe-latest.osm.pbf 04 May 2021
osmium extract --bbox=-1.35,50.69,-1.02,50.86 --set-bounds --strategy=smart europe-latest.osm.pbf  --output solent.osm.pbf.
Using tilemaker with the default process-openmaptiles.lua and config-openmaptiles.json files.

I'm not sure how to find whether the problem is in the original OSM data or missing instructions in the lua file.
Any suggestions?

**Comment by systemed** [comment]
I think this is because Portsmouth Harbour station is on a [pier](https://www.openstreetmap.org/way/192089899) and the Lua script doesn't currently write out piers. It should be a fairly easy fix - on finding an object with `man_made=pier`, write it to the `transportation` layer with `way:Attribute("class","pier")`.

**Comment by aguahombre** [comment]
That makes sense, as I noticed that the jetties in Gunwharf marina, for example, are not shown either.
Is this something you will fix in the default lua file in github?

**Comment by aguahombre** [comment]
I found I had to move layers ```road_area_pier``` and ```road_pier``` before ```building``` in the style.json otherwise the buildings were hidden by the pier.

**Comment by systemed** [comment]
I've added pier support in https://github.com/systemed/tilemaker/commit/82dee926e20b7021c49c45fba41da698b0a86925 - thanks for spotting!

In terms of the style.json, generally I think it's best to avoid diverging from the OMT original: if it's a problem with the style (and it seems to be) then best to report it over on their repo and we can take an update from there in due course.
