### ISSUE TITLE
Lost polygon after #239

### ISSUE THREAD

**Issue by QuentinC** [systemed/tilemaker#242]
Hello,

During my tests on this software, I have seen a lost polygon. 
It displays fine before #239 but disappears after...
This is the lost polygon: https://www.openstreetmap.org/relation/2980911 

Well it might be more complicated, here are some screenshots taken before #239 :
Zoom 12:
![1](https://user-images.githubusercontent.com/3394508/119241260-666d8580-bb55-11eb-9b6e-c2451d39ddbe.jpg)
Zoom 13:
![2](https://user-images.githubusercontent.com/3394508/119241265-6cfbfd00-bb55-11eb-8e65-5e91fc44c8b4.jpg)
And Zoom 14:
![14](https://user-images.githubusercontent.com/3394508/119241269-738a7480-bb55-11eb-939f-057b78d65796.jpg)

As you can see some parts of the polygon are lost depending of the zoom level, and the whole polygon disappear when using latest commit... 
I have dont my tests using the France>Bretagne export from there: https://download.geofabrik.de/europe/france/bretagne-latest.osm.pbf with a custom process.lua that includes military landuse:
[process-openmaptiles.lua.txt](https://github.com/systemed/tilemaker/files/6527194/process-openmaptiles.lua.txt) (L496)

Thanks again for the support !

**Comment by toshelp** [comment]
```is_valid``` checks geometry in the sense of OCG. I think this is the result of that check.
https://www.boost.org/doc/libs/1_76_0/libs/geometry/doc/html/geometry/reference/algorithms/is_valid/is_valid_2_with_failure_value.html

I found a workaround to uncheck ```failure_self_intersections```. But, it may cause other problems.
```
diff --git a/include/osm_lua_processing.h b/include/osm_lua_processing.h
index 5911f66..8c1cfa9 100644
--- a/include/osm_lua_processing.h
+++ b/include/osm_lua_processing.h
@@ -125,7 +125,7 @@ public:
         } else if (isWay && !geom::is_valid(geom,failure)) {
             if (verbose) std::cout << "Way " << originalOsmID << " has " << boost_validity_error(failure) << std::endl;
         }
-        if (failure==boost::geometry::failure_self_intersections || failure == boost::geometry::failure_few_points) 
+        if (failure == boost::geometry::failure_few_points) 
                        return false;
                if (failure==boost::geometry::failure_spikes)
                        geom::remove_spikes(geom);

```

**Comment by kleunen** [comment]
Indeed what toshelp is saying, i changed the behaviour of the is_valid check to not process self_intersecting polygons. On my map i had an issue that a tile was rendered incorrectly because of a self-intersecting polygon. 
I am not sure if the OSM data really has this many self-intersecting polygons, or boost is too picky. Because boost also seems to reject polygons which appear to be valid.

**Comment by kleunen** [comment]
Try also run with --verbose, to see if the polygon is mentioned

**Comment by kleunen** [comment]
Also on openstreetmap.org itself, you see rendering issues with this polygon:

**Comment by systemed** [comment]
Yes, that's definitely a bad multipolygon - at https://www.openstreetmap.org/relation/2980911#map=19/48.36403/-4.51177 and at https://www.openstreetmap.org/relation/2980911#map=19/48.36266/-4.51813 you can see the outers overlapping each other.

**Comment by kleunen** [comment]
But would a union of these overlapping polygons fix this?

i tried this but it does not seem to fix the polygon.

**Comment by QuentinC** [comment]
> 
> 
> Yes, that's definitely a bad multipolygon - at https://www.openstreetmap.org/relation/2980911#map=19/48.36403/-4.51177 and at https://www.openstreetmap.org/relation/2980911#map=19/48.36266/-4.51813 you can see the outers overlapping each other.

Should I report it to OSM ?

**Comment by toshelp** [comment]
I tried a ```union``` test.
The overlapping areas are merged.
Is there a rounding problem?

test code
```
#include <iostream>
#include <vector>
#include <boost/geometry.hpp>
#include <boost/geometry/geometries/point_xy.hpp>
#include <boost/geometry/geometries/polygon.hpp>
#include <boost/geometry/geometries/box.hpp>
#include <boost/assign/list_of.hpp>

namespace bg = boost::geometry;

typedef bg::model::d2::point_xy<double> point;
typedef bg::model::polygon<point> polygon;
typedef bg::model::box<point> box;

int main()
{
    const box bx(point(5, 0), point(10, 5));

    polygon poly;
    bg::exterior_ring(poly) = boost::assign::list_of<point>
        (0, 0)
        (0, 5)
        (5, 5)
        (5, 0)
        (0, 0)
        ;

    std::vector<polygon> out;
    bg::union_(bx, poly, out);
    
    std::cout << "poly result: " << bg::dsv(out[0]) << std::endl;
}
```

result
```
poly result: (((10, 5), (10, 0), (5, 0), (0, 0), (0, 5), (10, 5)))
```

**Comment by dougkpowers** [comment]
I'm experiencing a problem since #239 as well as many polygons I've been importing from OSM have suddenly dropped.  

For the sake of rendering a map, why do we care if two outer polygons in a multi-polygon overlap?  Instead, can we simply verify that each polygon that makes up the multi-polygon is valid?

**Comment by kleunen** [comment]
Change this: 
https://github.com/kleunen/tilemaker/blob/master/include/osm_lua_processing.h#L128

to return true, and see if this helps. Many polygons are self-intersecting, but it seems also many do not cause any rendering issue. So it is difficult to detect when a polygon will cause rendering issues.

**Comment by kleunen** [comment]
I have this way causing issues: 
https://www.openstreetmap.org/way/261930721#map=19/52.25461/6.20323

If you enable it, the tile looks like this: 
![image](https://user-images.githubusercontent.com/230050/120799596-3ce23000-c53f-11eb-9316-76407fb81f26.png)

**Comment by dougkpowers** [comment]
@kleunen I had already tried your suggestion and it did work.  I found that the multipolygon was "self-intersecting" because two polygons touched each other (but they didn't overlap).  That seems very legitimate.

This seems to be behaving like an experimental feature.  Perhaps there could be a command line flag to enable/disable it.

**Comment by kleunen** [comment]
Well, actually. Many polygons contain some self-intersection, also due to the clipping and coordinate conversion that is happening. You can see that if you run with --verbose. But many times, this is not actually an issue. Mapbox can handle some level of self-intersection on the polygons. 

I was thinking of maybe to restore the original behaviour. And add a possibility to the config file to block certain geometries. So if certain geometries cause issues on the map, you can blacklist them from inside the config file.

**Comment by systemed** [comment]
> I have this way causing issues:
> https://www.openstreetmap.org/way/261930721#map=19/52.25461/6.20323

I was able to fix this particular case with:

    Polygon fixed;
    geom::convex_hull(mp, fixed);
    geom::assign(mp, fixed);

which seems to act as a quick-and-dirty 'dissolve'. Ideally we should run this on each individual ring of a multipolygon, I guess.

**Comment by kleunen** [comment]
I tried also the buffer approach here: 
https://wandbox.org/permlink/iUbX79o2m3yeNQWe

From this: 
![image](https://user-images.githubusercontent.com/230050/120842761-6c0f9600-c56d-11eb-82e8-620b67fa0188.png)

it generates this:
![image](https://user-images.githubusercontent.com/230050/120842777-7336a400-c56d-11eb-91b7-402db8ab15c1.png)

**Comment by kleunen** [comment]
The convex hull gets generated like this:
![image](https://user-images.githubusercontent.com/230050/120843086-f952ea80-c56d-11eb-92c6-5573e646a58e.png)

**Comment by kleunen** [comment]
This is when i first do a buffer with distance 0.000003, and then a buffer with distance -0.000003
![image](https://user-images.githubusercontent.com/230050/120843572-8f871080-c56e-11eb-9a5b-e301071caba0.png)

**Comment by kleunen** [comment]
And with distance 0.00001 and -0.00001:
![image](https://user-images.githubusercontent.com/230050/120843892-ef7db700-c56e-11eb-8469-3e678a7fa504.png)

it is a valid polygon after this

**Comment by kleunen** [comment]
Maybe we should try this buffer approach on: 
https://www.openstreetmap.org/relation/2980911
