### ISSUE TITLE
Intermittent Segmentation Faults since #239

### ISSUE THREAD

**Issue by dougkpowers** [systemed/tilemaker#244]
I'm getting some intermittent seg faults since #239.  It has not been consistent so I'm struggling to pin it down.

Mac OS
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00007fe7bbb00000
Exception Note:        EXC_CORPSE_NOTIFY

Top of Thread #0: 0   libsystem_kernel.dylib              0x00007fff20669a5e __ulock_wait + 10

Top of Thread #1: 0   libsystem_malloc.dylib              0x00007fff204c618d small_malloc_from_free_list + 344
.... WriteGeometryVisitor::operator()(boost::geometry::model::multi_polygon<boost::geometry::model::polygon<boost::geometry::model::d2::point_xy<double, boo
st::geometry::cs::cartesian>, true, true, std::__1::vector

Top of Thread #2: 0 bool boost::geometry::detail::get_turns::get_turns_in_sections

Just putting this out there to see if anyone else is experiencing this.

**Comment by kleunen** [comment]
Yes i did see the same on windows. There it crashed consistently. In the parallel loading pr there is actually a patch that might resolve this.

**Comment by kleunen** [comment]
I can backport to the main and you can try.

**Comment by kleunen** [comment]
Try this: 
https://github.com/systemed/tilemaker/pull/245

**Comment by dougkpowers** [comment]
haven't received a segfault since pulling latest.
