### ISSUE TITLE
Dissolve alternatives

### ISSUE THREAD

**Issue by systemed** [systemed/tilemaker#246]
This is an all-purpose issue to note potential solutions for 'dissolving' self-intersecting polygons.

### Convex hull

    Polygon fixed;
    geom::convex_hull(mp, fixed);
    geom::assign(mp, fixed);

Simple, but loses precision. Ideally run this once per ring.

### Buffer

	MultiPolygon buffered;
	geom::strategy::buffer::distance_symmetric<double> distance_strategy(0.000001);
	geom::strategy::buffer::join_round join_strategy(16);
	geom::strategy::buffer::end_round end_strategy(16);
	geom::strategy::buffer::point_circle circle_strategy(16);
	geom::strategy::buffer::side_straight side_strategy;
	geom::buffer(mp, buffered,
	    distance_strategy, side_strategy,
	    join_strategy, end_strategy, circle_strategy);
	geom::assign(mp,buffered);

Can potentially then run again with a negative buffer to return to (a valid version of) the original shape.

### Boost.Geometry dissolve

Extension code at https://github.com/boostorg/geometry/blob/develop/include/boost/geometry/extensions/algorithms/dissolve.hpp . Not actively maintained. Given that users can compile tilemaker with several Boost versions, this would be difficult to include, but some of the concepts might be interesting. (Note also Artem's 2016 patch at https://github.com/artemp/dissolve/blob/master/boost-geometry-dissolve.patch .)

### Custom algorithm to remove self-intersections

Take this geometry:

![self_intersection](https://user-images.githubusercontent.com/694425/120844314-1a640d00-c567-11eb-8761-6f89a49805b0.png)

If Pa->Pa+1 intersects Pb->Pb+1 (where a<b), then replace Pa...Pb+1 with Pa->(intersection of lines)->Pb+1.

So in this example, replace P2...P5 with P2->intersection->P5.

It'd need some careful work for the case where Pa...Pb+1 includes P1 (i.e. the points wrap round).

### Break multipolygons into constituent polygons

In Boost.Geometry, a Polygon is an outer with n inners, and a MultiPolygon is n Polygons.

So if we have a MultiPolygon where the constituent Polygons overlap, and this causes a problem for Boost.Geometry, we could theoretically break it out into several objects, one for each Polygon.

### See also

#242, #239, #181, https://github.com/boostorg/geometry/pull/460 for comments on `simplify`, https://github.com/boostorg/geometry/issues/447 for a `dissolve` status ticket, https://barendgehrels.blogspot.com/2011/02/dissolving-pentagram.html.

**Comment by kleunen** [comment]
You can also make the simplifier detect intersections. So if you have this polygon:
![image](https://user-images.githubusercontent.com/230050/120845749-82b7ec00-c571-11eb-8fcb-54112d13b911.png)

You add point P at the intersection of P2-P4 and P3-P5, and "simplify" the polygon by going from P2 -P - P4 and remove P3 and P4. The simplifier actually already has the rtree for detecting these intersections. Because when adding a new line, it detects if this might cause an intersection, using the rtree.

**Comment by kleunen** [comment]
The simplifier can also remove spikes. If you have three points P1 - Pspike - P2, and P1 and P2 are actually within a small margin of each other, you can go from P1 to P2 and remove the spike.

**Comment by kleunen** [comment]
This is the buffer and unbuffer approach:

````C++
    const double buffer_distance = 0.00001;
    const int points_per_circle = 3;
    boost::geometry::strategy::buffer::distance_symmetric<double> distance_strategy(buffer_distance);
    boost::geometry::strategy::buffer::distance_symmetric<double> inverse_distance_strategy(-buffer_distance);
    boost::geometry::strategy::buffer::join_miter join_strategy;
    boost::geometry::strategy::buffer::end_flat end_strategy;
    boost::geometry::strategy::buffer::point_circle circle_strategy(points_per_circle);
    boost::geometry::strategy::buffer::side_straight side_strategy;
    
     // Create the buffer of a multi polygon
    boost::geometry::model::multi_polygon<polygon> result;
   
    boost::geometry::buffer(poly, result,
                distance_strategy, side_strategy,
                join_strategy, end_strategy, circle_strategy);
    boost::geometry::assign(poly, result[0]);
    boost::geometry::buffer(poly, result,
                inverse_distance_strategy, side_strategy,
                join_strategy, end_strategy, circle_strategy);
    boost::geometry::assign(poly, result[0]);

**Comment by kleunen** [comment]
This intersection calculation approach may not always give good results:

In this case: 
![image](https://user-images.githubusercontent.com/230050/120849534-87cb6a00-c576-11eb-9b26-c78ec311ee14.png)

You might go from P1 -> P2 -> intersection -> P1, and cut off part of the polygon. 
I don't think in practice you will see this case very often. But I guess the buffer approach might be better.

**Comment by kleunen** [comment]
https://www.sciencedirect.com/science/article/abs/pii/S0304397520304199

**Comment by systemed** [comment]
Some code for fixing self-intersections:

https://github.com/YaaZ/decomposition-library
https://github.com/mclaeysb/simplepolygon/blob/master/index.js
https://web.archive.org/web/20100805164131/http://www.cis.southalabama.edu/~hain/general/Theses/Subramaniam_thesis.pdf

**Comment by kleunen** [comment]
https://web.archive.org/web/20100805164131/http://www.cis.southalabama.edu/~hain/general/Theses/Subramaniam_thesis.pdf

This seems quite a straightforward and easy approach

**Comment by kleunen** [comment]
> So if we have a MultiPolygon where the constituent Polygons overlap, and this causes a problem for Boost.Geometry, we could theoretically break it out into several objects, one for each Polygon.

Regarding this, you can rebuild a new multipolygon and keep adding the polygons to the new multipolygon using:
https://github.com/kleunen/tilemaker/blob/master/include/geom.h#L55-L78

This way, when two polygons inside the multi polygon overlap or touch, they a combined into a single polygon. 

This happens now also inside the simplifier:
https://github.com/kleunen/tilemaker/blob/master/src/geom.cpp#L138-L144

And reduces the number of vertices

**Comment by kleunen** [comment]
Have a try at my implementation of dissolve:
https://wandbox.org/permlink/H6pm8NlvvfXCFNof

**Comment by systemed** [comment]
Wow - looks good!

**Comment by kleunen** [comment]
Yes. I think i will make a small single header library out of it. And also describe the approach. Because it is simpler then any of the other approaches that exist.

**Comment by systemed** [comment]
Using the pentagram example from Barend Gehrels' blog, this calculates the area correctly: https://wandbox.org/permlink/EH9AjkNT7hn6Jqlr

**Comment by kleunen** [comment]
The second case he mentions:
POLYGON((55 10, 141 237, 249 23, 21 171, 252 169, 24 89, 266 73, 55 10))

![image](https://user-images.githubusercontent.com/230050/121186119-0837e680-c867-11eb-9ce8-5f33ffe184ca.png)

Is not generated correctly (yet) using my code.

**Comment by kleunen** [comment]
Or maybe it is, at least, it takes the first union polygon and not the biggest, so.. Not sure what my code will generate from this.

**Comment by kleunen** [comment]
No it is actually correct, it generated two polygons:
![image](https://user-images.githubusercontent.com/230050/121187116-03276700-c868-11eb-9668-abf7e5df9162.png)

impressive

**Comment by kleunen** [comment]
But the blue polygon, should it be generated or not. Because the winding is reserve, but I would say, just generate the biggest polygon. Everything should be inside, because this ring is the outer and not one of the inners.

**Comment by kleunen** [comment]
https://github.com/kleunen/boost_geometry_dissolve

**Comment by kleunen** [comment]
I made several improvements to my dissolve: 
https://github.com/kleunen/boost_geometry_dissolve

It is working very well now, multiple intersections work, collinear segments. I have a test which generates 100.000 random polygons, they all are converted to simple/valid polygons.

**Comment by systemed** [comment]
Superb! We should look at integrating it to fix #242 and similar.

**Comment by kleunen** [comment]
yeah, would be very cool if it got integrated into boost geometry. But also the non self-intersecting simplify, maybe i will also extract this and make it available. I think more projects can benefit from this.

**Comment by kleunen** [comment]
Have a try #249
