### ISSUE TITLE
Suggestion: adaptive simplify level

### ISSUE THREAD

**Issue by tinoue** [systemed/tilemaker#25]
> ```
> "low_roads": { "minzoom": 9, "maxzoom": 11, "write_to": "roads", "simplify_below": 12, "simplify_level": 0.0001 }
> ```

In my understanding, the above configuration applies the same simplfy_level 0.0001 to each zoom level below 12.
Though it would be helpful to apply simplfy level 0.0002 to zoom level 11, 0.0004 to zoom level 10 and so on.

**Comment by systemed** [comment]
Agreed, that's a good idea.
