### ISSUE TITLE
mbtiles not produced with tilemaker are invisible

### ISSUE THREAD

**Issue by RyanDeRose-TomTom** [systemed/tilemaker#254]
I've been creating osm files with just road networks. Converting these to mbtiles with tilemaker and rendering works. However, I desperately need some background features like satellite imagery or land cover to contextualize the roads. I tried loading the following with server.rb:

http://osmlab.github.io/osm-qa-tiles/country.html <-- Luxembourg
https://data.maptiler.com/downloads/tileset/satellite-lowres/

and was surprised to find that both appear blank. Is there some incompatibility with mbtiles versions? Beyond this rendering issue, does anyone have recommendations for including land use polygons and/or city name labels with the roads I am generating early enough in the process so that I can put single osm.pbf files through tilemaker?

**Comment by systemed** [comment]
For the example server, you'll need a Mapbox/Maplibre GL style as well as the .mbtiles file. The mbtiles is a container for vector tiles, but vector tiles don't contain any styling information, just processed geodata in layers.

The style which is included with the example server is [this one](https://github.com/systemed/tilemaker/blob/master/server/static/style.json), and if you look at the JSON (in particular the `source-layer` items) you can see what it expects to find in your vector tiles. You can edit a style file either as raw JSON, or using a WYSIWYG editor like [Maputnik](https://maputnik.github.io), or with a preprocessor like [Glug](https://github.com/systemed/glug).

For landuse polygons, you could either pull data out of OSM (though coverage can be partial) or use a third-party source - CORINE, LUCA etc. are useful at small scales if you don't mind a bit of GIS wrangling! Again, after you've got them into the vector tiles, you'll need to modify your style to show them.
