### ISSUE TITLE
Labels for Lake and Rivers

### ISSUE THREAD

**Issue by tgdbepe4** [systemed/tilemaker#257]
Any idea how I can make the names of lakes and rivers visible. The information is present in openstreepmap.org:

![image](https://user-images.githubusercontent.com/46052442/122926602-54efe700-d368-11eb-989a-7d92e6025180.png)

Chhers, Peter

**Comment by systemed** [comment]
Tilemaker's standard OpenMapTiles schema does write names for rivers and lakes:

![Screenshot 2021-06-24 at 12 40 38](https://user-images.githubusercontent.com/694425/123257033-8d6afe80-d4e9-11eb-84a3-81e2dfef72c7.png)

![Screenshot 2021-06-24 at 12 41 01](https://user-images.githubusercontent.com/694425/123257045-90fe8580-d4e9-11eb-8160-f86fb4decfb7.png)

Could you share which zoom level, and where, you're not seeing lake/river names? (I presume this is with the standard OMT schema?)

**Comment by tgdbepe4** [comment]
Hi

The good news first. Yes, it is there when I use the the ruby server.rb. I use tileserver-php for serving the tiles. Over the URL of the tileserver-php I can't find no water_name object in Maputnik. Independent of the zoom level. Any suggestion for an other tileserver?

Cheers

Peter

**Comment by tgdbepe4** [comment]
Hi

Thanks this hint helped. I use maputnik to style but with the initial zoom level 14 - 14 the node/point was not visible. After changing to "water_name":        { "minzoom": 10, "maxzoom": 14 }, I found the point and was able to style it. In the mean time I altered the lua script adding a shapefile for cliffs and the supporting of the OSM attribute "sac-scale". Now I am quite lucky with it with the axeption that I havent found a way to add hillshade vector like features to the map. See it, https://sacscale.bergi-it-consulting.ch/tilemakersacscale.html. Any idea how find/create a vector tile hillshade and style it?

Many thanks for your great work and the hints!

Kind regards

Peter

**Comment by systemed** [comment]
Hillshading in vector tiles is really hard, I'm afraid!

You can either provide a Digital Elevation Model via raster tiles, or try to create contours and hillshading polygons. These Mapbox docs roughly explain the two approaches: https://docs.mapbox.com/help/troubleshooting/access-elevation-data/

I've done some work on hillshading polygons in the past and it's really tricky to get good results. Essentially the most common technique is to generate a raster hillshading map (e.g. using the gdal suite) and then vectorise it. But if you're developing a map for online use (i.e. not an offline maps app) then you might find it easier just to generate the raster tiles and load them into your map as a background.
