### ISSUE TITLE
Route relations support in Lua profiles

### ISSUE THREAD

**Issue by systemed** [systemed/tilemaker#26]
Something along the lines of Emil Tin's old implementation for OSRM would be good, so that `way_function` can do this:

``` lua
    while true do
        local role, route = routes:Next()
        if route==nil then break end
        local route_type=route.tags:Find("route")
        -- further processing...
    end
```

We could potentially specify the types of relations we're interested in (rather than hard-coding `route` only) in a similar manner to `node_tags`:

```
relation_types = { "route", "waterway" }
```

**Comment by hpgmiskin** [comment]
I think this would be very useful. I am looking to use tilemaker to create a map for cyclists which shows more favourable cycle routes as larger on a map (where most maps currently show roads as larger). Part of this is being able to render cycle routes.

I have noticed on line 517 in [`tilemaker.cpp`](https://github.com/systemed/tilemaker/blob/master/src/tilemaker.cpp#L517) there is a note saying `(just multipolygons for now; we should do routes in time)`.

What would be the best way to approach adding relation capabilities?

**Comment by systemed** [comment]
My half-formed thoughts thus far have been:

- read qualifying relations (as defined in a `relation_types` Lua table, as per above) in an early pass
- with each relation, store the tags and the list of member ways
- then, when we read ways, make the relation memberships available to the Lua profile via an iterator function, as per above

I think that wouldn't be too hard to code and would make it easy to integrate into the Lua processing. But I've not yet had time to work on it.

**Comment by hpgmiskin** [comment]
I have created WIP PR #81 as a start to adding relations to the `way_function` feedback much appreciated

**Comment by systemed** [comment]
This is terrific - thank you. Will try to take a proper look at it next week (remind me if I don't!).

**Comment by MikeKasperlik** [comment]
This looks very promising. Any chance this will be implemented anytime?

**Comment by systemed** [comment]
Done in #360.
