### ISSUE TITLE
Spikes on tile edges 

### ISSUE THREAD

**Issue by kleunen** [systemed/tilemaker#261]
I tried the latest head version now, but I am seeing this spikes now, at lower zoom levels:
![image](https://user-images.githubusercontent.com/230050/124347717-4adeab80-dbe6-11eb-9d24-998f2bc03f65.png)

**Comment by systemed** [comment]
I've seen this very occasionally - I think it might be an artefact of simplification. In theory we have a clippingBox with a small margin beyond the tile edge to prevent problems like this - see https://github.com/systemed/tilemaker/blob/master/src/coordinates.cpp#L80-L85 .

So it could be a result of simplifying the source coastline polygons, which are themselves tiled.

(One possibility to fix this would be to have an option in the simplification algorithm that doesn't simplify pure east-west or north-south lines - i.e. where lat1==lat2 or lon1==lon2.)

**Comment by kleunen** [comment]
Yes, I think it is related to the simplification. When you zoom in/out, you can see it appear and disappear

**Comment by kleunen** [comment]
So there is a straight line in the source data? which gets simplified ? 
But the distance between these two points should be really large right ?

well, you can look at the angle within the node to be simplified. If it is close to 180 degrees, it can be simplified. A 90 degrees angle, should not be simplified.

**Comment by kleunen** [comment]
Hmm, i think it may be this condition:
https://github.com/systemed/tilemaker/blob/master/src/geom.cpp#L48

**Comment by systemed** [comment]
Hmmm, interesting. I thought it would be the source data but in this case it isn't. If you look at the edge of the source polygons it's nowhere near this island:

![Screenshot 2021-07-03 at 09 23 29](https://user-images.githubusercontent.com/694425/124348190-6cd52f80-dbe0-11eb-921b-072b0963382f.png)

So it's to something to do with simplifying the geometries once we've clipped them to tile bounds.

At present we hardcode the tile margin to 1/200th of the tile width, but maybe we should make this configurable per-layer. https://blog.cyclemap.link/2020-01-25-tilebuffer/ has a good explanation of buffers/margins.

**Comment by kleunen** [comment]
Maybe the simplification is not deterministic. So you have the island, clipped into two polygons. On one side different nodes are removed in the simplification process as the part of the island on the other side. The render might not find the same nodes on the different sides of the island ?

**Comment by kleunen** [comment]
I tried changing: 
````
 if(boost::geometry::distance(input[start], input[end]) < 2 * max_distance || distance < max_distance) {
```

to
````
 if(distance < max_distance) {
````

but it makes no difference. I think the simplification should happen before the clipping to the tile edges

**Comment by systemed** [comment]
I was wrong - it is the source data after all:

![Screenshot 2021-07-03 at 10 16 51](https://user-images.githubusercontent.com/694425/124349622-e58bba00-dbe7-11eb-9a78-e6846ab890b9.png)

(I was looking at the EPSG:3857 shapefile previously, but we use the EPSG:4326 one.)

**Comment by kleunen** [comment]
Ah ok. Maybe just not simplify nodes which are on the outer edge of the polygon ? So on min lon, max lon, min lat, max lat.

**Comment by systemed** [comment]
Yes, that would work!

**Comment by kleunen** [comment]
I will give this a try

**Comment by kleunen** [comment]
hmm, i tried, but did not give an improvement. 

I used this in simplification:
````C++
  boost::geometry::model::box<typename GeometryType::value_type> box;
    boost::geometry::envelope(input, box);

    std::priority_queue<std::size_t, std::vector<size_t>> pq;
    for(std::size_t i = 0; i < input.size() - 2; ++i) {
        if( input[i].x() != box.min_corner().x() && input[i].x() != box.max_corner().x() &&
            input[i].y() != box.min_corner().y() && input[i].y() != box.max_corner().y()) {
            pq.push(i);
        }
    }

**Comment by dieterdreist** [comment]
sent from a phone

> On 3 Jul 2021, at 10:15, Richard Fairhurst ***@***.***> wrote:
> 
> So it could be a result of simplifying the source coastline polygons, which are themselves tiled.


could the untiled version of coastline polygons be used instead? I have solved similar issues in rendering by switching from tiled to untiled coastlines.

**Comment by kleunen** [comment]
The water polygons:
https://osmdata.openstreetmap.de/data/water-polygons.html

Do say: 
Where polygons have been split they overlap slightly to help avoiding rendering artefacts at the seams.

So maybe, the buffer in tilemaker should be slightly larger, such that they do not overlap with the buffer of the water polygons ?

**Comment by systemed** [comment]
@kleunen I've tried changing `xmargin = (maxLon -minLon )/200.0` to `/50.0` (and ymargin similarly) in coordinates.cpp, but it doesn't appear to have any effect - I still get some spikes, particularly when zooming in and out at z5.

@dieterdreist Perhaps - I'm generally keen to use small polygons where possible to reduce the amount of processing we have to do, though!

**Comment by kleunen** [comment]
> @kleunen I've tried changing `xmargin = (maxLon -minLon )/200.0` to `/50.0` (and ymargin similarly) in coordinates.cpp, but it doesn't appear to have any effect - I still get some spikes, particularly when zooming in and out at z5.

Strange. Possibily mapbox-gl needs to find multiple overlapping nodes on the polygon, to combine them ? And because of simplification, it can not find them.

**Comment by systemed** [comment]
Thinking about it, changing the margin won't make any difference, because this data is within the tile bounds.

I've just fetched the z5 tile with `vt2geojson` and loaded it into QGIS and you can see the result:

![Screenshot 2021-07-03 at 13 00 01](https://user-images.githubusercontent.com/694425/124353496-c8161a80-dbfe-11eb-80e6-e0e8eb634a3d.png)

(Dark blue is source data, orange is our tile)

I think your idea of not removing nodes which are on the outer edge of the polygon is probably the best.

**Comment by kleunen** [comment]
I tried not removing the node if it is on the edge. But this is not sufficient. Maybe the whole segment with a node on the edge should not be removed

**Comment by pnorman** [comment]
> I tried not removing the node if it is on the edge. But this is not sufficient.

For it to work I think the buffering of the source shapefiles would have to exceed the buffer on the vector tiles.

**Comment by kleunen** [comment]
> > I tried not removing the node if it is on the edge. But this is not sufficient.
> 
> For it to work I think the buffering of the source shapefiles would have to exceed the buffer on the vector tiles.

so i would actually have to reduce the size of the vector tiles buffer? instead of increase. And keep the nodes on the edge.

**Comment by pnorman** [comment]
> so i would actually have to reduce the size of the vector tiles buffer? instead of increase. And keep the nodes on the edge.

That should work. You shouldn't need much buffer on a water layer anyways

**Comment by systemed** [comment]
> I think your idea of not removing nodes which are on the outer edge of the polygon is probably the best.

I tried this and it seems to work. Near the start of the simplify algorithm in geom.cpp, add:

````
double xmin=input[0].x(), xmax=input[0].x(), ymin=input[0].y(), ymax=input[0].y();
for(std::size_t i=0; i<input.size(); i++) {
	xmin=std::min(xmin,input[i].x()); xmax=std::max(xmax,input[i].x());
	ymin=std::min(ymin,input[i].y()); ymax=std::max(ymax,input[i].y());
}
````

then in the while loop, after we've defined start/middle/end:

````
if (input[middle].x()==xmin || input[middle].y()==ymin || input[middle].x()==xmax || input[middle].y()==ymax) {
    continue;
}
````

Result:

![Screenshot 2021-07-03 at 13 55 50](https://user-images.githubusercontent.com/694425/124354916-76718e00-dc06-11eb-9c46-95add186a453.png)

**Comment by pnorman** [comment]
Another way to fix it is to add a point wherever the line crosses the unbuffered tile bounds then simplify while preventing those added points from being removed.

**Comment by kleunen** [comment]
You can use boost geometry envelop to get the min/max. I made mistake in this simplifier, that was why not working

**Comment by systemed** [comment]
#262 should hopefully fix this.

**Comment by kleunen** [comment]
yes, i basicly entered the same code, and it works. I will check the PR also.
