### ISSUE TITLE
Tile merging

### ISSUE THREAD

**Issue by kleunen** [systemed/tilemaker#269]
I performed a planet render by exporting the regions:

````
{ "extracts": [
{
    "output": "planet_1.osm.pbf",
    "description": "Bounding box specified in array format",
    "bbox": [-180,-90,0,0]
},
{
    "output": "planet_2.osm.pbf",
    "description": "Bounding box specified in array format",
    "bbox": [0,-90,180,0]
},
{
    "output": "planet_3.osm.pbf",
    "description": "Bounding box specified in array format",
    "bbox": [0,0,180,90]
},
{
    "output": "planet_4.osm.pbf",
    "description": "Bounding box specified in array format",
    "bbox": [-180,0,0,90]
}
] }
````
After merging however, it seems one column of tiles is not generated/merge:
![image](https://user-images.githubusercontent.com/230050/125447457-1cbdfeee-487b-4838-b132-56a9e591c54b.png)

**Comment by systemed** [comment]
(Yay for the planet!) 

Interesting - so that's at 0 degrees longitude, <0 degrees latitude.

Maybe worth viewing it with the MBGL debug tile grid turned on (`map.showTileBoundaries=true;`) to see which side of the line it is? Might be useful to find out whether it's a tile generation issue or just a merge issue too.

**Comment by kleunen** [comment]
It is in this region: 

````
{
    "output": "planet_2.osm.pbf",
    "description": "Bounding box specified in array format",
    "bbox": [0,-90,180,0]
},
````

**Comment by kleunen** [comment]
There is this check which filters out tiles based on the bounding box: 
https://github.com/systemed/tilemaker/blob/master/src/tilemaker.cpp#L394-L397

**Comment by kleunen** [comment]
I think it may not be related to the tile calculation but to the shape file. The edge of the ocean runs through the different tiles:
![image](https://user-images.githubusercontent.com/230050/125491410-2b33a6bb-bbdc-482f-bff5-b7c5238d64fd.png)

And: 
![image](https://user-images.githubusercontent.com/230050/125491505-793a5de0-4046-4894-af9e-5c448ca58292.png)

**Comment by kleunen** [comment]
![image](https://user-images.githubusercontent.com/230050/125491916-efa650b2-144f-483a-8f66-6970f0c31977.png)

**Comment by systemed** [comment]
The shapefile itself looks ok to me (loading it into QGIS), but it's certainly possible that we're loading it incorrectly - possibly something in `fillPointArrayFromShapefile` (read_shp.cpp)?

**Comment by kleunen** [comment]
I don't know if it is the loading. I was suspecting it was related to the clippingbox, some clipping being performed. But i am not sure. Maybe I should extract small region around this area.

**Comment by systemed** [comment]
Also... we work in projected, spherical Mercator coordinates (aka [EPSG 3857](https://epsg.io/3857), via the `lat2latp` function) which isn't applicable above 85°/below -85° latitude. Maybe possible that projecting -90° to spherical Mercator is causing an overflow somewhere?

**Comment by kleunen** [comment]
But the line follows a longitude, and this longitude is somewhere around 0 to a couple of degrees. The +85, -85 latitude is somewhere in the polar regions right ?

**Comment by kleunen** [comment]
When I generate an extract from africa, it generates fine: 

Bounding boxes:
    (0,-10,10,0)

**Comment by kleunen** [comment]
Nope, even --bbox=0,-90,10,0 is correct. I think it has to do with the merging. I will try

**Comment by kleunen** [comment]
The issue does occur with merging these two extracts: 

````
{ "extracts": [
{
    "output": "africa_1.osm.pbf",
    "description": "Bounding box specified in array format",
    "bbox": [0,-90,10,0]
},
{
    "output": "africa_2.osm.pbf",
    "description": "Bounding box specified in array format",
    "bbox": [-10,-90,0,0]
}
]}
````

**Comment by kleunen** [comment]
And this extract does work ok: 

````
{ "extracts": [
{
    "output": "africa_1.osm.pbf",
    "description": "Bounding box specified in array format",
    "bbox": [0,-85,10,0]
},
{
    "output": "africa_2.osm.pbf",
    "description": "Bounding box specified in array format",
    "bbox": [-10,-85,0,0]
}
]}

**Comment by kleunen** [comment]
#271 fixes this issue
