### ISSUE TITLE
Investigate combine_polygons_below performance

### ISSUE THREAD

**Issue by systemed** [systemed/tilemaker#270]
The `combine_polygons_below` option (implemented in `CheckNextObjectAndMerge` in tile_worker.cpp) leans heavily on Boost.Geometry's `union_` operation.

This can result in a significant slowdown, particularly in cases of complex polygons. Geofabrik report the following approximate times on a Baden-Wurttemberg extract:

- no combining, without buildings layer: 2m15
- no combining, with buildings layer: 3m30
- combine_polygons_below, without buildings layer: 9h30
- combine_polygons_below, with buildings layer: 13h00

So combining non-building polygons takes almost 9hr30 (presumably landuse multipolygons &c.), and combining building polygons takes a further 3h30.

It would be good to speed this up. My first thought is that it might be interesting to try appending the polygons to a single multipolygon, and then unioning that at the end, rather than repeatedly unioning two objects at a time. But that would likely result in a bunch of self-intersections which might cause things to fail.

cc @woodpeck @nakaner

**Comment by kleunen** [comment]
Within geom.h there is actually an in-place union which is used by the simplifier. The simplifier also rebuilds polygons/multi-polygons by performing many unions. I noticed performing this union "in-place", so just adding a polygon to an existing multi-polygon, is much faster using this function: 

https://github.com/systemed/tilemaker/blob/master/include/geom.h#L55-L78

**Comment by kleunen** [comment]
Also correct uses this same method for rebuilding polygons/multi-polygons:
https://github.com/systemed/tilemaker/blob/master/include/geometry/correct.hpp#L25-L47

**Comment by Nakaner** [comment]
@systemed The durations without combining of polygons are in minutes and seconds, not hours and minutes.

**Comment by systemed** [comment]
Haha, brain fade on my part. Of course.

**Comment by Nakaner** [comment]
> @systemed The durations without combining of polygons are in minutes and seconds, not hours and minutes.

But the durations with combining are indeed about half a day (9 hours and 12 hours) for just one large German state.

**Comment by systemed** [comment]
Ah, ok. Right, that does focus minds a little. (Have edited the original issue and I'll hide these comments to prevent confusing the matter.)

**Comment by systemed** [comment]
PR to address this at #383.

**Comment by systemed** [comment]
Fixed in #383.
