### ISSUE TITLE
Including / showing names for landuse layer

### ISSUE THREAD

**Issue by androbey** [systemed/tilemaker#276]
Hi all, 

first of all, thanks for this awesome tool! It's just great. 

I am not sure if my problem can be solved by some tilemaker config or if I have an error in my style. So I am sorry in advance, if I am in the wrong spot here. 
Nevertheless, that's my issue: Some areas tagged with key "landuse" have an additional key "name" (and no "amenity" key). In the best case I want to display the name value just like the name of a town (but in a different color).  Currently I am using the provided openmaptiles config files. 
In my style I tried to display the name value for source layer landuse but had no luck. Can it be that name values for landuse layer is junked or is there a way to include it? Or is it a style related problem?

**Comment by androbey** [comment]
Ok I found that the name is displayed but only at a very high zoom level. For a large area this is not ideal for my usecase, because you have to zoom to the center of the area to get the name displayed.

**Comment by systemed** [comment]
With tilemaker you can control what zoom levels individual features are written out at - use something like `way:MinZoom(5)` in the Lua script. But you'll need to make sure both that the minimum zoom for that layer is specified correctly in the config.json, and that your style renders what you're writing out.
