### ISSUE TITLE
Specify instructions for Windows users in the RUNNING.md file 

### ISSUE THREAD

**Issue by funbuket9** [systemed/tilemaker#281]
Hi,
As you may know, the title says it all. Basically, can you give Windows-specific instructions for us Windows users in the RUNNING.md file. You do realise not all of us uses Linux. And I'm pretty sure that other people who use windows would appreciate it!

**Comment by kleunen** [comment]
For windows, you can use the prebuilt executable for the 2.0.0 release. Please note that on windows, due to a bug, the osm_store directory is not cleaned up. This directory may get very big, this is resolved in pr #267. 

The command line options are the same as on linux
