### ISSUE TITLE
No labels present in MBTiles file

### ISSUE THREAD

**Issue by abhiank** [systemed/tilemaker#285]
Hello, thanks for this very useful tool. 

I'm working on making offline maps available in an Android app using Maplibre. I've got everything setup on the app to show local MBTiles file offline. MBTiles downloaded from maptiler.com are working perfectly. However, MBTiles created using tilemaker are not showing any labels at all. 

I used this .OSM.PBF file from Geofabric downloads - https://download.geofabrik.de/europe/lithuania-latest.osm.pbf

This was the command I executed as found from this blog - https://blog.kleunen.nl/blog/tilemaker-generate-map

`
tilemaker --input latvia-latest.osm.pbf --output latvia.mbtiles --process /resources/process-openmaptiles.lua --config /resources/config-openmaptiles.json 
`

The process worked perfectly and the MBTiles file was generated but on rendering it using Maplibre, no labels for places, shops, etc are being shown. Only highway labels are visible. What am I doing incorrectly over here? Do the Geofabric pbf files not contain names of things?

This is the repo I am using to show the MBTiles file in Maplibre - https://github.com/abhiank/OfflineMapExample

**Comment by kleunen** [comment]
Probably the fonts are missing, or something wrong with the configuration of the directories of the fonts. Have a look in your browser if the is some error in fetching the fonts from your server.

**Comment by abhiank** [comment]
Thanks for your prompt reply.

> fonts are missing

I initially thought so too, but if you take a look at the repo which I linked, its completely setup to work offline so all the fonts (in Glyphs folder) and icons (Sprite folder) are being packaged into the app itself in the assets folder. Labels in MBTiles files from maptiler are showing fine so I think fonts are not the issue. 

I looked into the contents of MBTiles from tilemaker and maptiler and found that many more tables in the maptiler file. I'm not sure what data those tables represent but is it possible that the labels data was not encoded into the tilemaker file?

Tables in Maptiler file - 
<img width="246" alt="tables in maptiler file" src="https://user-images.githubusercontent.com/8065733/130086803-84f3ada6-b1ec-4a47-9526-a49894e47494.png">

Tables in tilemaker file - 
<img width="166" alt="Screen Shot 2021-08-19 at 7 56 50 PM" src="https://user-images.githubusercontent.com/8065733/130086915-2e6e667b-ab8b-4e2f-9c5c-9d9faffd3942.png">

**Comment by kleunen** [comment]
So the issue is only on Android ? I have no experience with android maplibre TBH. 
Have you tried rendering from an online map first, before trying an offline map ? 
It is definitly possible the offline android client requires more metadata in the mbtiles file, which tilemaker does not generate.

**Comment by systemed** [comment]
I’d take a look at the name tag expected by your style vs that generated by tilemaker. The OpenMapTiles schema is historically a bit unclear on name vs name_en vs name_latin etc. - it’s possible tilemaker is generating one and your style is expecting another.

**Comment by abhiank** [comment]
@systemed I see both `name` and `name-en` in the style json. 
https://github.com/abhiank/OfflineMapExample/blob/master/app/src/main/assets/bright.json#L3061
https://github.com/abhiank/OfflineMapExample/blob/master/app/src/main/assets/bright.json#L3458

I tried replacing `name_en` with `name` and running the app again. It didn't work with that either..

How can I find out what tag is tilemaker using?

@kleunen, yes, I've only tried this file on Android yet. I don't have a setup to view mbtiles file online. But I'm trying to use this tool after you mentioned to try to view the file elsewhere - https://github.com/mapbox/mbview.

Where can I find out what data those extra table represent? Unfortunately, these tables are not mentioned in the MBTiles spec - https://github.com/mapbox/mbtiles-spec/blob/master/1.3/spec.md

**Comment by systemed** [comment]
tilemaker writes name:latin - see line 520 of https://github.com/systemed/tilemaker/blob/master/resources/process-openmaptiles.lua . You could change that line (or change your style to use name:latin).

**Comment by abhiank** [comment]
Thanks @systemed, I replaced all `"text-field": "{name}"` with "text-field": "{name:latin}" and it worked! 

Wouldn't it be syntactically correct to encode the MBTiles with "name" instead of "name:latin"?

**Comment by kleunen** [comment]
What kind of app are you building?

**Comment by abhiank** [comment]
@kleunen, This is the app I'm working on. 
https://play.google.com/store/apps/details?id=abhiank.maplocs

Trying to build in an offline map functionality into this. After considering all the options, MBTiles with Maplibre seemed like the best option to go with. So the next step in the process is creating the MBTiles files for all the regions and self hosting it. I'm glad I can do that with help from tilemaker.

@systemed If you use Android, I would be honored if you check out the app being a cyclist yourself.

**Comment by kleunen** [comment]
Very nice. Hope you can get it working.

**Comment by systemed** [comment]
> Wouldn't it be syntactically correct to encode the MBTiles with "name" instead of "name:latin"?

Honest answer is that I don't know. The OMT style we bundle with tilemaker (in its original, unaltered form) uses `name:latin`. The specs appear to say `name`, `name_en` and `name_de` but it's unclear how up-to-date they are. There are OMT issues at https://github.com/openmaptiles/openmaptiles/issues/930, https://github.com/openmaptiles/openmaptiles/pull/928 and https://github.com/openmaptiles/openmaptiles/issues/769 which are a bit inconclusive. If there's an unambiguous, always-works solution I'm very happy to go for that but it looks like it's all a bit of a mess!

> @systemed If you use Android, I would be honored if you check out the app being a cyclist yourself.

I'm mostly iPhone but I do have an Android phone somewhere so I'll try it out - I remember seeing good comments about your app on Reddit! Really good to see that tilemaker could be useful for you. The more independent cycling apps that aren't K*m**t, the better ;)

**Comment by abhiank** [comment]
> it looks like it's all a bit of a mess!

I went through the issues you linked and it indeed seems like a mess. Even if they fix it, tools which depend on this will continue to have to support all the old ones due to all the MBTiles files already in use. 

> I'll try it out - I remember seeing good comments about your app on Reddit! Really good to see that tilemaker could be useful for you

Thanks man! Indeed, tilermaker is making my life very easy. Else I would have to pay a lot to download latest MBTiles files from maptiler. Haha true.. those guys are eating up the cycle routing world. 

@kleunen thanks for writing the blogpost which helped me find this tool.

**Comment by lokkelvin2** [comment]
> Thanks @systemed, I replaced all `"text-field": "{name}"` with `"text-field": "{name:latin}"` and it worked!
> 
> Wouldn't it be syntactically correct to encode the MBTiles with "name" instead of "name:latin"?

Hey I just want to add that I faced the exact same issue using the [osm-liberty style](https://github.com/maputnik/osm-liberty) so I have to replace all values in `"text-field"` from `name` and `name_en` to `name:latin` to make the labels appear.

**Comment by systemed** [comment]
It might be interesting to see how much it would bloat the filesize to write `name` and/or `name_en` as well as `name:latin` for each object. Because MVT uses a per-tile dictionary for string values, the impact might not be that huge.
