### ISSUE TITLE
Tile generation using --store is singlethreaded

### ISSUE THREAD

**Issue by lokkelvin2** [systemed/tilemaker#287]
Using --store to generate the asia extract seems to run in single-threaded mode. This is after reading the pbf and at the `zoom xx: writing tile xxx of xxx` stage. My machine runs a dual socket Xeon 8168 with 192gb of RAM and the --store cache is 315gb on a nvme ssd. I believe that the computation at this stage should be multithreaded. However, cpu usage is only on 1 out of 96 cores and my disk i/o is basically 0%.

I am using the CI generated Windows artifact from commit 4053d523a31596d0156cd0458d17c8c45dbbbaff .

Any ideas what I could be doing wrong?

**Comment by kleunen** [comment]
It should be multithreaded at this phase. Maybe try to start the process with explicit specify the number of threads with: 
--threads 96

**Comment by lokkelvin2** [comment]
Thanks for the advice. I just retried it on my xeon machine and no dice, the CPU utilisation is still in the single digits. Strangely enough, the same binary runs multithreaded on a Ryzen 3600 pc when started without --store. I'll do some more investigation on the Xeon machine to see where the bottleneck is.

**Comment by kleunen** [comment]
yes, if you could investigate what the problem might be, because I honestly have no clue what could be the problem. It is the windows executable, correct ?
