### ISSUE TITLE
How can I add multi language support in the MBTiles created using this tool?

### ISSUE THREAD

**Issue by kuwapa** [systemed/tilemaker#305]
I wish to add support for multiple languages or possibly all the languages which are present in a PBF file to the MBTiles file so that I can dynamically change the language for display. 

My aim is to be able to change the language of tiles using this code https://docs.mapbox.com/help/troubleshooting/change-language/#mapbox-maps-sdk-for-android. Executing this code currently does not make any change for MBTiles generated using tilemaker. 

How do I go about doing this? Thanks.

**Comment by systemed** [comment]
You'll need to change your Lua script to read the name tags from OSM, and then write them into the vector tiles. Typically you'd do something like this:

    way:Attribute("name_fr", way:Find("name:fr"))

which means "write the contents of the OSM 'name:fr' tag into the 'name_fr' attribute for this vector tile object".

If you're using tilemaker's default Lua script, then have a look for the `SetNameAttributes` function, which is a common function called for most objects that have names.

**Comment by abhiank** [comment]
@systemed Thanks. I wanted to do some experiments before I replied. Here are some observations and questions. 

1. Since my goal was to setup multi languages, I took your advice and tried encoding in multiple languages like this. 
```
function SetNameAttributes(obj)
	obj:Attribute("name:latin", obj:Find("name"))
	obj:Attribute("name_ar", obj:Find("name:ar"))
	obj:Attribute("name_fr", obj:Find("name:fr"))
end
```
This worked partially. For eg, after creating the MBTiles file for an area of France, changing the `text-field` in the style to `name:latin` and `name_fr` both worked, however setting it to `name_ar` did not show any names on the map. When looking at multi lingual maps in https://maps.tracestrack.com/, I see that the major city names do have Arabic translations available for them which is what I was expecting to see in MBTiles file, but I did not see them on the map. Is this a limitation in tilemaker or an error in  my code?

2. For countries like Bangladesh or Yemen, using `obj:Attribute("name:latin", obj:Find("name"))` did not yield any tags at all and the map was completely empty. For yemen, even using `obj:Attribute("name_ar", obj:Find("name:ar"))` did not yield any names on the map. How to encode their local language names into MBTiles?

3. Continued from (2). For countries which have names mostly in local languages, map providers like Maptiler, Mapmillion are showing those local language tags in English. How to make this possible using tilemaker?

4. Just an observation - changing the `text-field` in the style manually seems to be doing the trick for now, but I have still been unable to figure out how to dynamically change the language like in the code from the first comment. Additionally, the code to dynamically change the language only seems to work with Mapbox tiles and not even Maptiler or Mapillion tiles. I'm unsure if this is happening from the style, or are new tiles fetched (which does not seem to be the case) or something to do with TileJSON (not sure how it works yet).

Any insights on these points will be very helpful. Thanks.

**Comment by kuwapa** [comment]
After I looked into how OSM stores the names of objects, I saw that for most countries, the `name` has the name of the object in english, however for countries like Bangladesh, Egypt, etc, the `name` field has the name in their default language - being Bangla, Arabic etc and additionally, the english version of the names are stored in `name:en`. So, for `SetNameAttributes(obj)` function, how do I write this logic in Lua -


if(`obj` contains `name:en`)
&ensp;&ensp;use `name:en`
else 
&ensp;&ensp;use `name`
end

**Comment by kuwapa** [comment]
I changed the `setNameAttribute()` to this and now english names are being encoded into the mbtiles for the non-english speaking countries

```
function SetNameAttributes(obj)
	if obj:Holds("name:en") then
		obj:Attribute("name:latin", obj:Find("name:en"))
	else
		obj:Attribute("name:latin", obj:Find("name"))
	end
```

**Comment by kuwapa** [comment]
An update on this issue :


### OSM Data
As I observed, for most objects in OSM, the `name` tag contained the name in the local language. So for English speaking countries, that would be English, for Arabic, the name tag would have arabic texts. There are 2 big problems with this

1. There is no information on what language the `name` tag is in. In my limited experience of OSM data, I think it would have been a better design to always store names in `name_en`, `name_es`, `name_ar` format and not have a generic `name` tag at all. 
2. There is no consistency on what language the `name` might be in. For eg, for most places in Mauritania, places are named in Arabic, but some place like [this](https://www.openstreetmap.org/node/7734401381) are named in English. Some places like [this](https://www.openstreetmap.org/node/3931963588) also had the name in both English and Arabic concatenated. 

### Requirement
For my requirement, I wanted to do show map in the language that the user's device is in. But since most places do not have names in more than a couple of languages and transliteration is not yet available, I wanted to show the user's language where its available and remaining times, show the default `name` tag value. 

### Solution

I changed the SetNameAttribute to this - 

```
function SetNameAttributes(obj)
	if obj:Holds("name:en") then
		obj:Attribute("name_en", obj:Find("name:en"))
	else
		obj:Attribute("name_en", obj:Find("name"))
	end

	if obj:Holds("name:fr") then
		obj:Attribute("name_fr", obj:Find("name:fr"))
	else	
		obj:Attribute("name_fr", obj:Find("name"))
	end

	if obj:Holds("name:ar") then
		obj:Attribute("name_ar", obj:Find("name:ar"))
	else	
		obj:Attribute("name_ar", obj:Find("name"))
	end

	if obj:Holds("name:es") then
		obj:Attribute("name_es", obj:Find("name:es"))
	else	
		obj:Attribute("name_es", obj:Find("name"))
	end
end
```

and then change the language dynamically in the app using this code - 

```
fun changeLanguage(lang: String) {
            map.getStyle { style ->
                style.getLayer("waterway-name")?.setProperties(PropertyFactory.textField(lang))
                style.getLayer("water-name-lakeline")?.setProperties(PropertyFactory.textField(lang))
                style.getLayer("water-name")?.setProperties(PropertyFactory.textField(lang))
                style.getLayer("poi-level-3")?.setProperties(PropertyFactory.textField(lang))
                style.getLayer("poi-level-2")?.setProperties(PropertyFactory.textField(lang))
                style.getLayer("poi-level-1")?.setProperties(PropertyFactory.textField(lang))

                style.getLayer("highway-name-path")?.setProperties(PropertyFactory.textField(lang))
                style.getLayer("highway-name-minor")?.setProperties(PropertyFactory.textField(lang))
                style.getLayer("highway-name-major")?.setProperties(PropertyFactory.textField(lang))
                //style.getLayer("highway-shield")?.setProperties(textField(lang))

                style.getLayer("place-other")?.setProperties(PropertyFactory.textField(lang))
                style.getLayer("place-village")?.setProperties(PropertyFactory.textField(lang))
                style.getLayer("place-town")?.setProperties(PropertyFactory.textField(lang))
                style.getLayer("place-city")?.setProperties(PropertyFactory.textField(lang))
                style.getLayer("place-city-capital")?.setProperties(PropertyFactory.textField(lang))

                style.getLayer("place-country-3")?.setProperties(PropertyFactory.textField(lang))
                style.getLayer("place-country-2")?.setProperties(PropertyFactory.textField(lang))
                style.getLayer("place-country-1")?.setProperties(PropertyFactory.textField(lang))

                style.getLayer("place-continent")?.setProperties(PropertyFactory.textField(lang))
            }
        }

changeLanguage("{name_es}")
```

### Issues
1. Checking if a layer has some information or not - Originally, I wanted to change the lua script to only write French tags in `name_fr` and Spanish text in `name_es` and so on. And then in app code, check if French name exists or not, Spanish name exists or not and accordingly set the one. However, checking if a language exists in the MBTiles layer does not seem possible. So I had to change the Lua script to write duplicate data for each language. 

3. The main issue I'm facing is that non-latin characters like Arabic are not being rendered at all. Mapbox SDK has an option to change the language and setting it to show Arabic works, so my guess is that the Maplibre SDK itself is not the issue. The next thing I checked was the font/glyphs. I'm currently using the Open Sans fonts from this repo from KlokanTech - https://github.com/klokantech/osm2vectortiles-gl-styles. I also tried the Noto Sans font from their repo and that too didn't work to show Arabic texts. I tried to find out what fonts was Mapbox using to show the Arabic texts but I couldn't find that out.  I have two questions here - (1) how can I check if the arabic texts are present in the MBTiles file  (2) Are non-latin texts being rendered in the MBTiles viewers you guys are using?

2. Lastly, the `highway-shield` layer - For this layer, changing the language was causing errors. On changing the language of this layer from English to any other language was leaving the boxes empty like shown in the screenshot. Changing the language back to English did not fix it but it rather started showing some street names in the boxes. So for now, I have commented out changing the language for the `highway-shield` layer. 


<img src="https://user-images.githubusercontent.com/8065733/134830966-83667e21-1416-41a9-b169-46369c4f22fb.jpeg" alt="English" width="500">
<img src="https://user-images.githubusercontent.com/8065733/134831167-63109b1a-e24b-43ed-b216-1da42da81fc8.jpeg" alt="Spanish" width="500">
<img src="https://user-images.githubusercontent.com/8065733/134831185-20953ce3-245d-4b4f-9644-8938fd064496.jpeg" alt="English" width="500">

**Comment by kuwapa** [comment]
Update regarding issue 2. I loaded up the MBTiles file created using tilemaker into VTM sdk sample and built it after changing the language to "ar"

https://github.com/mapsforge/vtm/blob/a82275315c34852dda67a38e86c778e81a855d49/vtm-android-example/src/org/oscim/android/test/MBTilesMvtActivity.java#L61

and it worked! The map shows the names in Arabic. Hence concluding that there is no problem with the MBTiles file itself. Now need to investigate what needs to be done in Maplibre to get it to show Arabic and other non-latin texts. 

![Screenshot_20210927-092532-min](https://user-images.githubusercontent.com/8065733/134843576-1dd3040a-853a-49a8-97e4-b8fb3165d781.jpeg)

**Comment by kuwapa** [comment]
The issue was regarding the typeface itself. After much searching, Arial Unicode Bold/Regular found here worked - https://github.com/aaronlidman/Toner-for-Tilemill/tree/master/toner4tilemill/fonts. 

Additionally, I used fontnik - https://github.com/mapbox/node-fontnik to generate the glyphs from the TTF file. 

Here's a screenshot showing Algiers which is rendering the Arabic texts using the Arial Regular typeface in Maplibre

![Screenshot_20211003-143343](https://user-images.githubusercontent.com/8065733/135747154-2cee7209-5597-4104-9ed2-57c9fa00cb14.jpeg)
