### ISSUE TITLE
How to create a smaller/lighter MBTiles file?

### ISSUE THREAD

**Issue by kuwapa** [systemed/tilemaker#309]
I created MBTiles files of two countries using extracts from Geofabric- Egypt and Bangladesh and loaded it in my [offline maps code example](https://github.com/abhiank/OfflineMapExample). In both cases, the map started seriously lagging on zoom levels 7-11 and then at one point just hung after which I had to kill the app. This issue however is not happening in the MBTiles file of those 2 countries obtained from Maptiler downloads. On closer inspection, the size of the MBTiles file created for Bangladesh using tilemaker was 200MB while the one downloaded from Maptiler was only 89MB. 

The size of the file however does not seem to be issue since bigger files from Maptiler also do not seem to be lagging and hanging the app. My only guess on why this is happening is because there are many layers in the tilemaker MBTiles file which the mobile SDK is unable to handle. So, 

1. How can I remove some layers from the MBTiles file? I tried simply removing them from the layers tag in the config json but that caused errors and did not work.

2. Would creating a lighter file work by removing layers or reducing the number of things to encode? - for eg, fewer POI types and fewer way types etc.

**Comment by kleunen** [comment]
You can remove layers from the 'config-openmaptiles.json'. Also reducing the maximum zoom level can have a significant difference, zoom level 14 has all details enabled. If you remove layers or reduce the zoom level, the file size will decrease yes.

**Comment by systemed** [comment]
It’s also possible that there are some complex geometries at z7-11 that tilemaker isn’t simplifying enough - forests, water, that sort of thing. Mapbox GL has an option to show tile boundaries for debugging, which also shows the tile size in kb - this can be useful in identifying problematic areas.

**Comment by abhiank** [comment]
@systemed Thanks for the suggestion. I found this option in the API - `map.isDebugActive = true` which starts showing the map tile boundaries but it doesn't show the tile sizes unfortunately. I couldn't find any other option to do that. However, I ran an sql average query on the MBTiles files - `SELECT avg(length(tile_data)) FROM tiles`. Bangladesh ->  4048 (tilemaker) vs 711 (Maptiler), Glasgow -> 11910 (tilemaker), 9258 (maptiler).  

@kleunen I tried removing some layers like `transportation_name_mid` and `transportation_name_detail`, but I kept running into errors which I tried to fix in the lua process file but couldn't get it to work. Also, I couldn't figure out what layers to remove since all of them seemed necessary and important. 

As a last ditch effort, I increased the values of `simplify_level` and `simplify_ratio` in the config file but the new Bangladesh mbtiles file still lagged and hangs the app. A question here - what does simplify tags do exactly - do they make complex shapes to simple shapes for easier rendering?

What else can I try to reduce the size of the tiles?

**Comment by systemed** [comment]
`map.showTileBoundaries=true` will show tile sizes in MBGL JS - maybe it's not supported in the Android version.

Probably the best thing you could do is use [vt2geojson](https://github.com/mapbox/vt2geojson) to export a typical problematic tile to GeoJSON, and do the same for the lighter equivalent from Maptiler. We can then load them into something like QGIS and see what the difference is. As mentioned, I think it's most likely to be an issue with water or landuse geometries, and the greater discrepancy in Bangladesh would support that. (Glasgow has a less complex river delta. ;) )

Simplification does indeed remove points at lower zoom levels as per https://en.wikipedia.org/wiki/Ramer–Douglas–Peucker_algorithm . The tilemaker parameters are explained in docs/CONFIGURATION.md.

**Comment by systemed** [comment]
I've just committed https://github.com/systemed/tilemaker/commit/28afdb8d8a03d7f09ccd4ffcb8c5668aad7ac6a1 which you might find an improvement - it uses the same simplification settings for admin boundaries as everything else (previously we weren't simplifying them enough). It brings a z9 tile in the Hebrides down from 26kb to 9gb which is a handy improvement.

**Comment by kuwapa** [comment]
After much trail and error, I found the main issue (in the Bangladesh file) was the water layer as @systemed suggested. I created mbtiles files with different `simplify_length` and `simplify_ratio` values until the lagging went away. The lag mainly happens on zoom level 7-8. Currently, this config stops the lag. However, this makes the rivers on the lower zoom levels look ugly.

```
"water": { "minzoom": 6,  "maxzoom": 14, "simplify_below": 12, "simplify_length": 10, "simplify_ratio": 7},
```

 My original question or approach was incorrect which was to reduce the file size itself. Removing multiple layers from the tile and reducing the file size to 150MB from 200MB did not make any difference in the lag. I have a few new questions regarding simplification
 
 1. Is it possible to set different `simplify_length`, `simplify_ratio` value for different zoom levels?
 2. Does `simplify_ratio` effect the `simplify_level` value or they operate independently? A little more explanation in the docs on the simplification topic will be very helpful. 
 3. How can I make the rivers appear like a line in zoom levels 7-8 like this -
 
![Screenshot_20210914-124839](https://user-images.githubusercontent.com/8065733/133213096-94fc6918-083c-4165-95ff-1388a678480e.jpg)


@systemed thanks! let me look into vt2geojson and compare the mbtiles files and try the new config from your commit.

**Comment by systemed** [comment]
They work like this:

- `simplify_below` is the zoom level below which geometries should be simplified. So if you set it to 13, they'll be simplified from z12 downwards.
- `simplify_level` is the amount of simplification, in degrees of longitude, at that zoom level.
- (`simplify_length` is an alternative to simplify_level, but expressed in metres.)
- `simplify_ratio` is the power by which to increase `simplify_level` at each zoom level (default 2)

The actual line of code which puts them together is

    simplifyLevel *= pow(ld.simplifyRatio, (ld.simplifyBelow-1) - zoom);

(where `ld` is layer definition and `zoom` is the current zoom level)

**Comment by kuwapa** [comment]
Thanks, I understand it now. One more doubt - is it more preferable to use `simplify_level` (degrees) instead of `simplify_length`? Both would correlate to a constant distance value isn't it?

**Comment by systemed** [comment]
The main difference is that `simplify_length` is reprojected according to the latitude of the object, because of [longitude convergence](https://www.usgs.gov/faqs/how-much-distance-does-a-degree-minute-and-second-cover-your-maps?qt-news_science_products=0#qt-news_science_products). But for most purposes there isn't much difference.

**Comment by kuwapa** [comment]
After a lot of experimentation and trial and error, this is the configuration I arrived at which doesn't cause the tiles to lag. It still has a lot of room for improvement like making landcover not look ugly on lower zoom levels etc, but I think its good enough for now. 

The main changes I made are
1. Landcover visible only zoom 8 onwards
2. Simplify boundary, water, waterway, landcover and landuse layers
3. Buildings visible only on zoom 14

Things that need improvement - 
1. Water layer to have more detail on zoom 6-9 + appear as a line on zoom 5
2. Landuse to not appear so blocky between zoom 8-10 without causing lag
3. Make boundary more detailed in zoom 5-7 without causing lag

```
{
	"layers": {
		"place":            { "minzoom":  0, "maxzoom": 14 },
		"boundary":         { "minzoom":  0, "maxzoom": 14, "simplify_below": 12, "simplify_level": 0.0006, "simplify_ratio": 2 },

		"poi":              { "minzoom": 12, "maxzoom": 14 },
		"poi_detail":       { "minzoom": 14, "maxzoom": 14, "write_to": "poi"},

		"housenumber":      { "minzoom": 14, "maxzoom": 14 },

		"waterway":         { "minzoom":  8,  "maxzoom": 14, "simplify_below": 12, "simplify_level": 0.0005, "simplify_ratio": 3 },
		"waterway_detail":  { "minzoom": 12,  "maxzoom": 14, "write_to": "waterway" },

		"transportation":             { "minzoom": 4,  "maxzoom": 14, "simplify_below": 14, "simplify_level": 0.0003 },
		"transportation_name":        { "minzoom": 8,  "maxzoom": 14 },
		"transportation_name_mid":    { "minzoom": 13, "maxzoom": 14, "write_to": "transportation_name" },
		"transportation_name_detail": { "minzoom": 14, "maxzoom": 14, "write_to": "transportation_name" },

		"building":          { "minzoom": 14, "maxzoom": 14 },

		"water":             { "minzoom": 6,  "maxzoom": 14, "simplify_below": 12, "simplify_level": 0.0004, "simplify_ratio": 3},
		"ocean":             { "minzoom": 0,  "maxzoom": 14, "source": "coastline/water_polygons.shp", "simplify_below": 13, "simplify_level": 0.0001, "simplify_ratio": 2, "write_to": "water", "index": true },
		"water_name":        { "minzoom": 14, "maxzoom": 14 },
		"water_name_detail": { "minzoom": 14, "maxzoom": 14, "write_to": "water_name" },

		"aeroway":           { "minzoom": 11, "maxzoom": 14 },
		"aerodrome_label":   { "minzoom": 10, "maxzoom": 14 },
		"park":              { "minzoom": 11, "maxzoom": 14 },

		"landuse":           { "minzoom":  4, "maxzoom": 14, "simplify_below": 14, "simplify_level": 0.0005, "simplify_ratio": 3 },
		"urban_areas":       { "minzoom":  4, "maxzoom":  8, "source": "landcover/ne_10m_urban_areas/ne_10m_urban_areas.shp", "source_columns": ["featurecla"], "simplify_below": 7, "simplify_level": 0.0003, "simplify_ratio": 2, "write_to": "landuse" },

		"landcover":         { "minzoom":  8, "maxzoom": 14, "simplify_below": 14, "simplify_level": 0.0005, "simplify_ratio": 3 },

		"ice_shelf":         { "minzoom":  0, "maxzoom":  9, "source": "landcover/ne_10m_antarctic_ice_shelves_polys/ne_10m_antarctic_ice_shelves_polys.shp", "source_columns": ["featurecla"], "simplify_below": 13, "simplify_level": 0.0005, "write_to": "landcover" },
		"glacier":           { "minzoom":  2, "maxzoom":  9, "source": "landcover/ne_10m_glaciated_areas/ne_10m_glaciated_areas.shp", "source_columns": ["featurecla"], "simplify_below": 13, "simplify_level": 0.0005, "write_to": "landcover" },
		"mountain_peak":     { "minzoom": 11, "maxzoom": 14 }
	},
	"settings": {
		"minzoom": 0,
		"maxzoom": 14,
		"basezoom": 14,
		"include_ids": false,
		"combine_below": 14,
		"name": "Tilemaker to OpenMapTiles schema",
		"version": "3.0",
		"description": "Tile config based on OpenMapTiles schema",
		"compress": "gzip",
		"filemetadata": {
			"tilejson": "2.0.0", 
			"scheme": "xyz", 
			"type": "baselayer", 
			"format": "pbf", 
            "tiles": ["https://example.com/liechtenstein/{z}/{x}/{y}.pbf"]
		}
	}
}

```

**Comment by systemed** [comment]
That's super helpful - thank you.

I'm reminded by another ticket that you might want to try `combine_below` to merge adjacent linestrings - that may have performance benefits. (There's also `combine_polygons_below` but the implementation of that is currently not as efficient as it could be, so use that one sparingly.)

**Comment by kuwapa** [comment]
Thanks for your help too! :)

I initially did try `combine_below` for the water layer but it it made it look a lot worse, and I didn't quite understand what it was doing, so I avoided it. Will try this in my next iteration of improving the config for my need. One question about it though - what is a linestring - Is it a line between two points in a shape?

Also, in what scenarios would adjacent linestrings exist? Would it be something like two highways running parallel?

**Comment by systemed** [comment]
A vector tile can hold three types of geometry: point, linestring, polygon. A linestring is another name for a polyline, i.e. a non-closed line such as a road, river or boundary.

tilemaker by default creates one line from each OSM way. At smaller zoom levels, that means that what looks like a continuous line might actually be made up of lots of bitty little lines all joined together. `combine_below` will reorder them, where possible, to make one continuous line. It's possible, likely even, that this will render faster.

**Comment by kuwapa** [comment]
Thanks for that explanation. Now I understand. I think this would be useful in the transportation layer where I saw a jumble of many tiny linestrings for cities at lower zoom levels. I now realise that using it for the water layer was the wrong approach since the water layer almost never had linestrings but mostly polygons. Will try `combine_below`.

**Comment by systemed** [comment]
Yep - there's a separate setting for polygons (`combine_polygons_below`) but it needs some refinement!
