### ISSUE TITLE
Error while running tilemaker on clipped osm files

### ISSUE THREAD

**Issue by sidneibjunior** [systemed/tilemaker#31]
I've downloaded planet.osm.pbf and used osmosis to clip a bounding-polygon.
The result is the following osm.pbf file: [clipped pbf file](https://www.dropbox.com/s/nrzf0vme8p5vxdh/osm-latest-clipped.pbf?dl=)

When processing this file with tilemaker I get the following output:

`Layer water (z0-15)`
`Layer waterway (z0-15)`
`Layer road (z0-15)`
`Layer road_bridge (z0-12) -> road`
`Layer bridge (z12-15)`
`Layer building (z15-20)`
`Layer poi (z0-15)`
`Layer admin (z0-15)`
`Layer aeroway (z0-15)`
`Layer barrier_line (z0-15)`
`Layer contour (z0-15)`
`Layer housenum_label (z0-15)`
`Layer landcover (z0-15)`
`Layer landuse (z0-15)`
`Layer country_label (z0-15)`
`Layer state_label (z0-15)`
`Layer place_label (z0-15)`
`Layer poi_label (z15-20)`
`Layer road_label (z0-15)`
`Layer tunnel (z0-15)`
`Layer water (z0-15)`
`Layer water_label (z0-15)`
`Layer waterway (z0-15)`
`Layer waterway_label (z0-15)`
`Layer marine_label (z0-15)`
`Reading /tmp/osm-latest-clipped.osm.pbf`
`terminate called after throwing an instance of 'std::out_of_range'`
`what():  _Map_base::at`
`Aborted`

**Comment by systemed** [comment]
One of the ways contains a reference to node 2073897685, but that node doesn't exist in the .pbf. Verified with:

````
osmconvert osm-latest-clipped.pbf -o=output.osm
grep 2073897685 output.osm
      <nd ref="2073897685">
````

This should be fixable by using Osmosis's clipIncompleteEntities or completeWays options (from reading the docs - I don't use Osmosis so haven't tried it!).

**Comment by sidneibjunior** [comment]
I clipped again using Osmosi's clipIncompleteEntities option and it worked!

Thanks  @systemed

**Comment by systemed** [comment]
No problem :)
