### ISSUE TITLE
Basic guidance on memory requirements

### ISSUE THREAD

**Issue by bt-maps** [systemed/tilemaker#310]
Hi,

I am looking  guidance for generating tiles from a 9.8 GiB pbf extract. Should I even attempt to do it using a MacBook pro  with 16gb of memory?
I know it's recommended to do country by country, but hoping to get an idea of what is possible with a typical laptop.
Brent

**Comment by kleunen** [comment]
With 16gb i doubt you are going to convert 9.8GiB with the current 2.0.0 release. You are probably better of splitting the region into two regions using osmium and using tilemaker --merge to combine them into a single mbtiles file. Even with this, you still have to use the --store option and have a fast ssd as a backup for the conversion process. 

Work is being done on reducing the memory requirements.

**Comment by kleunen** [comment]
I think the guide would be. If you renumber the input file, use the compact mode and use the store. You need a bit more than twice the amount of RAM as the size of the input file.

So input file is 3G, you need 6 to 7G of ram. And planet file is 60G. So you need 120 to 130G probably.

So with 10G osm file you need 20G ram. But better is 24G.

**Comment by systemed** [comment]
Closing as outdated - with v3 you should comfortably be able to use a 9.3GB extract on a 16GB Mac (assuming you use `--store`).
