### ISSUE TITLE
Error on creating MBTiles of osm.pbf extracts from download.openstreetmap.fr

### ISSUE THREAD

**Issue by kuwapa** [systemed/tilemaker#335]
Hi, 

Geofabric downloads have some regions like India, China, Indonesia etc only have big files and not smaller regions within them for download. Openstreetmap.fr downloads offer these smaller regions within these countries. However, on trying to create MBTiles using extracts I'm getting this error - 

(Tried with this file - https://download.openstreetmap.fr/extracts/asia/georgia-latest.osm.pbf)

`tilemaker --input georgia-latest.osm.pbf --output gor.mbtiles --config new_config.json --process new-process-openmaptiles.lua`

```
Layer place (z0-14)
Layer boundary (z0-14)
Layer poi (z12-14)
Layer poi_detail (z14-14) -> poi
Layer housenumber (z14-14)
Layer waterway (z8-14)
Layer waterway_detail (z12-14) -> waterway
Layer transportation (z4-14)
Layer transportation_name (z8-14)
Layer transportation_name_mid (z13-14) -> transportation_name
Layer transportation_name_detail (z14-14) -> transportation_name
Layer building (z14-14)
Layer water (z6-14)
Layer ocean (z0-14) -> water
Layer water_name (z14-14)
Layer water_name_detail (z14-14) -> water_name
Layer aeroway (z11-14)
Layer aerodrome_label (z10-14)
Layer park (z11-14)
Layer landuse (z4-14)
Layer urban_areas (z4-8) -> landuse
Layer landcover (z8-14)
Layer ice_shelf (z0-9) -> landcover
Layer glacier (z2-9) -> landcover
Layer mountain_peak (z11-14)
Can't read shapefiles unless a bounding box is provided.
```

So I installed osmium-tool and used `fileinfo` to look into the files. Unlike extracts from Geofabric, these files do not have the bounding box info encoded in it

`osmium fileinfo malaysia-latest.osm.pbf`
```
File:
  Name: malaysia-latest.osm.pbf
  Format: PBF
  Compression: none
  Size: 188942371
Header:
  Bounding boxes:
  With history: no
  Options:
    generator=pyosmium-up-to-date/3.0.1
    osmosis_replication_base_url=http://download.openstreetmap.fr/replication/./asia/malaysia/minute
    osmosis_replication_sequence_number=4743636
    osmosis_replication_timestamp=2021-10-05T01:28:58Z
    pbf_dense_nodes=true
    timestamp=2021-10-05T01:28:58Z
```

Then I looked up on if its possible to extract the bounding box from a osm.pbf file and fortunately found this solution which worked -
https://gis.stackexchange.com/a/379922/138032

`ogrinfo -dialect sqlite -sql "select ST_Envelope(geometry) from multipolygons where building is not null limit 5" malaysia-latest.osm.pbf`

```
Had to open data source read-only.
INFO: Open of `malaysia-latest.osm.pbf'
      using driver `OSM' successful.
	- 'VirtualXPath'	[XML Path Language - XPath]
	- 'VirtualXPath'	[XML Path Language - XPath]

Layer name: SELECT
Geometry: Unknown (any)
Feature Count: 5
Extent: (101.611363, 1.406565) - (104.030529, 3.021333)
Layer SRS WKT:
GEOGCRS["WGS 84",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    ID["EPSG",4326]]
Data axis to CRS axis mapping: 2,1
Geometry Column = ST_Envelope(geometry)
OGRFeature(SELECT):0
  POLYGON ((104.0282805 1.4065652,104.0305294 1.4065652,104.0305294 1.4078187,104.0282805 1.4078187,104.0282805 1.4065652))

OGRFeature(SELECT):1
  POLYGON ((101.6113633 3.02065,101.6123859 3.02065,101.6123859 3.0213332,101.6113633 3.0213332,101.6113633 3.02065))

OGRFeature(SELECT):2
  POLYGON ((103.7300584 1.433693,103.7307804 1.433693,103.7307804 1.4345569,103.7300584 1.4345569,103.7300584 1.433693))

OGRFeature(SELECT):3
  POLYGON ((103.7874631 1.4416748,103.788865 1.4416748,103.788865 1.442372,103.7874631 1.442372,103.7874631 1.4416748))

OGRFeature(SELECT):4
  POLYGON ((103.7949757 1.436935,103.7956036 1.436935,103.7956036 1.438694,103.7949757 1.438694,103.7949757 1.436935))

```

Then finally, I used this bounding box data and used it to create mbtiles using tilemaker

`tilemaker --input malaysia-latest.osm.pbf --output malay.mbtiles --bbox 101.611363,1.406565,104.030529,3.021333 --config new_config.json --process new-process-openmaptiles.lua`

for which I'm getting a new error- 

```
Layer place (z0-14)
Layer boundary (z0-14)
Layer poi (z12-14)
Layer poi_detail (z14-14) -> poi
Layer housenumber (z14-14)
Layer waterway (z8-14)
Layer waterway_detail (z12-14) -> waterway
Layer transportation (z4-14)
Layer transportation_name (z8-14)
Layer transportation_name_mid (z13-14) -> transportation_name
Layer transportation_name_detail (z14-14) -> transportation_name
Layer building (z14-14)
Layer water (z6-14)
Layer ocean (z0-14) -> water
Layer water_name (z14-14)
Layer water_name_detail (z14-14) -> water_name
Layer aeroway (z11-14)
Layer aerodrome_label (z10-14)
Layer park (z11-14)
Layer landuse (z4-14)
Layer urban_areas (z4-8) -> landuse
Layer landcover (z8-14)
Layer ice_shelf (z0-9) -> landcover
Layer glacier (z2-9) -> landcover
Layer mountain_peak (z11-14)
Bounding box 101.611, 1.40657, 104.031, 3.02133
Reading .shp ocean
Unable to open water-polygons-split-4326/water_polygons.shp or water-polygons-split-4326/water_polygons.SHP.
Reading .shp urban_areas
Unable to open landcover/ne_10m_urban_areas/ne_10m_urban_areas.shp or landcover/ne_10m_urban_areas/ne_10m_urban_areas.SHP.
Reading .shp ice_shelf
Unable to open landcover/ne_10m_antarctic_ice_shelves_polys/ne_10m_antarctic_ice_shelves_polys.shp or landcover/ne_10m_antarctic_ice_shelves_polys/ne_10m_antarctic_ice_shelves_polys.SHP.
Reading .shp glacier
Unable to open landcover/ne_10m_glaciated_areas/ne_10m_glaciated_areas.shp or landcover/ne_10m_glaciated_areas/ne_10m_glaciated_areas.SHP.
Sorting loaded shapes
Reading .pbf malaysia-latest.osm.pbf
Block 2507/2783 ways 0 relations 0        
Sorting nodes
terminate called after throwing an instance of 'kaguya::LuaRuntimeError'
  what():  Could not find node with id 8979039264
Aborted (core dumped)
```

I tried the same with Algeria and Angola. In all the 3 cases, tilemaker aborted after a node was not found. This issue does not happen with extracts of same countries from Geofabric.

How can I work around this issue? Are extracts from openstreetmap.fr in a different format which wont work with tilemaker?

Thanks.

**Comment by systemed** [comment]
It looks like openstreetmap.fr's extracts aren't generated with referential integrity. In other words, the .osm.pbf file contains ways for which not every node is included in the file. This is typically caused by generating the extracts with osmosis without the `clipIncompleteEntities` or `completeWays` options enabled.

Corroboration:

    galibier:~ richard$ osmium check-refs ~/Maps/planet/georgia-latest.osm.pbf 
    [======================================================================] 100% 
    There are 7896891 nodes, 575774 ways, and 8920 relations in this file.
    Nodes in ways missing: 6621

IMO these .osm.pbf files are ill-formed but then my opinion is probably neither here nor there. ;) In the example you gave (node 8979039264), this is in [an exclave of Brunei surrounded by Malaysia](https://en.wikipedia.org/wiki/Temburong_District), so I guess it's not too surprising that there's a clipping issue here.

We could potentially output a warning rather than exiting when this happens.

To get a bounding box, you can use `osmium fileinfo` with the `-e` (extended) option:

    galibier:~ richard$ osmium fileinfo -e ~/Maps/planet/georgia-latest.osm.pbf 
    [...]
    Data:
      Bounding box: (27.4578,40.3506,48.517,45.3611)

**Comment by kuwapa** [comment]
Thanks for the detailed analysis. Seems like using the osm.fr extracts are out of the question then. I guess I'll have to go the `osmium extract` route and extract smaller regions from existing big osm.pbf files from Geofabric. The reason I wanted to avoid that since I would have to collect the bounding box data for each smaller region I need. Maybe I could use the smaller osm.fr extracts just to find out the bounding box data which I need. Anyway, thanks again.

**Comment by systemed** [comment]
Try now: https://github.com/systemed/tilemaker/commit/0dd85fb0635b172c8bcf08944de235d21f72f84c

This adds a `--skip-integrity` command line option that will just keep going if it encounters a missing node.

(Whoops, that was meant to be a PR rather than committing straight to master... git fail on my part!)

**Comment by kuwapa** [comment]
Hehe happens to us all 😅

About the commit, it worked perfectly. Thanks! 
I wanted to understand a bit more on what the consequences of `--skip-integrity` are. Are ways which have missing nodes are entirely skipped? OR is it that just that node is skipped and when the map is rendered, and the way would have a gap in it? 

I rendered algeria-latest.osm.pbf from downloads.openstreetmap.fr and couldn't notice any visual differences even though the extract has 2516 nodes missing. 

```
osmium check-refs algeria-latest.osm.pbf 
[======================================================================] 100% 
There are 15003309 nodes, 1319540 ways, and 12613 relations in this file.
Nodes in ways missing: 2516
```

However, apart from the missing nodes issue, these extract have another problem - languages. It seems that only 2 languages have been added to the extract - English and French. Even the local languages have not been added. Also, for some reason, the end file size was bigger. algeria.mbtiles created using Geofabric extract - 210MB whereas algeria.mbtiles from osm.fr extract - 240MB.

**Comment by kuwapa** [comment]
@systemed, regarding the languages, I've changed the lua script to the following. For now, I've decided to add all the languages supported by my app. For all the languages, I've added the default fallback to English if its available. Using this script, Geofabric's extracts were able to show Arabic texts if I set the language to "{name:latin}", but osm.fr extracts did not have local language names. 

```
function SetNameAttributesForLanguage(obj,lang)
	local tagToWrite = "name_" .. lang
	local osmTag = "name:" .. lang

	if obj:Holds(osmTag) then
		obj:Attribute(tagToWrite, obj:Find(osmTag))
	elseif obj:Holds("name:en") then
		obj:Attribute(tagToWrite, obj:Find("name:en"))
	else	
		obj:Attribute(tagToWrite, obj:Find("name"))
	end
end
	

-- Set name, name_en, and name_de on any object
function SetNameAttributes(obj)
	obj:Attribute("name:latin", obj:Find("name"))

	if obj:Holds("name:en") then
		obj:Attribute("name_en", obj:Find("name:en"))
	else
		obj:Attribute("name_en", obj:Find("name"))
	end

	SetNameAttributesForLanguage(obj,"ca")
	SetNameAttributesForLanguage(obj,"da")
	SetNameAttributesForLanguage(obj,"de")
	SetNameAttributesForLanguage(obj,"es")
	SetNameAttributesForLanguage(obj,"fr")
	SetNameAttributesForLanguage(obj,"in")
	SetNameAttributesForLanguage(obj,"it")
	SetNameAttributesForLanguage(obj,"ja")
	SetNameAttributesForLanguage(obj,"ko")
	SetNameAttributesForLanguage(obj,"nl")
	SetNameAttributesForLanguage(obj,"pl")
	SetNameAttributesForLanguage(obj,"pt")
	SetNameAttributesForLanguage(obj,"ru")
	SetNameAttributesForLanguage(obj,"sl")
	
	-- **** do transliteration
end
```
