### ISSUE TITLE
Bus and metro stations not showing up?

### ISSUE THREAD

**Issue by wimpie3** [systemed/tilemaker#337]
I'm not able to show public transport stations on my map. POI's like hospitals, parkings and shops appear, but no stations or bus stops.

My layout json uses the "poi" source layer with a filter on "bus", "rail","airport".

Is Tilemaker using an alternative name for the transportation layer? Or does it currently skip those points while making the vector layers?

**Comment by systemed** [comment]
Ah, I see. Try building #338 and see if that makes it better.

**Comment by wimpie3** [comment]
I'm on Windows so that will be difficult...

**Comment by systemed** [comment]
You don't need to build tilemaker itself, it's just a change to the .lua file. If you change the process-openmaptiles.lua file to have that fix, then rerun tilemaker, it should (fingers crossed) work for you.

**Comment by wimpie3** [comment]
Seems to be working! Thank you!

**Comment by systemed** [comment]
Excellent!

**Comment by systemed** [comment]
Can you give me an OSM object link, please. For example, https://www.openstreetmap.org/node/123456

**Comment by wimpie3** [comment]
That is bizarre, cause the tram icons I can see on the maputnik link aren't visible on the openstreet map! OSM only shows bus stops...

**Comment by wimpie3** [comment]
So this should work, right? Hmmm... it's not...

```
      "id": "poi-tram_stop",
      "type": "symbol",
      "source": "openmaptiles",
      "source-layer": "poi",
      "minzoom": 15,
      "filter": [
        "all",
        [
          "==",
          "$type",
          "Point"
        ],
        [
          "==",
          "class",
          "railway"
        ],
        [
          "==",
          "subclass",
          "tram_stop"
        ]
      ],
```

**Comment by systemed** [comment]
Don't know, I'm afraid - debugging styles is a bit outside tilemaker's scope ;)

I'd recommend using `vt2geojson` as above for debugging - you can capture a vector tile in GeoJSON format and then look through it with a text editor to see if the data you want is in there.

**Comment by wimpie3** [comment]
tilemaker --input belgium-latest.osm.pbf --output=tiles/ --process process-openmaptiles.lua --config config-openmaptiles.json 

Source of the PBF is from geofabrik.

Extract ends with "Sorting  nodes" and returns to the command prompt. I've retried it with the original lua script and it's failing as well. I've recently installed Windows 11 on my laptop, might be due to that?
