### ISSUE TITLE
Translations from labels missing

### ISSUE THREAD

**Issue by wimpie3** [systemed/tilemaker#339]
At the moment, all labels are put in the field name:latin, in English. This poses a problem in countries where multiple languages are spoken and the street names (and other labels) need to be translatable "on the fly" to two or more languages. 

I've seen other style sheets using the fields "name-xx" where xx is the language code (en, fr, de, etc...). As I understand this is not 100% standardized yet (see https://github.com/systemed/tilemaker/issues/285#issuecomment-902059045). However, IMHO it's better to have a temporary solution using name-xx instead of having nothing at all, since only showing the English labels can be a no-go for many international developers.

**Comment by kuwapa** [comment]
I had the same issue, so I changed the process.lua file to encode all the languages I needed. I've mentioned the details in this thread - #305 and this comment - https://github.com/systemed/tilemaker/issues/335#issuecomment-935871440

**Comment by wimpie3** [comment]
Ok so I actually modified the lua script and added
`obj:Attribute("name_fr", obj:Find("name"))
`
in the SetNameAttributes module.

However, in my MapBox javascript, when I use
`map.setLayoutProperty('road_major_label', 'text-field', ['get','name_fr']);`
the labels are empty on the map.

So something is not working here... any help?

**Comment by wimpie3** [comment]
> But I think #340 provides a good solution for now. It lets you configure what languages you want to use in the vector tiles by editing a couple of variables at the top of the Lua script. These will be written to the most commonly used attributes (`name:latin`, `name_int`) but you can configure that too.

Perfect!
