### ISSUE TITLE
expose "isRelation" publicly to allow identification of converted multipolygons 

### ISSUE THREAD

**Issue by dieterdreist** [systemed/tilemaker#352]
Maybe I missed it and you already cater for it, I would like to see in the process.lua whether a way is derived from a multipolygon or not. Maybe a multipolygon derived way could get a virtual "area=yes" tag?

**Comment by dieterdreist** [comment]
Maybe "isRelation" in osm_lua_processing could become a public property?

**Comment by dieterdreist** [comment]
easier than I thought, I simply check for type=multipolygon

**Comment by typebrook** [comment]
> Maybe "isRelation" in osm_lua_processing could become a public property?

I think this is a good idea. For a clearer indication in lua script (Although tilemaker only support multipolygon for relation currently)

Actually I did this on my [fork](https://github.com/typebrook/tilemaker/commit/a8185978a0fd53a5c61404a3ae0b16ef119e1413). To build docker image which used in my [Github Page](https://typebrook.github.io/mapstew/#12/24.91158/121.61877) (for side project), so fontend can realize an element is a relation or a way.

![Screenshot from 2021-11-11 13-26-31](https://user-images.githubusercontent.com/19887090/141242636-f67b2ec9-7731-4b9f-830a-76f2597174a6.png)


@systemed Any concern?
