### ISSUE TITLE
Consecutive primitive groups are not read after reading first group

### ISSUE THREAD

**Issue by irnc** [systemed/tilemaker#353]
This issue manifested itself while working on a small extract from OSM, which was converted from OSM XML to `.osm.pbf` using Osmosis. Resulting `.osm.pbf` ([lasosna-4.osm.pbf.zip](https://github.com/systemed/tilemaker/files/7491208/lasosna-4.osm.pbf.zip)) has 1 primitive block containing 3 primitive groups (one for nodes, ways and relations).

After #243 reading a primitive group [triggers](https://github.com/systemed/tilemaker/pull/243/files#diff-bfb4ba738dcd19bc3dfbf147c0ef01f971eb3e07af31166c48d0d2a43f8ac02aR205) `handled_block = true` which results in block being [erased](https://github.com/systemed/tilemaker/pull/243/files#diff-bfb4ba738dcd19bc3dfbf147c0ef01f971eb3e07af31166c48d0d2a43f8ac02aR277) from the processing of consecutive phases, e.g. after nodes primitive group is read, consecutive ways group would not be read because block would be erased from the `blocks` map.

I guess removing call to `blocks.erase` could be a workaround, but it may result in a performance issue for big input files. 

Should we fix it by setting `handled_block = true` only when block has a single primitive group?

**Comment by systemed** [comment]
Ah, I'd occasionally wondered if that would ever be a problem.

> Should we fix it by setting `handled_block = true` only when block has a single primitive group?

Sounds like a good idea - do you want to try that or shall I have a go?

**Comment by irnc** [comment]
Please have a look at #354. Here we mark as handled not only blocks with a single group, but also blocks with multiple groups having data of the same type, i.e. all groups read during the current phase, so block is read in full and could be erased.
