### ISSUE TITLE
Invalid pbfs produced

### ISSUE THREAD

**Issue by rory** [systemed/tilemaker#36]
I have run tilemaker on the latest ireland-and-northern-ireland extract, and I get a pile of pbf files. However I don't think those tiles are valid protobuf files.

If I run:

    tilemaker ireland-and-northern-ireland-latest.osm.pbf --output=tiles

Then `protoc` can't read those files:

    $ protoc --decode_raw < tiles/13/3932/2588.pbf
    Failed to parse input.
    $ protoc --decode=vector_tile.Tile ./include/vector_tile.proto < tiles/13/3932/2588.pbf
    Failed to parse input.

All the output file suffer from this problem:

    $ find tiles -type f | while read FILENAME ; do protoc --decode_raw < $FILENAME ; done |& uniq -c
      53176 Failed to parse input.

Vector tiles downloaded from mapzen's vector tile format work and will give debugging/textual output.

*(I asked this on [StackOverflow](http://stackoverflow.com/questions/35367800/cannot-parse-a-protocol-buffers-file-in-python-when-using-the-correct-proto-fil/35384278))*

**Comment by systemed** [comment]
Is this a compression issue? Vector tile compression and naming is famously ambiguous (see Mapbox issues passim). You can tell tilemaker whether you want to produce compressed tiles or not.

**Comment by rory** [comment]
> Is this a compression issue?

It seems so. If I gunzip the pbfs then it works:

    $ zcat ietiles/13/3932/2588.pbf | protoc --decode_raw
    3 {
      1: "roads"
      2 {
        2: "\000\000"
        3: 2
        4: "\t\'\254<R\314\004\007\264\006\013\"\000br\020\n\020\006\346\0024\200\002& \n\031\252\002"
      }
      3: "type"
      4 {
        1: "track"
      }
      15: 1
    }
    $ zcat ietiles/13/3932/2588.pbf | protoc --decode=vector_tile.Tile ./include/vector_tile.proto 
    layers {
      name: "roads"
      features {
        tags: 0
        tags: 0
        type: LINESTRING
        geometry: 9
        geometry: 39
        geometry: 7724
        geometry: 82
        geometry: 588
        geometry: 7
        geometry: 820
        geometry: 11
        geometry: 34
        geometry: 0
        geometry: 98
        geometry: 114
        geometry: 16
        geometry: 10
        geometry: 16
        geometry: 6
        geometry: 358
        geometry: 52
        geometry: 256
        geometry: 38
        geometry: 32
        geometry: 10
        geometry: 25
        geometry: 298
      }
      keys: "type"
      values {
        string_value: "track"
      }
      version: 1
    }
