### ISSUE TITLE
Does not run when not run from source code directory

### ISSUE THREAD

**Issue by rory** [systemed/tilemaker#37]
I have compiled and installed tilemaker according to the documentation. I'm using Ubuntu 14.04. When I am in the tilemaker source code directory tilemaker works fine. When I am not in that directory, I get the following error:

    $ tilemaker ./ireland-and-northern-ireland-latest.osm.pbf --output=ietiles/
    tilemaker: ./include/rapidjson/filereadstream.h:44: rapidjson::FileReadStream::FileReadStream(FILE*, char*, std::size_t): Assertion `fp_ != 0' failed.

I have seen this error on 3 different (linux) machines so far.

**Comment by systemed** [comment]
Tilemaker expects a JSON config file and a Lua processing file. If you don't specify these on the command line, it will look in the current directory. If they're not present, it can't run.

I'm guessing this is what is happening here. The error message could be clearer though!

**Comment by rory** [comment]
That makes sense. Thanks.
