### ISSUE TITLE
Release 2.1

### ISSUE THREAD

**Issue by systemed** [systemed/tilemaker#379]
We've had lots of worthwhile improvements since 2.0 so I think it's about time to do a new release. The changelog hasn't kept up so I'll need to update that.

Are there any outstanding issues that we need to fix (ideally not too complex/time-consuming) before a new release?

cc @kleunen @leonardehrenfried

**Comment by leonardehrenfried** [comment]
I've been running latest master production for a while and have not noticed any problems. So yes, go ahead.

**Comment by kleunen** [comment]
indeed, i think it is stable now. 2.1 contains some useful small fixes, making things much more stable.

**Comment by kleunen** [comment]
There is 1 thing. I think tilemaker is now added to the debian repository, but the man page the debian developers made is not very complete / correct. So maybe it is good to add a man page to the tilemaker repository.

**Comment by systemed** [comment]
Good point - I've added more detail on the options to the man page.

v2.1 now released and artifacts uploaded :)
