### ISSUE TITLE
Metadata of MBTiles 1.3 SHOULD contain `center`

### ISSUE THREAD

**Issue by yuiseki** [systemed/tilemaker#380]
Hi,

I love this really great, ultra fast tile maker software and Now I'd like to help in any way I can.

I found MBTiles file created by this `tilemaker` does not contain `center` in metadata.
Some kind of MBTiles server expects `center` and failed to draw the map if `center` is missing.

Specification of MBTiles 1.3 says we SHOULD contain `center` key/value in metadata.
https://github.com/mapbox/mbtiles-spec/blob/master/1.3/spec.md#content

I've read the code and I've understood line 367 of `src/tilemaker.cpp` has checking `defaultView` config value and write `center` to metadata or not.
https://github.com/systemed/tilemaker/blob/0dd85fb0635b172c8bcf08944de235d21f72f84c/src/tilemaker.cpp#L367

I believe we should write `center` metadata whether the `defaultView` config is specified or not.
How about that to determine value of `center` from `bounds`, `minzoom`, `maxzoom` values when `defaultView` config does not specified?

I'd really like to make a pull request to this project, but I'm a beginner in C++, so it might take a while...
If anyone is interested in fixing this issue, could you fix it?

Thanks!

**Comment by fpetry** [comment]
I can second this. I also had the problem and the changes of @yuiseki fixed it.
