### ISSUE TITLE
segmentation fault with tilemaker 2.1

### ISSUE THREAD

**Issue by mytracks** [systemed/tilemaker#382]
Hi.

I am using the new `relation_scan_function` of tilemaker 2.1 to process OSM data. This works well with smaller input files. But when I use a larger file it crashes with a `segmentation fault`. It is not a problem with the RAM on the machine since the machine has lots of it. The file is filtered using osmfilter. It only contains objects related to `routes`. This filtered file (routes-planet.osm.pbf) has a file size of 948MB. The crash happens quite early after about one minute.

The output is this:
```
gis@vps-06:~/tilemaker-configs/routes$ tilemaker --input routes-planet.osm.pbf --output routes-planet.mbtiles
Layer route (z10-14)
Bounding box -180, -85.06, 180, 85.06
Sorting loaded shapes
Reading .pbf routes-planet.osm.pbf
Block 31/67 ways 0 relations 0
Sorting nodes
Segmentation fault
```

I published this tilemaker configuration on GitHub:
https://github.com/mytracks/tilemaker-configs/tree/main/routes

Thanks,
Dirk

**Comment by systemed** [comment]
Hm. I wondered if it could be an overflow but I can't see anything obvious that might overflow, which makes me think it might be circumstances around a particular relation. I'll continue to look into it.

**Comment by systemed** [comment]
Rather exasperatingly this seems to be the sort of issue that happens in normal usage but doesn't show up when running tilemaker under valgrind...

**Comment by systemed** [comment]
https://github.com/systemed/tilemaker/commit/7c8e2e6995d2d0c2b7434cc3c533c9259d99ea9c should fix this.

**Comment by mytracks** [comment]
Thank you very much. This fix solves my problem. And processing all routes of the filtered planet file is still pretty fast (about 20 minutes).
