### ISSUE TITLE
Cannot set Version 8 in config-openmaptiles.json 

### ISSUE THREAD

**Issue by fpetry** [systemed/tilemaker#385]
I'm trying to use mapbox-gl-js with tiles served by mbtileserver and created with tilemaker.

The validation of mablibre-gl-js fails with 

```
[...]
Error: version: expected one of [8], "3.0" found
[...]
```

And Indeed, tilemaker places the string from config-openmaptiles.json there, which is the string "3.0.0":

```
{
  "bounds": [...],
  "center": [...],
  "description": "Tile config based on OpenMapTiles schema",
  "format": "pbf",
  "map": "https://[redacted]/services/[redacted]/map",
  "maxzoom": 14,
  "minzoom": 0,
  "name": "Tilemaker to OpenMapTiles schema",
  "scheme": "xyz",
  "tilejson": "2.1.0",
  "tiles": [
    "https://[redacted]/services/[redacted]/tiles/{z}/{x}/{y}.pbf"
  ],
  "type": "baselayer",
  "vector_layers": [...],
  "version": "3.0"
}
```

When trying to just set the integer '8' there the validation of tilemaker fails:

```
[...]
mbtiles file exists, will overwrite (Ctrl-C to abort, rerun with --merge to keep)
tilemaker: /usr/include/rapidjson/document.h:1681: const Ch* rapidjson::GenericValue<Encoding, Allocator>::GetString() const [with Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; rapidjson::GenericValue<Encoding, Allocator>::Ch = char]: Assertion `IsString()' failed.
Aborted (core dumped)
[...]
```
Is there another way to set this? Am I doing something wrong, or is there an issue?

**Comment by systemed** [comment]
Hm. The version in the `settings` object within tilemaker's `config.json` (stored internally as `projectVersion`) is written in two places:

- Within the `metadata` table of the .mbtiles. The [mbtiles spec](https://github.com/mapbox/mbtiles-spec/blob/master/1.2/spec.md#metadata) defines it as "The version of the tileset, as a plain number".
- Or if you write out to individual tile files, within a `metadata.json` file. The [TileJSON spec](https://github.com/mapbox/tilejson-spec/tree/master/2.2.0) defines it as "OPTIONAL. Default: "1.0.0". A semver.org style version number."

The only spec referring to version 8 (as an integer) is [Mapbox GL style JSON](https://docs.mapbox.com/mapbox-gl-js/style-spec/root/#center). But that isn't something under tilemaker's control, that's just whatever style you choose. Have you checked your style file to see if it has the correct version?

**Comment by fpetry** [comment]
Thank you. You pointed me in the right direction. At some point during my tests I configured the mbtiles "service" as style in the maplibre-gl-js script. So actually there was no style anymore and I was mislead by the version warning.

For later readers with a similar setup:

* The maplibre-gl-js "style" option points to a style.json file hosted separately
* The style.json (v8) points to the mbtiles TileJSON service, where the vector tiles are served (v3.0.0)

So no error, just some usage problems on my side.
