### ISSUE TITLE
server.rb listens only on 127.0.0.1

### ISSUE THREAD

**Issue by borisgontar** [systemed/tilemaker#391]
Anybody knows how to make server.rb listen on all interfaces? Thanks.

**Comment by systemed** [comment]
server.rb really is only for local testing. If you're trying to run it on anything other than your local machine you're using it for something it isn't designed for.

There are lots of mbtiles servers out there you can use in production. I use https://github.com/systemed/mod_mbtiles but searching Github will find you servers in PHP, Go, Python, Node, whatever you like.

If you absolutely do have to run server.rb (say, you're developing the style on one machine and want to test it from your mobile or something) and you want it to listen to a different IP address, I think you can do this by altering the Rack invocation to:

````ruby
Rack::Handler::WEBrick.run(app, { Host: "123.12.0.9" })
````

or whatever the format is for the latest version.

**Comment by SomeoneElseOSM** [comment]
For completeness,

    Rackup::Handler::WEBrick.run( app, { Host: "0.0.0.0" } )

or

    Rackup::Handler::WEBrick.run( app, { Host: "a.b.c.d" } )

(where "a.b.c.d" is the LAN IP address of the server) does not work:

    ruby  server.rb ~/data/rutland-latest.mbtiles  
    Starting local server
    /var/lib/gems/3.0.0/gems/rackup-0.2.3/lib/rackup/handler/webrick.rb:32:in `run': wrong number of arguments (given 2, expected 1) (ArgumentError)
            from server.rb:119:in `<class:MapServer>'
            from server.rb:22:in `<main>'

(using "Rackup:" instead of "Rack:" is needed to get to this stage on Ubuntu 22.04)

I am only doing local testing of course, but on a VM.  I'll investigate other serving options.

**Comment by SomeoneElseOSM** [comment]
An actual way of running this so that it works is:
                options = { Host: "0.0.0.0" }
                Rackup::Handler::WEBrick.run(app, **options )

(I've no idea if this varies by ruby or OS version - this was on Debian 12)

However, 
~/src/tilemaker/server/static/style.json
and
~/src/tilemaker/server/static/spec.json
both have "localhost" hardcoded in them, which obviously needs changing too.
