### ISSUE TITLE
Point on surface instead of centroid

### ISSUE THREAD

**Issue by Nakaner** [systemed/tilemaker#392]
For labeling countries, point on surface is a better approach to get a labeling point than centroids because centroids can be located outside the polygon, e.g. France being labeled in the Bay of Biscay.

**Comment by systemed** [comment]
Good thinking. It looks like Boost.Geometry does have a point_on_surface implementation as well.

**Comment by freeExec** [comment]
https://github.com/mapbox/polylabel

**Comment by geoneutrino** [comment]
Brining this issue back as i also stumbled on labels 

Boost geometry seems to support point on surface. Tilemaker Readme says version 1.66+ required
https://www.boost.org/doc/libs/1_66_0/boost/geometry/algorithms/point_on_surface.hpp

Would it be integrateable or is there more missing ?

**Comment by systemed** [comment]
Fixed in v3.
