### ISSUE TITLE
field from shapefile not included in mbtiles?

### ISSUE THREAD

**Issue by oudoken** [systemed/tilemaker#394]
Hello there,
Thanks for tilemaker it's a great tool.
I'm having some problem in adding a shapefile.

The data from the shapefile it's correctly added btw the fields in the shapefile are added based on the json config file:

        "myshape": {
            "minzoom": 2,
            "maxzoom": 14,
            "source": "myshape.shp",
	    "source_columns": ["the_column"] // also can be true it does not change
        }

No matter if i put true or the column array the only field created it's "Class" (?) this field it's not in the dbf of shapefile.
It' possibile i'm missing something? Maybe a character encoding issue? Or there are some required fields in the DBF?
Thanks

**Comment by systemed** [comment]
It sounds like you're using the default OpenMapTiles-compatible schema. This includes an `attribute_function` which only writes out the fields used by the OpenMapTiles schema:

````lua
-- Remap coastlines
function attribute_function(attr,layer)
	if attr["featurecla"]=="Glaciated areas" then
		return { subclass="glacier" }
	elseif attr["featurecla"]=="Antarctic Ice Shelf" then
		return { subclass="ice_shelf" }
	elseif attr["featurecla"]=="Urban area" then
		return { class="residential" }
	else
		return { class="ocean" }
	end
end
````

If you want to write out custom fields (i.e. effectively a different schema) you'll need to add a bit of code accordingly. This should do it:

````lua
function attribute_function(attr,layer)
	if layer=="myshape" then
		return attr
	elseif attr["featurecla"]=="Glaciated areas" then
		return { subclass="glacier" }
	[...]
````

**Comment by oudoken** [comment]
Hi @systemed,
Thanks for the reply!
The issue is resolved, i've not looked into the lua because the documentation was referring only to the json configuration file.
Now it's working perfectly, Thanks
