### ISSUE TITLE
Error while processing geometry LINESTRING when using Colombia-latest

### ISSUE THREAD

**Issue by mvanlaar** [systemed/tilemaker#395]
I'm trying to build with the windows version 2.2 and the latest download from geofabrik.de for colombia (the country). 

I'm getting the following error:

Stored 32249279 nodes, 69282 ways, 11047 relations
Shape points: 0, lines: 0, polygons: 384
Generated points: 332127, lines: 1890689, polygons: 2193019
Error while processing geometry LINESTRING,33229659,Could not find generated linestring with id 33229659
Error while processing geometry LINESTRING,33264230,Could not find generated linestring with id 33264230
Error while processing geometry LINESTRING,33264233

Full log: 
[tilemakererror.txt](https://github.com/systemed/tilemaker/files/8252986/tilemakererror.txt)

Try to run it with the default configs

tilemaker --input colombia-latest.osm.pbf --output colombia.mbtiles --process resources/process-openmaptiles.lua --config resources/config-openmaptiles.json --verbose --skip-integrity

The specs of the machine are: 384 GB Memory and 16 cores 32 threads.

**Comment by mvanlaar** [comment]
When running it with de visual studio debugger on the exe i'm getting this error:
Unhandled exception at 0x00007FF9AEBC286E (ucrtbase.dll) in tilemaker.exe: Fatal program exit requested.

**Comment by mvanlaar** [comment]
Relates to #399

**Comment by systemed** [comment]
Unfortunately I'm not able to debug Windows issues. The best thing anyone could do here would be to look back through previous versions and find the last commit which worked as expected.

**Comment by mvanlaar** [comment]
I've workaround it by using the github action and saving the result in the artifact. I've you like i can share the actions config.
