### ISSUE TITLE
segfault with latest

### ISSUE THREAD

**Issue by dieterdreist** [systemed/tilemaker#397]
Segmentation fault: 11  tilemaker --config ${p}/config.json --process ${p}/process.lua --input ${ACTUALSOURCE} --output ${p}/tilesets/${LOCALOSMCUT}.mbtiles

(sorry for the not so complete information). It works without problems with a06d0aa (1st march)

**Comment by systemed** [comment]
Do you have the source .osm.pbf for this?

**Comment by dieterdreist** [comment]
here you are: http://23m.it/20220318_roma_large.osm.pbf

**Comment by systemed** [comment]
Hm, works fine for me. Are you using the standard config.json/process.lua or custom ones?

**Comment by dieterdreist** [comment]
hm, very strange, encouraged by your results I switched the repo back to latest, recompiled and this time it worked (both, with the 18/3 file and with a new one).
