### ISSUE TITLE
Ocean partially visible  

### ISSUE THREAD

**Issue by ns9920** [systemed/tilemaker#401]
Hi 

I think I must have missed something but I really can't understand why this ocean is not visible as it is styled properly.
maybe I must have defined the bbox wrong ? 

please let me know 

<img width="1440" alt="Screenshot 2022-03-23 at 11 27 05 PM" src="https://user-images.githubusercontent.com/43876575/159699450-0854f1ff-032b-49df-aa59-a196b8985ae3.png">

**Comment by systemed** [comment]
> maybe I must have defined the bbox wrong ?

Can't really tell unless you tell us what you did... (command line invocation, where the .pbf file came from, whether you're using the standard config/process.lua or a different one, etc.)

Generally help requests are better under discussions ^^^ rather than issues.

**Comment by ns9920** [comment]
I have used the pbf files from
Geofabrik for all the continents with the specified coastline ocean and landcover data files then merged all the mbtiles created

**Comment by systemed** [comment]
What are your exact command line steps?
