### ISSUE TITLE
Missing tiles? tilemaker + tileserver-gl

### ISSUE THREAD

**Issue by xewonder** [systemed/tilemaker#406]
Hello.

very new to this but i have a problem and i don't know who do ask?

 i used tilemaker to generate the mbtiles
./tilemaker --input greece-latest.osm.pbf --output greece.mbtiles --process resources/process-openmaptiles.lua --config resources/config-openmaptiles.json 
with the following:
[config-openmaptiles 2.json.txt](https://github.com/systemed/tilemaker/files/8457068/config-openmaptiles.2.json.txt)

then i run it with the basic 
docker run --rm -u 0 -it -v $(pwd):/data -p 8080:80 maptiler/tileserver-gl
with the following config:
[config.json.txt](https://github.com/systemed/tilemaker/files/8457089/config.json.txt)

there are tiles missing?
![Screenshot 2022-04-09 170307](https://user-images.githubusercontent.com/14354903/162577644-899959a9-e48b-4573-817c-d1250f25bf49.png)

it should look like this:

![Screenshot 2022-04-09 170813](https://user-images.githubusercontent.com/14354903/162577805-70681726-e851-459f-ba2b-afbaf0b154da.png)

any help appreciated!

(if anyone can help me to check if it's the mbtiles or tileserver, here is the link to my mbtiles https://e1.pcloud.link/publink/show?code=XZnvcHZVAyReWOJuR07ec1Tzwc2Wy7YH7GX) 800mb

**Comment by systemed** [comment]
You need to supply the coastline data. See the instructions beginning "If you want to include sea tiles" in the readme. I don't know how that works with docker, sorry.

**Comment by xewonder** [comment]
That was EXACTLY it!

Thank you so much!
