### ISSUE TITLE
compiling??

### ISSUE THREAD

**Issue by xewonder** [systemed/tilemaker#408]
Hello.

I have tried on several releases of Ubuntu to compile tilemaker in order to get zoom over 17 without success.

I am using the per-compiled version that is available to download and it works great on Ubuntu 20.04.4 LTS.

Can you please make a version that will make tiles at over 17 zoom  and make it available to download?

Many thanks

DD

**Comment by systemed** [comment]
I don't think we'll provide a pre-built download but you should be able to compile it like this:

    make CONFIG="-DFAT_TILE_INDEX"
    sudo make install

Out of interest, why do you want to create tiles at zoom levels over 17? Usually with vector tiles you just create them up to z14 (or z15 at a pinch), and include all the features for higher zoom levels in the z14 (/z15) tiles. The client-side renderer will then "overzoom" these tiles when zooming in.

**Comment by systemed** [comment]
When you say "you can just not make it compile", what exactly happens in the console?

> if want my city at zoom 18..?

As I say above, you generate tiles up to z14, and the client-side renderer (e.g. MapLibre GL) "overzooms" them when you zoom in further. There is no point in generating 2**4 times more tiles when all the information you need for a z18 tile is in a z14 tile anyway. All this is explained in https://github.com/systemed/tilemaker/blob/master/docs/VECTOR_TILES.md

**Comment by xewonder** [comment]
> As I say above, you generate tiles up to z14, and the client-side renderer (e.g. MapLibre GL) "overzooms" them when you zoom in further. There is no point in generating 2**4 times more tiles when all the information you need for a z18 tile is in a z14 tile anyway. All this is explained in https://github.com/systemed/tilemaker/blob/master/docs/VECTOR_TILES.md

are you telling me that zoom 14 is enough? when it tried the default, after 14 i was getting a blank map...

Im sorry... i have not enough experience ... at (compiled) zoom 16 though it's doing as you said.

Thank you!
