### ISSUE TITLE
Create two objects in same layer from the same way

### ISSUE THREAD

**Issue by ThibaudM** [systemed/tilemaker#41]
Hello,

I tried to use the following in lua:

```
function way_function(way)
    way:Layer("layer1", true)
    way:Attribute("key", "value1")

    way:Layer("layer1", true)
    way:Attribute("key", "value2")
end
```

This code generates only one feature (instead of 2) in the final geojson.
#### Finding the problem

In the source code this behaviour is due to:
`map< uint64_t, unordered_set<OutputObject> > tileIndex;` in _tilemaker.cpp_ and

```
bool operator==(const OutputObject& x, const OutputObject& y) {
    return (x.layer == y.layer) && (x.objectID == y.objectID) && (x.geomType == y.geomType);
}
```

in _output_object.cpp_ because there is no verification of equality for attributes field.
#### Trying to resolve

For me there are 2 solutions:
- Compare attributes fields in `bool operator==(const OutputObject& x, const OutputObject& y);` in _output_object.cpp_
- Change the `unordered_set` type to a `vector` type

These 2 solutions give the same result. It works when there is only one zoom level but creates too much features when I tried:

```
{
    "layers": {
        "layer1": { "minzoom": 16, "maxzoom": 18 }
    },
    "settings": {
        "minzoom": 16,
        "maxzoom": 18,
        "basezoom": 18,
        "include_ids": false,
        "name": "OSM Vector Tiles",
        "version": "0.1",
        "description": "Vector Tiles from OSM data, created with tilemaker",
        "compress": "none"
    }
}
```

Have you an idea of How can we fix this problem ?

And thank you for your nice job :)

Thibaud

**Comment by grafi-tt** [comment]
Probably your settings of `maxzoom` and `basezoom` are problematic.
Your value 18 is greater than 16, however, Tilemaker assumes a zoomlevel is less than or equals to 16. (Tilemaker assigns 16bits to each of x and y coordinates.)
If you change the value to 15 or so, I expect the first solution gives the correct result.
Could you try it?

Even though, the second solution would not gives the correct result.
This is because multiple identical objects are copied into `generatedIndex[newIndex]`, in the following part of `tilemaker.cpp`.
```
			// otherwise, we need to run through the z14 list, and assign each way
			// to a tile at our zoom level
			for (auto it = tileIndex.begin(); it!= tileIndex.end(); ++it) {
				uint index = it->first;
				uint tilex = (index >> 16  ) / pow(2, baseZoom-zoom);
				uint tiley = (index & 65535) / pow(2, baseZoom-zoom);
				uint newIndex = (tilex << 16) + tiley;
				unordered_set<OutputObject> ooset = it->second;
				for (auto jt = ooset.begin(); jt != ooset.end(); ++jt) {
					generatedIndex[newIndex].insert(*jt);
				}
			}
```
I guess we can fix this by applying `sort()` and `uniq()` (then we need the `=` operator again, and the `<` operator is also required).

**Comment by ThibaudM** [comment]
In fact, I already fixed the problem for zoom level > 16 with tilemaker.
For my problem, I found a solution by modifying the == operator of OutputObject like this:

```c++
bool operator==(const vector_tile::Tile_Value& x, const vector_tile::Tile_Value& y) {
        if(x.has_string_value() && y.has_string_value())
                return x.string_value() == y.string_value();
        if(x.has_float_value() && y.has_float_value())
                return x.float_value() == y.float_value();
        if(x.has_double_value() && y.has_double_value())
                return x.double_value() == y.double_value();
        if(x.has_uint_value() && y.has_uint_value())
                return x.uint_value() == y.uint_value();
        if(x.has_sint_value() && y.has_sint_value())
                return x.sint_value() == y.sint_value();
        if(x.has_bool_value() && y.has_bool_value())
                return x.bool_value() == y.bool_value();
        return false;
}
bool operator!=(const vector_tile::Tile_Value& x, const vector_tile::Tile_Value& y) {
        return !(x == y);
}
 
bool operator==(const OutputObject& x, const OutputObject& y) {
 
        std::map<string, vector_tile::Tile_Value>::iterator it;
        
        if ((x.layer != y.layer) || (x.objectID != y.objectID) || (x.geomType != y.geomType) || (x.attributes.size() != y.attributes.size()))
       return false;
 
        for (auto i = x.attributes.begin(); i != x.attributes.end(); ++i) {
                if( !y.attributes.count(i->first) || y.attributes.at(i->first) != i->second)
                        return false ;
        }
 
        return true;
}
```

**Comment by systemed** [comment]
Could you test with the latest version and let me know if this is still an issue?

**Comment by ThibaudM** [comment]
The last version works, thank you
