### ISSUE TITLE
Merge layers

### ISSUE THREAD

**Issue by eliabieri** [systemed/tilemaker#410]
Is there a way to generate tiles where all layers are merged into one?
I'm working with a library that has the limitation of expecting only a single layer (as delivered by mapbox or stadia)

**Comment by systemed** [comment]
You could do this either by changing the Lua script so it only writes to one layer, or by adding `write_to` directives in the JSON config - the latter might be easiest. https://github.com/systemed/tilemaker/blob/master/docs/CONFIGURATION.md explains how they work.

I'm slightly intrigued as to the difference - I wasn't aware that Mapbox or Stadia were doing things differently. A sample vector tile would be interesting if you have one.

**Comment by eliabieri** [comment]
Thank you. I tried to write all layers to a single one using the `write_to` directive, but the `vector_map_tiles` Flutter package is still rejecting the tiles.  
I'll post an update once I know more.

**Comment by systemed** [comment]
If you can post a URL of a vector tile that works (i.e. https://your.server/tiles/z/x/y.pbf), and a URL of one that doesn't, I can look into it.

**Comment by eliabieri** [comment]
Yes sure. 
[Here](https://github.com/systemed/tilemaker/files/8750202/example_tiles.zip) you find two MVT tiles, both for the exact same Z, Y and X parameters.   
One is working (Stadiamaps) and one is not (exported using tilemaker so a single layer).

**Comment by systemed** [comment]
Ok, thanks. Can you post the process.lua and config.json that you used to create the tilemaker tile?

The Stadia tile definitely has layers in it (`vt2geojson working_2867.pbf -z 13 -x 4268 -y 2867 | grep vt_layer`) as do standard tilemaker layers, so I'm not sure what you're doing with your tilemaker config.

**Comment by eliabieri** [comment]
Ok thanks a lot for looking into this.  
If the Stadia tile does have multiple layers, then I was probably [missinformed](https://github.com/greensopinion/flutter-vector-map-tiles/issues/50) in the issue discussion of the `vector_map_tiles` library.  

I used the default `process.lua` file and the 
[following](https://github.com/systemed/tilemaker/files/8750240/config-openmaptiles.json.zip) `config.json` file.

**Comment by systemed** [comment]
Layers are pretty fundamental to vector tiles so yes, I think there's a misunderstanding there:

https://github.com/mapbox/vector-tile-spec/tree/master/2.1#41-layers

I'd suggest you back out your changes to config.json; just use the default; then find exactly what error your renderer is reporting.
