### ISSUE TITLE
How to fill in missing ocean

### ISSUE THREAD

**Issue by ether6** [systemed/tilemaker#417]
Hey guys, first, thanks for the awesome tool. I was able to compile a global mbtiles file from OSM pieces from the https://download.geofabrik.de/ site -- took a couple of days, but 0 problems. Anyway, this isn't an issue with tilemaker, but it seems that we are missing a strip of ocean below Australia. Any ideas on a quick fix for this?

![Screen Shot 2022-07-07 at 2 40 44 PM](https://user-images.githubusercontent.com/8461462/177876532-9b5248c4-15e3-4100-a4eb-896c2366e133.png)

**Comment by systemed** [comment]
Hm, that's an odd place to see that. Could you confirm where you downloaded the coastline data from?

**Comment by ether6** [comment]
https://osmdata.openstreetmap.de/download/water-polygons-split-4326.zip

**Comment by ether6** [comment]
Re-ran the script with the whole planet to fix this issue.
