### ISSUE TITLE
Support shapefile polygons with multiple outer rings

### ISSUE THREAD

**Issue by fofanov** [systemed/tilemaker#42]
Firstly, thanks for making this great tool!

The [ESRI Shapefile Technical Description](https://www.esri.com/library/whitepapers/pdfs/shapefile.pdf) states that a shapefile polygon may contain multiple outer rings, in effect representing a multi-polygon geometry. 

Tilemaker currently assumes all shapefile polygons consist of only 1 outer ring. Therefore, any shapefile polygon containing multiple outer rings will fail Boost's geometry checks on ring orientation. An example of such a dataset where this occurs is [Ordnance Survey Boundary-Line](https://www.ordnancesurvey.co.uk/business-and-government/products/boundary-line.html).

I couldn't find anything in the boost geometry docs for organising a set of rings into multiple polygons. It appears that OGR has code for [handling this](http://www.gdal.org/classOGRGeometryFactory.html#afa3e76499553c3dc0a1621af98b88be6), but it doesn't use boost geometry and in any case is a bit too heavyweight a dependency to add just for this purpose. 

Therefore, it would be nice to add a bit of code to tilemaker to support this, possibly making some assumptions about the ring ordering/overlaps in the input so that heavy spatial calculations can be avoided when reading shapefiles - something along the lines of how OGR does it.

I'd be happy to make a PR and give this a try.

**Comment by systemed** [comment]
A PR would be great - please do!
