### ISSUE TITLE
Config files with street names

### ISSUE THREAD

**Issue by anuragvohraec** [systemed/tilemaker#422]
Hi every one,

If there predefined Configs files where the utput mbtiles do contans City name, street names.

**Comment by systemed** [comment]
The standard openmaptiles-compatible one does include that, but depending on the stylesheet you use, the density of streetnames will vary. Can you be more specific?

**Comment by anuragvohraec** [comment]
> The standard openmaptiles-compatible one does include that, but depending on the stylesheet you use, the density of streetnames will vary. Can you be more specific?

I used the standard configs the one we get when one unzips v2.2.0 for ubuntu from here : [Release v2.2.0](https://github.com/systemed/tilemaker/releases/tag/v2.2.0).

I used these commands `./build/tilemaker --input /path/to/specific.osm.pbf --output mymaps.mbtiles --process resources/process-openmaptiles.lua --config resources/config-openmaptiles.json`

I get no street names or building names, as one ususally sees on open street map.
![image](https://user-images.githubusercontent.com/53807480/181754862-7c97287e-cbd0-4ef8-b569-06918bc4e609.png)

**Comment by systemed** [comment]
Where is this?

**Comment by anuragvohraec** [comment]
> Where is this?
I download a very big file for India from GeoFabrik sepcifically maps for[ central India ](https://download.geofabrik.de/asia/india/central-zone.html)
And converted that files using tilemaker. The problem is every where on such tiles. Its usually should not be like that. I have seen them on Open street map these streets are properly tagged and visible on their map.

**Comment by systemed** [comment]
Ok, and could you confirm whether or not streetnames appear when you zoom in?

**Comment by anuragvohraec** [comment]
No Street name do not appears when I zoom in to any amount (even beyond 14)

**Comment by systemed** [comment]
Ok, and what stylesheet are you using?

**Comment by anuragvohraec** [comment]
I use tile server for getting tiles in browser.
Its says the basic style:
![image](https://user-images.githubusercontent.com/53807480/181759406-34333d8f-5a2f-409e-b754-a5a305dc12c7.png)

**Comment by systemed** [comment]
Ok.

The OpenMapTiles schema is not clear about what vector tile attribute is used for storing the name (as per https://github.com/openmaptiles/openmaptiles/issues/930).

You need to find out what attribute is being used by the style you've chosen. From https://github.com/klokantech/tileserver-gl-styles/blob/master/styles/basic-preview/style.json it looks like it is simply "name".

In tilemaker, then, you need to configure your style to write the "name" attribute. You can do this by changing line 12 of resources/process-openmaptiles.lua from

    preferred_language_attribute = "name:latin"

to

    preferred_language_attribute = "name"

**Comment by anuragvohraec** [comment]
The problem repeats.

Here are the steps to repdouce.
Unzip file: [data.zip](https://github.com/systemed/tilemaker/files/9220079/data.zip)
It contains a `ashta.osm.pbf` sample file I have used as test to create ashta.mbtiles

**Comment by anuragvohraec** [comment]
And then ran `tileserver-gl-light ashta.mbtiles`

**Comment by systemed** [comment]
Sorry, I don't have a node setup so I won't be able to run `tileserver-gl-light`.

**Comment by anuragvohraec** [comment]
> Sorry, I don't have a node setup so I won't be able to run `tileserver-gl-light`.

Which tile server do you use ?

**Comment by systemed** [comment]
I use https://github.com/systemed/mod_mbtiles but I don't think that'll help you here - it's the style that's the issue, not the tileserver.

If you can find out what name attribute is required by the style you're using, that will help. I can't really debug someone else's style I'm afraid.

**Comment by anuragvohraec** [comment]
Ok will try somethings on my own. Thank you for all your help. 
Cheers.

**Comment by systemed** [comment]
tilemaker just generates vector tiles with attributes written to them. It uses a Lua script to determine what attributes it writes.

The style is something you serve up from your tileserver to the client (probably Maplibre GL). tilemaker doesn't know anything about it.

This explains how it all fits together: https://github.com/systemed/tilemaker/blob/master/docs/VECTOR_TILES.md
