### ISSUE TITLE
Layers are merged?

### ISSUE THREAD

**Issue by lonewaffle** [systemed/tilemaker#425]
I'm certain that I'm just doing something wrong here. I'm trying to generate tiles to use with QGIS and, while I'm getting the output mbtiles that contains the data I want, all of the layers are merged together in QGIS, so I can't apply any meaningful styles to them. I'm using the included config-openmaptiles.json and process-openmaptiles.lua, btw.

When I look at the properties of the mbtiles inside of QGIS and go to Symbology, I only see 3 layers, Polygons, Points, and Lines. I was hoping to see separate layers for things like roads, waterways, etc. Also, I don't see any place names, road names, etc at all. 

What am I doing wrong?

**Comment by lonewaffle** [comment]
Also, since it might be relevant, I'm on macOS, using using release 2.2.0 with QGIS 3.26.1

I have no errors during the generation process. Here's the command I'm using:
`./build/tilemaker --input ~/Downloads/wyoming-latest.osm.pbf --output Wyoming.mbtiles --process ./resources/process-openmaptiles.lua --config ./build/config.json`

Here's the output of that command:
Layer place (z0-14)
Layer boundary (z0-14)
Layer poi (z12-14)
Layer poi_detail (z14-14) -> poi
Layer housenumber (z14-14)
Layer waterway (z8-14)
Layer waterway_detail (z12-14) -> waterway
Layer transportation (z4-14)
Layer transportation_name (z8-14)
Layer transportation_name_mid (z12-14) -> transportation_name
Layer transportation_name_detail (z14-14) -> transportation_name
Layer building (z13-14)
Layer water (z6-14)
Layer ocean (z0-14) -> water
Layer water_name (z14-14)
Layer water_name_detail (z14-14) -> water_name
Layer aeroway (z11-14)
Layer aerodrome_label (z10-14)
Layer park (z11-14)
Layer landuse (z4-14)
Layer urban_areas (z4-8) -> landuse
Layer landcover (z0-14)
Layer ice_shelf (z0-9) -> landcover
Layer glacier (z2-9) -> landcover
Layer mountain_peak (z11-14)
Bounding box -111.058, 40.9834, -103.941, 45.0195
Reading .shp ocean
Unable to open coastline/water_polygons.shp or coastline/water_polygons.SHP.
Reading .shp urban_areas
Unable to open landcover/ne_10m_urban_areas/ne_10m_urban_areas.shp or landcover/ne_10m_urban_areas/ne_10m_urban_areas.SHP.
Reading .shp ice_shelf
Unable to open landcover/ne_10m_antarctic_ice_shelves_polys/ne_10m_antarctic_ice_shelves_polys.shp or landcover/ne_10m_antarctic_ice_shelves_polys/ne_10m_antarctic_ice_shelves_polys.SHP.
Reading .shp glacier
Unable to open landcover/ne_10m_glaciated_areas/ne_10m_glaciated_areas.shp or landcover/ne_10m_glaciated_areas/ne_10m_glaciated_areas.SHP.
Sorting loaded shapes
Reading .pbf /Users/josh/Downloads/wyoming-latest.osm.pbf
Block 1043/1099 ways 0 relations 0
Sorting nodes
Block 1096/1099 ways 8000 relations 0
Sorting ways
Sorting generated geometriesions 2780
Stored 8373373 nodes, 17466 ways, 1520 relations
Shape points: 0, lines: 0, polygons: 0
Generated points: 34524, lines: 392586, polygons: 166163
Zoom level 14, writing tile 99665 of 99665
Filled the tileset with good things at Wyoming.mbtiles

Also, I did configure my language in the LUA by setting it to "en". Here's an example of my tiles:
![Screen Shot 2022-08-04 at 10 37 34 PM](https://user-images.githubusercontent.com/5062130/183002505-0206286e-1bcf-4fd9-938b-cded8394e59d.png)

And here's what I see when I want to try restyling them (so everything's not just one color):
![Screen Shot 2022-08-04 at 10 38 22 PM](https://user-images.githubusercontent.com/5062130/183002591-9fe4e141-e191-4143-975b-4094878c06d8.png)

**Comment by lonewaffle** [comment]
I'm guessing I can't really do what I'm wanting to do without using a server to handle the rendering. I'll just go that route.

**Comment by systemed** [comment]
tilemaker .mbtiles go into QGIS just fine. This is what I get if I do "Add Vector Layer" in QGIS and then select an .mbtiles file:

![Screenshot 2022-08-05 at 09 39 11](https://user-images.githubusercontent.com/694425/183038708-c64936c2-a693-47ed-a001-217148061c24.png)

If you're not seeing this, can you provide more detailed steps to reproduce, screenshots etc.?

**Comment by lonewaffle** [comment]
Thanks @systemed 
I can confirm that it works as you described when importing that way (though it takes a long time to scan the layers). I was just dragging the mbtiles file onto the workspace before without realizing the differences in how the data would be imported.
