### ISSUE TITLE
terminating with uncaught exception 

### ISSUE THREAD

**Issue by VincentBaillet** [systemed/tilemaker#426]
I'm using Tilemaker with great success since several months... I usually start from pbf dowloaded from geofabrik.de.

Therefore, I have a problem with one pbf, that I've created from several sources.
my command line is:
 tilemaker total.pbf  --output=world.mbtiles --bbox -160,-70,160,70 --config config-openmaptiles.json --process process-openmaptiles.lua

the result is :
...
...
_Sorting loaded shapes
Reading .pbf total.pbf
Block 0/3 ways 0 relations 0        
Sorting nodes
libc++abi: terminating with uncaught exception of type std::length_error: vector
Abort trap: 6_

there's certainly something wrong with my total.pbf, and at the end of the day the fault is certainly mine. but the error message gives me no clue about where to find my mistake.
Please note that this PBF is displayed flawlessly by QGIS and JOSM. A "data constitency" check with JOSM returns a "No problems found"

I'm working on a mac, but I've tried the same process on a PC  -> Tilemaker exits without any error message, even in verbose mode. 
I've attached the pbf and the json/lua files  [Archive.zip](https://github.com/systemed/tilemaker/files/9282652/Archive.zip)

any clue to solve this problem ????

**Comment by systemed** [comment]
Hm. Just off the top of my head - worth trying with `--skip-integrity`?

**Comment by VincentBaillet** [comment]
Thanks for the fast answer... :)     but same problem.:(

**Comment by systemed** [comment]
How did you create the PBF?

**Comment by VincentBaillet** [comment]
_How did you create the PBF?_
I've created it with JOSM ( loaded 5 different layers =>changed/added some tags => merged the layers => export to pbf )

**Comment by systemed** [comment]
It looks like you've got objects with negative IDs in there. When I put a bunch of debug statements in there it tells me that you have a relation of ID 18446744073709451134, which looks like a negative ID added to 2**64. tilemaker doesn't support negative IDs.

**Comment by VincentBaillet** [comment]
Bingo: you're right. in fact, most of the ids (if not all) are negative. 
it looks like JOSM is guilty...
So i've changed all the ids by hand... and this error disappeared. I will have to find another solution for future pbf creations.

Thank you very much for helping me resolve this problem. :)

**Comment by systemed** [comment]
No problem!
