### ISSUE TITLE
How to generate fonts?

### ISSUE THREAD

**Issue by tuupola** [systemed/tilemaker#429]
Not really issue on tilemaker but a question. Have you found a way to generate the fonts yourself?  

I know there is [openmaptiles/fonts](https://github.com/openmaptiles/fonts) but there is issues with installing [mapbox/fontnik](https://github.com/mapbox/fontnik) atleast on Fedora. Both mentioned projects have not had any activity for couple of years.

**Comment by systemed** [comment]
Yes, it's not easy. I run `genfontgl` (which is basically a wrapper around fontnik) on an Ubuntu VM; getting it to run on macOS proved challenging and I can imagine the same being true of Fedora.

**Comment by tuupola** [comment]
Yeah I was thinking about running a VM. Which version of Ubuntu you are running?

**Comment by systemed** [comment]
That particular one is on 16.04 and my notes say:

- Install nvm from https://github.com/nvm-sh/nvm
- `nvm install v6.17.1`
- `npm install fontnik`
- `npm install genfontgl`

Then to create a font:

`node /root/node_modules/genfontgl/index.js font.ttf output_location`
