### ISSUE TITLE
Does not generate tiles, gets stuck on one of the first few

### ISSUE THREAD

**Issue by Thomasssb1** [systemed/tilemaker#442]
I am trying to turn generate a .mbtiles file from Wales. I run the following, it does all of the steps before starting generating tiles fine but as soon as it reaches tile generation it only generates a single tile or two and ends.

`tilemaker --input wales-latest.osm.pbf --output wales.mbtiles --config config-openmaptiles.json --process process-openmaptiles.lua --store D:\mapstore`
The final line produced:
`Zoom level 3, writing tile 1 of 18402`

I tried with Great Britain as well, and it did the same thing but instead produced this final line:
`Zoom level 2, writing tile 2 of 192649`

The final .mbtiles produced is only 20KB large in both instances, clearly not containing the tiles.
I am running this on Windows 10 from the precompiled binaries supplied here https://github.com/systemed/tilemaker/releases (version 2.2.0).

**Comment by systemed** [comment]
The Windows build is currently broken. If you can build it yourself then #441 should fix it; if not then I’m planning to include it in 2.3 in a week or two.

**Comment by Thomasssb1** [comment]
Thanks, I built it myself and looked at that post. All works now, I got the mbtiles file. 👍
