### ISSUE TITLE
PMTiles support?

### ISSUE THREAD

**Issue by systemed** [systemed/tilemaker#445]
See spec at https://github.com/protomaps/PMTiles/blob/master/spec/v3/spec.md

It might be worth waiting until the spec settles down but this could be an interesting addition.

**Comment by bdon** [comment]
The headers at https://github.com/protomaps/PMTiles/tree/main/cpp are well tested right now, but intentionally designed so you handle the ordering and I/O yourself.

**Comment by donno** [comment]
PMTiles support was merged in #620.
