### ISSUE TITLE
Couldn't open .json config: resources/config-openmaptiles.lua

### ISSUE THREAD

**Issue by toqeer786** [systemed/tilemaker#449]
i am following the running.md file before this i had completed install.md steps for ubuntu now the issue is that whenever i run this command:
sudo tilemaker --input pakistan.osm.pbf \
>  --output pakistan.mbtiles \
>           --config resources/config-openmaptiles.lua \
>           --process resources/process-openmaptiles.lua
i found a following error 
"Couldn't open .json config: resources/config-openmaptiles.lua
"
i am new to this project  .kindly help me , where am doing wrong

**Comment by systemed** [comment]
Typo in the instructions - thank you for spotting that! It should be

`--config resources/config-openmaptiles.json`

i.e. .json not .lua.

**Comment by toqeer786** [comment]
> Typo in the instructions - thank you for spotting that! It should be
> 
> `--config resources/config-openmaptiles.json`
> 
> i.e. .json not .lua.

thank you so much !! and what about 

> --process resources/process-openmaptiles.lua is it changed to openmaptiles.json or remain same?
