### ISSUE TITLE
how to display map in english 

### ISSUE THREAD

**Issue by toqeer786** [systemed/tilemaker#451]
hi there !!
i have created mbtiles for pakistan and complete all my project but the issue is that i want to display my map in english language can anyone tell me how can i make it  i have read all the issues here and also try alot to make changes in way attribute ,prefered language but no result , i want to display the pakistan map with english labels .kindly help thanks!
![pakistan osm urde](https://user-images.githubusercontent.com/115454250/204978194-3aa99675-f487-4060-a407-3f4bdafcc903.png)

**Comment by systemed** [comment]
Have a look at the top of [process-openmaptiles.lua](https://github.com/systemed/tilemaker/blob/master/resources/process-openmaptiles.lua).

If you change `preferred_language=nil` to `preferred_language="en"`, then regenerate, you should get English names (where they exist in OSM!).

**Comment by toqeer786** [comment]
hii thank you soo much for your help .i had make changes in preferred_language="en" and then again i regenrate the mbtile but i have still previous result , is there any need to make changes in .lua fille?
