### ISSUE TITLE
Fix tilemaker.org ?

### ISSUE THREAD

**Issue by vtuz** [systemed/tilemaker#453]
Hi guys, would you fix [tilemaker.org](https://tilemaker.org/) 

I just generated the tiles using tilemaker and would like to compare with real example to check if I did everything correct.

And thanks for nice, extremely fast tile renderer.

**Comment by typebrook** [comment]
Any issue on this site? I didn't see anything wrong
![Uploading Screenshot_2023-02-23-11-02-52_1920x1080.png…]()

**Comment by vtuz** [comment]
Yes, it works now. Thanks!
