### ISSUE TITLE
terminate called after throwing an instance of 'std::runtime_error'   what():  unable to open database file Aborted

### ISSUE THREAD

**Issue by satya-auti** [systemed/tilemaker#456]
```
_terminate called after throwing an instance of 'std::runtime_error'
  what():  unable to open database file
Aborted_
```

I have used  different input files but still facing same issue.

tilemaker --input raw_data/pnq_ht.osm.pbf --bbox 73.5658,18.404,74.2222,18.7081 --output mbtiles/planet.mbtiles --process resources/process.lua --config resources/config.json --store tempStore

**Comment by systemed** [comment]
Have you created the `mbtiles/` directory, and does you have write permission to it?

**Comment by satya-auti** [comment]
It's resolve now

**Comment by systemed** [comment]
Great!

**Comment by satya-auti** [comment]
@systemed I'm facing issue while rendering relation building:part tag on map.

I have added the below code for same.

`function relation_scan_function(relation)
    if relation:Find("type") == "multipolygon" or relation:Find("type") == "building" then
        relation:Accept()        
    end
end`


`while true do
        local rel = way:NextRelation()
        if not rel then
            break 
        end
        -- print ("Part of route "..way:FindInRelation("ref"))
        part = way:FindInRelation("building:part")
        -- part = way:FindInRelation("ref")

        if part == "yes" then
            way:Layer("building",false)
            relation:Attribute("building:part",part)
        else
            way:Attribute("building:part","empty")
        end

    end`

**Comment by systemed** [comment]
I don't know anything about building relations I'm afraid, but just to check - the second half of your code above is in `way_function`, yes?

**Comment by satya-auti** [comment]
yes
