### ISSUE TITLE
command failed with:Filled the tileset with good things at /home/**.mbtiles

### ISSUE THREAD

**Issue by supperlitt** [systemed/tilemaker#462]
Filled the tileset with good things at /home/south.mbtiles
the file south.mbtiles is created but ,when is run

docker run --rm -it -v $(pwd):/data -p 8080:8080 maptiler/tileserver-gl --mbtiles south.mbtiles

the map is not have any text (place name, build name, and any other name).

**Comment by systemed** [comment]
That isn’t a failure, that’s the correct exit message, and it sounds like the tiles have been generated. 

You need to check that the attribute used for writing names is the same one your stylesheet is expecting. See the comments at the top of https://github.com/systemed/tilemaker/blob/master/resources/process-openmaptiles.lua - if your stylesheet expects something different from ‘name:latin’ then you’ll need to change that line.

**Comment by supperlitt** [comment]
thanks for help.
