### ISSUE TITLE
include_ids in the config file doesn't set the original OpenStreetMap IDs

### ISSUE THREAD

**Issue by wieringen** [systemed/tilemaker#466]
Enabling include_ids in my tilemaker configuration will result in Ids being added, but the IDs seem to be randomly generated.

I noticed that during the Lua processing phase, an extra ID is generated. Could it be that the wrong ID is outputted to the tile objects? 
[https://github.com/systemed/tilemaker/blob/3a4239f00ac4333af84aae9250a214a175403945/src/osm_lua_processing.cpp#L542](https://github.com/systemed/tilemaker/blob/3a4239f00ac4333af84aae9250a214a175403945/src/osm_lua_processing.cpp#L542)

**Comment by systemed** [comment]
If you `AND` the resulting ids with 0x7fffffffff, does the result seem right?

**Comment by pa5cal** [comment]
Yes, the result seems right w/ `id & 0x7fffffff`

Thanks.

**Comment by systemed** [comment]
Fixed in #470. Thanks for spotting.

**Comment by wieringen** [comment]
Thanks!  :)
