### ISSUE TITLE
Is there anyway to add center for multipolygon

### ISSUE THREAD

**Issue by satya-auti** [systemed/tilemaker#467]
we can add center point for polygon using inbuilt function (LayerAsCentroid).
Is there any inbuilt function for Multipolygon?

**Comment by systemed** [comment]
This should just work as normal with multipolygons, I think - does it not work for you?

**Comment by satya-auti** [comment]
<img width="922" alt="image" src="https://user-images.githubusercontent.com/103890980/222053644-5116bf9d-1042-4d66-b320-be2cd6a39bb3.png">


center point of the both polygon is between them. Is there anyway to set the individual point to center of the both polygon?

**Comment by systemed** [comment]
Ah, I see what you mean. Currently tilemaker uses boost::geometry's centroid algorithm, which as you've seen chooses the single centroid of the assembled geometries as a whole. I think what you're looking for is something that writes several centroids, one for each constituent polygon. There's no way to do that at present but it might be an interesting thing to introduce.

**Comment by systemed** [comment]
Fixed in v3.
