### ISSUE TITLE
lost the ocean

### ISSUE THREAD

**Issue by vutrongnghiahaui** [systemed/tilemaker#468]
I have build code and install on ubuntu 20.04 and use Vietnam map from OpenStreetMap Data geofabrik repository for testing. When creating .mbtiles file and using TileServer GL server to display map, the ocean is lost clearly woven. Looking forward to everyone's contributions.
![Screenshot from 2023-03-01 13-18-12](https://user-images.githubusercontent.com/57761482/222060191-660f3926-6099-4f6f-af99-57f577ac60df.png)
The config and process files I leave the default of the source code.

**Comment by vutrongnghiahaui** [comment]
I tried adding a coastline/water_polygons.shp file like according to config-openmaptiles.json all maps are ocean blue
![Screenshot from 2023-03-01 16-07-20](https://user-images.githubusercontent.com/57761482/222094026-2065e4c9-17d4-4fbe-a76d-a025d34e75ad.png)
not sure if this is a direction

**Comment by ReGameView** [comment]
Hello, I faced the same problem, I really lost 3 days until I realized what the snag was, but I used Docker, and it helped me that I completely cleared the container (cache, volume, etc.)

**Comment by BishopOfTurkey** [comment]
From the README

> If you want to include sea tiles, then create a directory called coastline in the same place you're running tilemaker from, and then save the files from https://osmdata.openstreetmap.de/download/water-polygons-split-4326.zip in it, such that tilemaker can find a file at coastline/water_polygons.shp.

You'll probably need this to get what you're looking for :)
