### ISSUE TITLE
Mbtiles file generated by Tilemaker when used with tileserver-gl not showing labels

### ISSUE THREAD

**Issue by AmirOsman2020** [systemed/tilemaker#477]
Hello, I recently installed tileserver-gl and used .mbtiles data source that I downloaded from maptiler.com the server worked perfectly but I used the free version which is not updated, so, I downloaded .osm.pbf data from https://download.geofabrik.de/ and then I installed tilemaker and generated the mbtiles file successfully however when I used it with tileserver-gl the map is working but the labels don't show up, I went back to check the file I downloaded from maptiler.com and the labels showed up, so the problem is with the file I generated from tilemaker, any help?

**Comment by systemed** [comment]
You need to make sure that the attribute used to write the placenames is the same one that your style is expecting. OpenMapTiles styles are inconsistent on this point.

In resources/process-openmaptiles.lua, look at the first four commented lines labelled "Alter these lines to control which languages are written for place/streetnames". In particular look at

````lua
-- This is written into the following vector tile attribute (usually "name:latin"):
preferred_language_attribute = "name:latin"
````

You may need to change "name:latin" to something else, maybe "name". This will be in the JSON for whatever style you're using. See #285.

**Comment by AmirOsman2020** [comment]
> 

Yes, I already did that, labels still not showing up, Is am using the default configuration file config.json when generating the .mbtiles file using tilemaker do dose it include labels by default or do I have to modify it to add labels, this is the config file:


{
	"layers": {
		"place":            { "minzoom":  0, "maxzoom": 14 },
		"boundary":         { "minzoom":  0, "maxzoom": 14, "simplify_below": 12, "simplify_level": 0.0003, "simplify_ratio": 2 },

		"poi":              { "minzoom": 12, "maxzoom": 14 },
		"poi_detail":       { "minzoom": 14, "maxzoom": 14, "write_to": "poi"},

		"housenumber":      { "minzoom": 14, "maxzoom": 14 },

		"waterway":         { "minzoom":  8,  "maxzoom": 14, "simplify_below": 12, "simplify_level": 0.0003, "simplify_ratio": 2 },
		"waterway_detail":  { "minzoom": 12,  "maxzoom": 14, "write_to": "waterway" },

		"transportation":             { "minzoom": 4,  "maxzoom": 14, "simplify_below": 13, "simplify_level": 0.0003 },
		"transportation_name":        { "minzoom": 8,  "maxzoom": 14 },
		"transportation_name_mid":    { "minzoom": 12, "maxzoom": 14, "write_to": "transportation_name" },
		"transportation_name_detail": { "minzoom": 14, "maxzoom": 14, "write_to": "transportation_name" },

		"building":          { "minzoom": 13, "maxzoom": 14 },

		"water":             { "minzoom": 6,  "maxzoom": 14, "simplify_below": 12, "simplify_level": 0.0003, "simplify_ratio": 2},
		"ocean":             { "minzoom": 0,  "maxzoom": 14, "source": "coastline/water_polygons.shp", "simplify_below": 13, "simplify_level": 0.0001, "simplify_ratio": 2, "write_to": "water", "index": true },
		"water_name":        { "minzoom": 14, "maxzoom": 14 },
		"water_name_detail": { "minzoom": 14, "maxzoom": 14, "write_to": "water_name" },

		"aeroway":           { "minzoom": 11, "maxzoom": 14 },
		"aerodrome_label":   { "minzoom": 10, "maxzoom": 14 },
		"park":              { "minzoom": 11, "maxzoom": 14 },
		"landuse":           { "minzoom":  4, "maxzoom": 14, "simplify_below": 13, "simplify_level": 0.0003, "simplify_ratio": 2 },
		"urban_areas":       { "minzoom":  4, "maxzoom":  8, "source": "landcover/ne_10m_urban_areas/ne_10m_urban_areas.shp", "source_columns": ["featurecla"], "simplify_below": 7, "simplify_level": 0.0003, "simplify_ratio": 2, "write_to": "landuse" },
		"landcover":         { "minzoom":  0, "maxzoom": 14, "simplify_below": 13, "simplify_level": 0.0003, "simplify_ratio": 2 },
		"ice_shelf":         { "minzoom":  0, "maxzoom":  9, "source": "landcover/ne_10m_antarctic_ice_shelves_polys/ne_10m_antarctic_ice_shelves_polys.shp", "source_columns": ["featurecla"], "simplify_below": 13, "simplify_level": 0.0005, "write_to": "landcover" },
		"glacier":           { "minzoom":  2, "maxzoom":  9, "source": "landcover/ne_10m_glaciated_areas/ne_10m_glaciated_areas.shp", "source_columns": ["featurecla"], "simplify_below": 13, "simplify_level": 0.0005, "write_to": "landcover" },
		"mountain_peak":     { "minzoom": 11, "maxzoom": 14 }
	},
	"settings": {
		"minzoom": 0,
		"maxzoom": 14,
		"basezoom": 14,
		"include_ids": false,
		"combine_below": 14,
		"name": "Tilemaker to OpenMapTiles schema",
		"version": "3.0",
		"description": "Tile config based on OpenMapTiles schema",
		"compress": "none",
		"filemetadata": {
			"tilejson": "2.0.0", 
			"scheme": "xyz", 
			"type": "baselayer", 
			"format": "pbf", 
            "tiles": ["https://example.com/liechtenstein/{z}/{x}/{y}.pbf"]
		}
	}
}

**Comment by AmirOsman2020** [comment]
Sorry, I miss read your solution, I went back and modified the process-openmaptiles.lua file and now it's working perfectly, Thanks very much.
