### ISSUE TITLE
Missing methods in processor during import

### ISSUE THREAD

**Issue by svvac** [systemed/tilemaker#478]
Using the the openmaptiles default [configuration][config.json] and [processor][process.lua], against the [Europe extract][geofabrik-eu] from Geofabrik the generation process fails due to missing methods:

```
config/tilemaker.process.lua:253: attempt to call method 'NextRelation' (a nil value)
config/tilemaker.process.lua:722: attempt to call method 'ZOrder' (a nil value)
```

<details><summary>Environment</summary>

- Ubuntu 22
- Tilemaker v2.3.0 (using prebuilt binary from releases)

</details>

[config.json]: https://github.com/systemed/tilemaker/blob/a5d7def9f49abe4689004655ca382196cf75c3db/resources/config-openmaptiles.json
[process.lua]: https://github.com/systemed/tilemaker/blob/a5d7def9f49abe4689004655ca382196cf75c3db/resources/process-openmaptiles.lua
[geofabrik-eu]: https://download.geofabrik.de/europe.html

**Comment by systemed** [comment]
I haven't been able to reproduce this - Europe processes fine on my machine (also Ubuntu). It's not an error I would expect to see. I use a source build but will try with the binary to see if it's specific to that.

**Comment by svvac** [comment]
Indeed, I had to use another computer for the import suing the same data, and I could not reproduce it anymore even though it was quite systematic previously.

This does seem like a problem on my end, probably relating to corrupt/malformed data.

Sorry for the noise.
