### ISSUE TITLE
Changing BIND IP and PORT

### ISSUE THREAD

**Issue by sledzik1984** [systemed/tilemaker#481]
Is there any possibility to change ip addres and port that ruby server uses?

**Comment by systemed** [comment]
Yes, you can edit the options that you send to `Rackup::Handler::WEBrick.run(app)` at the end of the file.

For example:

````ruby
    Rack::Handler::WEBrick.run(app, { Host: "192.168.0.100" })
````

Available options are as per https://docs.ruby-lang.org/en/2.7.0/WEBrick/HTTPServer.html I guess.

**Comment by SomeoneElseOSM** [comment]
FWIW what worked for me (Debian 12, and presumably later versions of many things) was:

    puts "Starting local server"
    require 'rackup'
    # require 'rack'
    
    server = MapServer.new(ARGV[0],0)
    app = Proc.new { |env| server.call(env) }
    # Rackup::Handler::WEBrick.run(app)
    options = { Host: "0.0.0.0" }
    Rackup::Handler::WEBrick.run(app, **options )

(replace 0.0.0.0 if you just want to server on one local address of several)
