### ISSUE TITLE
Docs: landcover shapefiles

### ISSUE THREAD

**Issue by langbein-daniel** [systemed/tilemaker#484]
In the [README.md](https://github.com/systemed/tilemaker/blob/master/README.md), there is information about the coastline shapefile and why one might need it.

But there is currently no information about landcover shapefiles.

When running `tilemaker` I have these lines in my output:

```
Reading .shp urban_areas
Unable to open landcover/ne_10m_urban_areas/ne_10m_urban_areas.shp or landcover/ne_10m_urban_areas/ne_10m_urban_areas.SHP.
Reading .shp ice_shelf
Unable to open landcover/ne_10m_antarctic_ice_shelves_polys/ne_10m_antarctic_ice_shelves_polys.shp or landcover/ne_10m_antarctic_ice_shelves_polys/ne_10m_antarctic_ice_shelves_polys.SHP.
Reading .shp glacier
Unable to open landcover/ne_10m_glaciated_areas/ne_10m_glaciated_areas.shp or landcover/ne_10m_glaciated_areas/ne_10m_glaciated_areas.SHP.
```

Does `tilemaker` produce different tiles if landcover shapefiles are available? Or does this depend on the used style such that it is not always necessary?

And where can I get those files from, is it e.g. https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_urban_areas.zip?

**Comment by dieterdreist** [comment]
sent from a phone

> On 25 Mar 2023, at 11:52, Daniel Langbein ***@***.***> wrote:
> 
> Does tilemaker produce different tiles if landcover shapefiles are available? Or does this depend on the used style such that it is not always necessary?
> 


depending on your style this data is mixed with OpenStreetMap data and used for some zoom levels 

> And where can I get those files from, is it e.g. https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_urban_areas.zip?
> 


yes, these are files from natural earth data

**Comment by systemed** [comment]
Fixed in v3 - thanks for flagging.
