### ISSUE TITLE
release 2.4.0 version not set

### ISSUE THREAD

**Issue by dieterdreist** [systemed/tilemaker#487]
in the release 2.4.0 when running `tilemaker --help` it says: 
```
tilemaker (version not set)
Convert OpenStreetMap .pbf files into vector tiles
....
```

**Comment by systemed** [comment]
Yeah, it's done that before. I've never quite figured out what magic set of incantations is needed to get the github binaries to do it in the right order. Not really a big deal tbh.

**Comment by dieterdreist** [comment]
sure, no big deal, I just saw it "in time" and thought maybe you forgot to set a string somewhere...
