### ISSUE TITLE
Get way's center node

### ISSUE THREAD

**Issue by WingmanImd** [systemed/tilemaker#489]
Hey, is there any way to get a way's center node in way_function?
My ccp knowledge is pretty much nonexistent and I would really need this feature.
I tried using LayerAsCentroid but I don't think that is supposed to be used as I require as the point in not accurate.

Thanks for your time and awesome project!

**Comment by systemed** [comment]
LayerAsCentroid will write out a point as the centroid of the way - it uses Boost.Geometry's centroid calculation, [as described here](https://www.boost.org/doc/libs/1_75_0/libs/geometry/doc/html/geometry/reference/algorithms/centroid/centroid_2.html). When you say the point is "not accurate" what do you mean?

**Comment by WingmanImd** [comment]
I used the wrong term. I want to display a symbol on top of a way, right on top of the middle node of it, specifically I want to show a hiking trail's osmc:symbol. When using way:LayerAsCentroid i will not add a point on on top of the way when that way is not straight.

The red squares in the image bellow are the way:LayerAsCentroid result.

Hope it makes sense


![Screenshot from 2023-04-16 22-41-31](https://user-images.githubusercontent.com/16722652/232338031-dd1bf181-e099-4145-9d9d-b30c6206a290.png)

**Comment by WingmanImd** [comment]
I just realised that what I want is to mostly duplicate the style for a road_shield.  So basically:
`{
      "id": "highway-marked-hiking-trail-symbols",
      "type": "symbol",
      "source": "openmaptiles",
      "source-layer": "marked_trail",
      "minzoom": 9,
      "layout": {
        "icon-image": "railway_11",
        "icon-rotation-alignment": "viewport",
        "icon-size": 1,
        "symbol-placement": {"base": 1, "stops": [[10, "point"], [11, "line"]]},
        "symbol-spacing": 75,
        "text-field": "{osmc:symbol}",
        "text-font": ["KlokanTech Noto Sans Regular"],
        "text-rotation-alignment": "viewport",
        "text-size": 10
      },
      "paint": {}
    },`

But obviously with icon-image replaced with the proper symbol.

Thanks again for the awesome project!
