### ISSUE TITLE
Tiles are missing when generating tiles for: israel-and-palestine-latest.osm.pbf

### ISSUE THREAD

**Issue by adibarda** [systemed/tilemaker#491]
Hello,

**Question**
=======
Does tile's row / column depends on the bounding box setup?
My Android MapBox client requests for z/x/y tiles which doesn't exists in the .mbtiles DB created by TileMaker. 

we are talking about this map:
==============================
https://download.geofabrik.de/asia/israel-and-palestine-latest.osm.pbf

for reference, you can see it live at:
======================================
https://israelhiking.osm.org.il/map/13.48/31.7403/35.0630

Here is the command line for generating the tiles:
===================================================
tilemaker --verbose --input israel-and-palestine-latest.osm.pbf --output ihm.mbtiles --process res/process.lua --config res/config.json 
pause

**Problem:**
========
the generated tiles DB (ihm.mbtiles) doesn't contain all the tiles for the map for example tile: 12/2445/1663 (and a lot more) is missing in the .mbtiles DB

What can be tuned in the config in order to generate the tiles in different X/Y?

Thank You.
Adi

**Comment by systemed** [comment]
When I browse that URL, one of the tiles requested, returned, and rendered is https://israelhiking.osm.org.il/vector/data/IHM/12/2445/1663.pbf - am I missing something?

You presumably realise that the internal `tile_row` value within the mbtiles is the TMS standard, i.e. it's inverted from the Y value in the URL. So if you're just searching the mbtiles database for the Z/X/Y value, you won't find it. You can convert from one to the other with `y = ((1 << z) - y - 1)`.

**Comment by adibarda** [comment]
> am I missing something

I put this online map for reference to demonstrate an application that has managed to produce the correct tiles.

> y = ((1 << z) - y - 1)
Sorry didn't know about that conversion so I'm going to try it right away! 
Thank you so much!
