### ISSUE TITLE
Ocean Tile Missing | TileMaker Intermittent Bug

### ISSUE THREAD

**Issue by koufopoulosf** [systemed/tilemaker#495]
Hello,

First of all I would like to thank you very much for this wonderful tool. I love it! However ...

I am making this issue as I have noticed that tilemaker faces some issues with ocean tiles. In particular, I have created the map of Greece, using the official Geofabrik file ([greece-latest.osm.pbf](https://download.geofabrik.de/europe/greece.html)).

Moreover, I proceeded to create an MBTiles file, using the Shortbread Schema. For that process, I used both of these 2 repositories:

1. [geofabrik/shortbread-tilemaker](https://github.com/geofabrik/shortbread-tilemaker)
2. [versatiles-org/shortbread-tilemaker](https://github.com/versatiles-org/shortbread-tilemaker)

In the first case, the map had no ocean at all:

![image](https://github.com/systemed/tilemaker/assets/66564413/e42ab56f-db52-4529-9201-c75cb954a99d)

While in the second case, the map had the ocean layer, however with a partially missing tile:

![image](https://github.com/systemed/tilemaker/assets/66564413/28c7ef66-4d73-4659-8bc4-cc842c2bde09)
[
At this point, let me mention that even if I were to rebuild the vector tiles, the result would remain the same.](https://tiles.versatiles.org/#8.22/37.787/24.45)

I have proceeded to make an issue on both repositories:

On Geofabrik: https://github.com/geofabrik/shortbread-tilemaker/issues/18
On VersaTiles: https://github.com/versatiles-org/shortbread-tilemaker/issues/3

From VersaTiles, @yetzt noticed more issues related to my issue here that are coming from the tilemaker repository:
[systemed/tilemaker/issues/417](https://github.com/systemed/tilemaker/issues/417)
[systemed/tilemaker/issues/401](https://github.com/systemed/tilemaker/issues/401)

@systemed Are there any plans on fixing this major issue?

This issue prevents people from using this tool and I would very much appreciate if you could take action on this matter and solve it.

Thank you very much for your valuable time and I look forward to your response.

Best Regards,

koufopoulosf

**Comment by systemed** [comment]
Could you confirm the _exact_ steps to reproduce - e.g.

1. download greece-latest.osm.pbf from https://download.friendlyosmcompany.com/greece/extracts/
2. use fresh install of tilemaker (built from source) on Ubuntu 22.04
3. download coastline files from https://osmdata.somewhereorother.com/ and place in the `coastline/` directory
4. run tilemaker with the following command line: `tilemaker --input greece-latest.osm.pbf --output greece.mbtiles --process etc. etc.`
5. view created mbtiles with (whatever you're using)
6. etc.

> major issue
> This issue prevents people from using this tool

Please don't put judgemental comments/assumptions in github issues, just keep it factual and dispassionate. And please don't bomb my private email with followups, it won't get your issue fixed any faster.

**Comment by yetzt** [comment]
water polygons should be these:

https://github.com/geofabrik/shortbread-tilemaker/blob/main/get-shapefiles.sh#L25-L26

**Comment by koufopoulosf** [comment]
I tried to reproduce the issue on a new linux server, however the issue just disappeared. On the previous linux server I had installed different versions of libraries, so I suppose something made a conflict when building tilemaker fom source? I really do not know.

Furthermore, I am sorry if you took my comment personally, I did not mean to hurt your feelings.

Last, I just sent you a single polite email in case you could had a look, I don't understand how the word "bomb" came from.

In any way, I would like to thank you very much for your valuable reply and I would recommend as well for people facing this issue to try a fresh installation on a different server in case of a library/package conflict creating this issue.
