### ISSUE TITLE
merge tiles

### ISSUE THREAD

**Issue by koufopoulosf** [systemed/tilemaker#496]
Hello @systemed,

I am making this issue as I would like to ask your valuable opinion, on which is the best way to merge 2 osm.pbf or mbtiles files. I know that tilemaker has the --merge functionality, however when I try for 2 different mbtiles files, I get this: ```Can't read shapefiles unless a bounding box is provided.```

So I am using the Osmosis tool for this conversion:
```osmosis --read-pbf file="file1.osm.pbf" --read-pbf file="file2.osm.pbf" --merge --write-pbf file="merged.osm.pbf"```

and then use the tilemaker to convert that particular merged.osm.pbf file to an MBTiles file.

So my question is, would you recommend to merge 2 osm.pbf files or 2 mbtiles files into 1?
And if so, which process would you suggest as the most robust one? Do you approve the Osmosis method or there are more robust ones?

Thank you very much for your valuable time.

**Comment by systemed** [comment]
> however when I try for 2 different mbtiles files, I get this: Can't read shapefiles unless a bounding box is provided.

Can you paste the command lines you're using when you try this?

(I have no experience with Osmosis but have used `osmium merge` for this kind of thing.)

**Comment by koufopoulosf** [comment]
```tilemaker --config config.json --process process.lua --input data/greece-latest.osm.pbf --output data/greece.mbtiles```

```tilemaker --config config.json --process process.lua --input data/cyprus-latest.osm.pbf --output data/cyprus.mbtiles```

And then:

```
tilemaker --config config.json --process process.lua --input data/greece.mbtiles --merge data/cyprus.mbtiles --output data/merged.mbtiles
--merge specified but .mbtiles file doesn't already exist, ignoring
Layer place_labels (z3-14)
Layer boundaries (z0-14)
Layer boundary_labels (z2-14)
Layer addresses (z14-14)
Layer water_lines (z4-14)
Layer water_lines_labels (z4-14)
Layer dam_lines (z12-14)
Layer dam_polygons (z12-14)
Layer pier_lines (z12-14)
Layer pier_polygons (z12-14)
Layer bridges (z12-14)
Layer street_polygons (z11-14)
Layer streets_polygons_labels (z14-14)
Layer ferries (z8-14)
Layer streets (z14-14)
Layer streets_med (z11-13) -> streets
Layer streets_low (z5-10) -> streets
Layer street_labels (z10-14)
Layer street_labels_points (z12-14)
Layer aerialways (z12-14)
Layer public_transport (z11-14)
Layer buildings (z14-14)
Layer water_polygons (z4-14)
Layer ocean (z8-14)
Layer ocean-low (z0-7) -> ocean
Layer water_polygons_labels (z14-14)
Layer land (z7-14)
Layer sites (z14-14)
Layer pois (z14-14)
Can't read shapefiles unless a bounding box is provided.
```

**Comment by systemed** [comment]
Ok, that's not how it works. You need to do this:

````
tilemaker --config config.json --process process.lua --input data/greece-latest.osm.pbf --output data/output.mbtiles
tilemaker --config config.json --process process.lua --input data/cyprus-latest.osm.pbf --merge --output data/output.mbtiles
````

See "Merging" in RUNNING.md.

**Comment by koufopoulosf** [comment]
@systemed by the way, I tried to merge these 2 countries, however only the first input country (greece-latest.osm.pbf) appears on the map. Maybe the merge has to do with "updating" the first map and not with displaying both countries?
