### ISSUE TITLE
Scheme setting is ignored when creating mbtiles

### ISSUE THREAD

**Issue by Emptyless** [systemed/tilemaker#498]
In the `config-openmaptiles.json` file, the XYZ scheme is referenced. Tilemaker however uses TMS. Is this (or should it be) a configurable option? 

https://github.com/systemed/tilemaker/blob/c6ae3cd68fdf3c090fcfce9fe6c4fe68e912ec03/resources/config-openmaptiles.json#LL48C13-L48C13

Related issues #8 and #491 show similar confusion in interpreting the Z/X/Y endpoint.

**Comment by pnorman** [comment]
mbtiles are always TMS numbered. I don't see any confusion about that.

If someone writes code to respond to xyz requests they have to do some basic math.

**Comment by Emptyless** [comment]
While it adheres to the specification, it does strike me as odd that there is no mention that the projection used is deprecated and does not follow the OSM standard pseudo mercator. The ruby example server implements the `y` to `y_tms` mapping, why not add a note in the readme?

**Comment by systemed** [comment]
I don't think the TMS format is "deprecated", is it? It's just that .mbtiles uses one thing and the OSM tileservers use something else - neither is right or wrong.

> why not add a note in the readme?

If we explained absolutely everything that people could potentially get confused by in the readme it would be about 50000 lines long. :) But it could make a FAQ, I guess (FSVO of "frequently").
