### ISSUE TITLE
lua error kaguya::LuaTypeMismatch

### ISSUE THREAD

**Issue by Ajiro3** [systemed/tilemaker#501]
Hi,
I want to pick up "roads" from OSM file.
So, I put a lua script shown in CONFIGURATION.md with --process option.
function way_function(way)
  local highway = way:Find("highway")
  if highway~="" then
    way:Layer("roads", false)
    way:Attribute("name", way:Find("name"))
    way:Attribute("type", highway)
  end
end

tilemaker outputs as follows;
lua runtime error: type mismatch
terminate called after throwing an instance of 'kaguya::LuaTypeMismatch'
  what():  type mismatch!!

Will you kindly advice me to solve this issue?
Thank you,

**Comment by Ajiro3** [comment]
I solved this issue by myself.

**Comment by ginnyTheCat** [comment]
Do you remember how you solved it back then?

**Comment by Ajiro3** [comment]
Sorry, my reply is not suitable for this issue.
I don' have any progress for this issue.

**Comment by Ajiro3** [comment]
No, I did't try. 
Now I am using tippecanoe instead of tilemake.
