### ISSUE TITLE
how to set make "CONFIG=-DFLOAT_Z_ORDER" under docker environment?

### ISSUE THREAD

**Issue by geographerwang** [systemed/tilemaker#515]
under docker environment,how to use tilemaker。 it has errors like this
![image](https://github.com/systemed/tilemaker/assets/12079968/a7e6b37c-f1c9-44c8-81b9-c1295440dca1)

i have tried as follows:
![image](https://github.com/systemed/tilemaker/assets/12079968/5cf51159-9fec-40b2-ad94-027ed5cc89a3)
![image](https://github.com/systemed/tilemaker/assets/12079968/e3cf20de-b424-47e4-b222-dbec92b825e5)

**Comment by systemed** [comment]
This is no longer needed in v3 as it supports float z-order by default.
