### ISSUE TITLE
mbtiles from tilemaker not working in Opencpn

### ISSUE THREAD

**Issue by mrbc42** [systemed/tilemaker#521]
I successfully used Tilemaker to extract some coastline from an "osm.pbf" file and loaded it into Opencpn.  All I get is a border outline of the map area without any detail. Searching through some forums, it looks like Opencpn requires the scheme "tms" instead of "xyz" does Tilemaker support this?  I couldn't find any reference in the docs.  It also looks like Opencpn requires an image in the "blob" "tile_data" column of the DB rather than Binary.

I have loaded the mbtiles DB into DBbrowser and all the data is there.

As this mbtiles thing is completely new to me, I dont know if I am conveying the issue correctly but as far as I can tell, there are only windows tools available to create mbtiles for Opencpn and I am a 100% Linux user so trying to find a native solution and I was able to get Tilemaker working easily with the above caveats.

any assistance or comments to point me in the right direction would be greatly appreciated as to whether I can use Tilemaker for this purpose.

[Opencpn](https://opencpn.org/) - Boat Navigation / charts etc
[Chart formats](https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:charts:chart_formats)

thanks,

**Comment by pnorman** [comment]
mbtiles is always stored with tms coordinates, not xyz.

**Comment by systemed** [comment]
An .mbtiles file can contain either raster map tiles or vector map tiles. tilemaker only makes vector map tiles. OpenCPN requires raster map tiles. I'm afraid tilemaker won't be suitable for this purpose.
