### ISSUE TITLE
v2.4.0:tilemaker-ubuntu-22.04.zip:Could not find node with id

### ISSUE THREAD

**Issue by alx696** [systemed/tilemaker#524]
osm.pbf from https://download.openstreetmap.fr/extracts/asia/china.osm.pbf can not work:

```
$ ./tilemaker --input /home/l/test/china.osm.pbf --output /home/l/test/china.mbtiles
Layer waterway (z11-14)
Layer transportation (z12-14)
Layer building (z14-14)
Layer poi (z13-14)
Sorting loaded shapes
Reading .pbf /home/l/test/china.osm.pbf
Block 19668/21175 ways 0 relations 0        
Sorting nodes
terminate called after throwing an instance of 'std::out_of_range'
  what():  Could not find node with id 359922889
已放弃 (核心已转储)
```

**Comment by systemed** [comment]
If you try to process a .pbf where some of the nodes are missing from the ways, tilemaker will produce this error. Some download sites don't provide this referential integrity. You can use the `--skip-integrity` switch to get round this.

**Comment by alx696** [comment]
Thanks! I will try later.
