### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by longlostbro** [systemed/tilemaker#53]
Does this or will this support Windows OS?

**Comment by systemed** [comment]
#24 made it compile under VS2015, and should still work. I don't have any experience with Windows myself I'm afraid, but if you try it and it doesn't compile, do post an issue here and hopefully someone can assist.

**Comment by longlostbro** [comment]
Could you add the sln?

**Comment by systemed** [comment]
I can't add an .sln file because I don't have a Windows computer or any knowledge as to how to program one.

**Comment by longlostbro** [comment]
ok sounds good. I'll see if I can get it to work. Thank you.
