### ISSUE TITLE
luabind error when running

### ISSUE THREAD

**Issue by pnorman** [systemed/tilemaker#55]
On Debian testing I get this error message

```
pnorman@pippin:~/osm/tilemaker$ ./tilemaker ~/osm/planet/british-columbia-161023.osm.pbf --output=tiles/
terminate called after throwing an instance of 'std::runtime_error'
  what():  luabind::open() must be called with the main thread lua_State*
Aborted
```

luabind installed is 0.9.1+dfsg-11

**Comment by pnorman** [comment]
boost is 1.61.07, lua5.1 is installed, so is 5.2. It looks like luabind is built against lua5.2

**Comment by pnorman** [comment]
Confirmed, edited the makefile to use Lua5.2 and it works. Not sure what the best solution is.

**Comment by systemed** [comment]
Luabind is a bit of a trainwreck and I'd like to remove tilemaker's dependency on it, either to use luwra or sol2. This should make Lua issues much simpler.

**Comment by systemed** [comment]
Luabind now replaced - please open a new issue if you have difficulties now we're using kaguya!
