### ISSUE TITLE
Generating MBTILE with info over 17z

### ISSUE THREAD

**Issue by felipemendes1994** [systemed/tilemaker#558]
Hi,

I've been trying to generate a mbtile with information over 16 zoom, through tilemaker in docker. So I built the docker image providing `-DFAT_TILE_INDEX=ON` on the line `Dockerfile:31` as below
```RUN cmake -DFAT_TILE_INDEX=ON -DTILEMAKER_BUILD_STATIC=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++ ..```

For a short test, I first tried to generate mbtile from southeast-brazil region (https://download.geofabrik.de/south-america/brazil/sudeste-latest.osm.pbf), but even enabling the needed arg, I was getting the error:
```
Compile tilemaker with -DFAT_TILE_INDEX to enable tile output at zoom level 17 or greater
```

I also tried to comment the lines `shared_data.cpp:144` to `shared_data.cpp:149`, to overcome this validation, and generate the mbtile. I got success on docker image built, but when compiling mbtile, I got error on memory usage. This error doesn't show messages, but it might be realized when monitoring memory usage. As result, I have no file created in output dir.

I made available 20GB ram docker, but this was not enough. My question is, how much memory is need for compiling mbtile with information over 17z?

My intention is generating a mbtile for the whole planet with information over 17z zoom.

Steps to reproduce the error:
```
1 - git clone git@github.com:systemed/tilemaker.git
2 - git checkout v2.4.0
3 - Enable -DFAT_TILE_INDEX=ON on Dockerfile
4 - docker build -t tilemaker:2.4.0 .
5 - docker run --rm -it --memory=20GB -v ~/Documentos/arquivos/PBFs:/srv -v ./generated:/output -v ./tiles:/tmp-tiles tilemaker:2.4.0 --input=/srv/sudeste-latest.osm.pbf --output=/output/sudeste-30-10.mbtiles --store /tmp-tiles --verbose
```

**Comment by systemed** [comment]
It's very unusual to generate vector tiles at z17. Vector tiles don't work like raster tiles. Rather, the idea is that your z14 (or maybe z15) tiles have _everything_ that is needed for higher zooms, and you just select what to show in the stylesheet.

See https://github.com/systemed/tilemaker/blob/master/docs/VECTOR_TILES.md#the-format

> My intention is generating a mbtile for the whole planet with information over 17z zoom.

If that really _is_ what you want to do then I suspect tilemaker isn't the tool for you, I'm afraid.

**Comment by felipemendes1994** [comment]
Hi @systemed ,

First of all, thanks for you quick answer. I made a comparison amoung mbtile generated with other tool we where using before, and for my suprise, 14z is totally enough. I don't need more than this. So I'm gone follow with the standart configuration.

Thank you again!

**Comment by pnorman** [comment]
> It's very unusual to generate vector tiles at z17. Vector tiles don't work like raster tiles. Rather, the idea is that your z14 (or maybe z15) tiles have _everything_ that is needed for higher zooms, and you just select what to show in the stylesheet.

Specifically, I believe it is not possible to pre-generate z16 and z17 in a practical manner.

**Comment by felipemendes1994** [comment]
I opened another issue to specifically address the planet's mobile generation, as they are different problems..

https://github.com/systemed/tilemaker/issues/573
