### ISSUE TITLE
Bigger example

### ISSUE THREAD

**Issue by pnorman** [systemed/tilemaker#56]
The example included has a water, roads, buildings, and pois layer. Is this enough to get a handle on performance and memory requirements? Are there features not demoed in the example (e.g. shapefiles)?

**Comment by pnorman** [comment]
Also, the example is only z11-14

**Comment by systemed** [comment]
Ideally we should have a reference style, in the same way that osm2pgsql has one.

**Comment by TimSC** [comment]
I hope to make a style based on the openmaptiles schema, which could become a reference style for this project. https://github.com/TimSC/tilemaker/tree/otmdata2 https://openmaptiles.org/schema/
