### ISSUE TITLE
stylesheet

### ISSUE THREAD

**Issue by humanitiesNerd** [systemed/tilemaker#576]
I made this map with Tilemaker and Proomaps (it's a PMTiles file served through MaplibreJs)

![PMTiles](https://github.com/systemed/tilemaker/assets/283791/6e90c25e-c831-4fb3-8303-c0c613efff5e)

Only 2 layers are visible here

1. landuse (filled with a solid color)
2. transportation (in black)

This is because the stylesheet is improvised

[This](https://github.com/openmaptiles/osm-bright-gl-style) other stylesheet seems to be available 

but

1. it's in json (shouldn'i it be .css ?)
2. it contains lots of keys I don't recognize
3. it contains a lot of urls pointing to things and I'm not sure what they are
4. it's complicated

Isn't there a complete but simple ready made stylesheet I could use ?

Thanks

**Comment by systemed** [comment]
You can use the openmaptiles-compatible stylesheet that's bundled with tilemaker. See config-openmaptiles.json and process-openmaptiles.lua in https://github.com/systemed/tilemaker/tree/master/resources.

The Maplibre/Mapbox GL renderers use a JSON format of stylesheet, not CSS. I'd recommend reading through tilemaker's `docs/` directory to understand how vector tiles work.
