### ISSUE TITLE
Created tiled .pbf from osm .pbf but they not load ok when trying to display them

### ISSUE THREAD

**Issue by nouryf** [systemed/tilemaker#59]
Hi,

1. I downloaded this .mbtiles
https://osm2vectortiles-downloads.os.zhdk.cloud.switch.ch/v2.0/extracts/liechtenstein.mbtiles

and broked down to .pbf tiles and was able to display it offline using Mapbox -gl like it outlined in
https://github.com/klokantech/mapbox-gl-js-offline-example

2. Now I built tilemaker on Windows (https://github.com/alex85k/tilemaker), then downloaded liechtenstein.pbf from http://download.geofabrik.de/europe/liechtenstein-latest.osm.pbf

and used tilemaker.exe (with default config.json and process.lua of tilemaker) to create tiled .pbf. The process created indeed zoom level 12, 13 and 14 (as outlined in config.json). 

When I tried displaying them the same way as I displayed other .pbf in step 1, I get errors about null blobs and my map do not display any geometry at all. My .html start the zoom at 12 since my tiles started there.

I'm wondering if the produced .pbf are valid since I can't display them ?
Or may be I'm missing a settings when using TileMaker to produce my tiled .pbf ?

Thanks for any help

Noury

**Comment by TGISer** [comment]
How did you built tilemaker on Windows .  Thank you for your help!

**Comment by nouryf** [comment]
I used this fork: https://github.com/alex85k/tilemaker
It provide .bat to build dependencies needed for tilemaker then another .bat to build tilemaker once dependencies are built.

Let me know if you need a detailed explanation and I'll gather the details from my notes when I built it a while ago.

**Comment by TGISer** [comment]
I need a detailed explanation, thanks a lot !

Can you display the .pbf now ?

**Comment by nouryf** [comment]
I was not able to display the produced .pbf when I tried this 3 months ago. I did not try again. It could be that I did some thing wrong.

Here are the steps to build tile maker on Windows. Thanks to @alex85k for his help pointing me to the right direction to build TileMaker on Windows.

1. Need Visual Studio 2015: Download and install Visual Studio 2015. Create new C++ project and it will prompt you to to download and install C++ run time. Install them.

2. Install 'Git' and 'Cmake'. 
Git: https://git-for-windows.github.io 
Cmake: https://cmake.org/download/

Get the zip from:
https://github.com/alex85k/winbuilds

3. Edit 'Settings.bat':

if "%COMPILER%"=="" SET COMPILER=MSVC2015
if "%PREFIX%"=="" SET PREFIX=F:\OSM\libs2015r
if "%BOOST_ROOT%"=="" SET BOOST_ROOT=F:\OSM\boost
if "%VARIANT%"=="" SET Variant=Release

Compiler --> VS 2015
Prefix where to store libraries that will be built
Path for where boost will be build

Note: F:\OSM is a folder on my machine where I stored the build results. You can have any folder on your OS.

4. In CMD window:

build_boost.bat
build_all_base.bat
build_luabind.bat
build_protobuf.bat
build_protobuf-c.bat

Then:

5.
build_tilemaker.bat

**Comment by 1254859753** [comment]
@nouryf  I can't display my .pbf, can you teach me how to display? I want to learn your codes that can use tiles.
