### ISSUE TITLE
Error when try to run on MacOS Sierra

### ISSUE THREAD

**Issue by armed** [systemed/tilemaker#61]
Installed tilemaker:
```
 $ brew install protobuf boost lua51 shapelib                                                                                             
 $ make
 $ make install
```

It exited with error, when I tried to run it:
```
$ tilemaker osm_extract.osm.pbf --output=/path/to/tiles
libc++abi.dylib: terminating with uncaught exception of type kaguya::LuaTypeMismatch: type mismatch!!
[1]    15510 abort      tilemaker osm_extract.osm.pbf --output=/path/to/tiles/
```

One thing I changed is install path in Makefile to my home/bin directory and I used git tag v1.4.0 when compiled tilemaker, using master didn't help.

**Comment by armed** [comment]
Sorry my bad, config.json and processing.lua wasn't in path.

**Comment by systemed** [comment]
No problem. I should probably add explicit checks for that.

**Comment by tkorsa** [comment]
@armed What did you add to your path? I can't figure out how to add processing.lua.

**Comment by armed** [comment]
@tkorsa I just `cd` to folder in which `config.json` and `processing.lua` is located and launch tilemaker executable, which is in my env PATH.

**Comment by tkorsa** [comment]
@armed Yeah i'm doing the same. But I still get the type mismatch.

![Tilemaker](https://media.giphy.com/media/26ybwHZ922lnfCMxy/source.gif)

**Comment by tkorsa** [comment]
Well, I cd'd out of tilemaker dir and used
`--config=tilemaker/config.json --process=tilemaker/process.lua`
That solved it for me.

**Comment by xingmolu** [comment]
Layer waterway (z11-14)
Layer transportation (z12-14)
Layer building (z14-14)
Layer poi (z13-14)
Reading china-latest.osm.pbf
Block 7786 group 0 ways 0 relations 4547
Stored 54260116 nodes, 3314075 ways, 4850 relations
libc++abi.dylib: terminating with uncaught exception of type boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::geometry::inconsistent_turns_exception> >: Boost.Geometry Inconsistent Turns exception
[1]    1314 abort      tilemaker china-latest.osm.pbf --output=tiles/


What is the problem with this?
