### ISSUE TITLE
Wrong x and y with 14+ zoom levels

### ISSUE THREAD

**Issue by armed** [systemed/tilemaker#62]
Hi.

I tried to generate .mbtiles database for 12-18 zoom levels from OSM pbf file, but my tile server returned nothing. By manually requesting SQLite database I figured out that `tile_column` and `tile_row` has wrong values on all zoom levels. Here is my config file (default except 14->18):
```
{
	"layers": {
		"water": { "minzoom": 11, "maxzoom": 18 },
		"roads": { "minzoom": 12, "maxzoom": 18, "simplify_below": 13, "simplify_level": 0.0001, "simplify_ratio": 2.0 },
		"buildings": { "minzoom": 18, "maxzoom": 18 },
		"pois": { "minzoom": 13, "maxzoom": 18 }
	},
	"settings": {
		"minzoom": 12,
		"maxzoom": 18,
		"basezoom": 18,
		"include_ids": false,
		"name": "Tilemaker example",
		"version": "0.1",
		"description": "Sample vector tiles for Tilemaker",
		"compress": "gzip",
		"metadata": {
			"json": { "vector_layers": [
						{ "id": "roads",     "description": "roads",     "fields": {"name":"String","type":"String"}},
						{ "id": "water",     "description": "water",     "fields": {}},
						{ "id": "buildings", "description": "buildings", "fields": {}}
					] }
		}
	}
}
```
But with default parameters (12-14) everything works as expected.

**Comment by armed** [comment]
Results with valid columns which I see using leaflet (zoom levels up to 14, default config): 
<img width="572" alt="screen shot 2016-12-02 at 2 31 58 pm" src="https://cloud.githubusercontent.com/assets/223060/20827503/93b0baaa-b89c-11e6-8136-3e5c6c012e17.png">

Results with invalid columns, server responses with 404 errors (zoom levels up to 18, see above):
<img width="566" alt="screen shot 2016-12-02 at 2 34 01 pm" src="https://cloud.githubusercontent.com/assets/223060/20827526/d8da7e7c-b89c-11e6-8903-0bef99deb579.png">

**Comment by 1254859753** [comment]
Have you ever tried to generate .mbtiles database for 1-10 zoom levels from OSM pbf file? @armed
