### ISSUE TITLE
Font Problem

### ISSUE THREAD

**Issue by Cactustory** [systemed/tilemaker#637]
My rendered tiles have Persian names and they are shown incorrectly.
How can I get the required fonts?

![image](https://github.com/systemed/tilemaker/assets/80807292/1e4f7d43-5870-40cf-955b-f1862b963f1a)

**Comment by systemed** [comment]
Rendering is not really within tilemaker's scope - it just produces the tiles. I don't know what the Persian fonts _should_ look like but this Maplibre example is probably what you want: https://maplibre.org/maplibre-gl-js/docs/examples/mapbox-gl-rtl-text/

**Comment by Cactustory** [comment]
Its correct now and its right to left but some of the characters are missing. For example "تهران" in my rendered vector is "تهرا"
![image](https://github.com/systemed/tilemaker/assets/80807292/a1acb401-3622-49a6-8cf9-f7e157725a47)

**Comment by systemed** [comment]
https://github.com/openmaptiles/openmaptiles/issues/194 might be relevant. But the tilemaker project really is about creating tiles rather than rendering them so I can't help any more here, I'm afraid.
