### ISSUE TITLE
Problem building on Debian Jessie

### ISSUE THREAD

**Issue by citizenfish** [systemed/tilemaker#65]
Seeing errors as follows:-

`/usr/include/boost/geometry/algorithms/disjoint.hpp: In instantiation of ‘bool boost::geometry::disjoint(const Geometry1&, const Geometry2&) [with Geometry1 = int; Geometry2 = boost::geometry::model::d2::point_xy<double>]’:
/usr/include/boost/geometry/algorithms/intersects.hpp:99:53:   required from ‘bool boost::geometry::intersects(const Geometry1&, const Geometry2&) [with Geometry1 = int; Geometry2 = boost::geometry::model::d2::point_xy<double>]’
src/osm_object.cpp:269:66:   required from here
/usr/include/boost/geometry/algorithms/disjoint.hpp:344:80: error: no type named ‘type’ in ‘struct boost::geometry::dimension<int>’
     return dispatch::disjoint<Geometry1, Geometry2>::apply(geometry1, geometry2);
                                                                                ^
In file included from /usr/include/boost/iterator/iterator_categories.hpp:22:0,
                 from /usr/include/boost/iterator/detail/facade_iterator_category.hpp:7,
                 from /usr/include/boost/iterator/iterator_facade.hpp:14,
                 from /usr/include/boost/filesystem/path.hpp:28,
                 from /usr/include/boost/filesystem.hpp:16,
                 from src/tilemaker.cpp:20:
`

**Comment by citizenfish** [comment]
This was down to a dependency on boost 1.56. I removed and reinstalled to this version and now get:-

`In file included from src/tilemaker.cpp:90:0:
src/read_shp.cpp: In function ‘void readShapefile(std::string, std::vector<std::basic_string<char> >&, Box&, std::map<unsigned int, std::vector<OutputObject> >&, std::vector<boost::variant<boost::geometry::model::d2::point_xy<double>, boost::geometry::model::linestring<boost::geometry::model::d2::point_xy<double, boost::geometry::cs::cartesian>, std::vector, std::allocator>, boost::geometry::model::multi_linestring<boost::geometry::model::linestring<boost::geometry::model::d2::point_xy<double, boost::geometry::cs::cartesian>, std::vector, std::allocator>, std::vector, std::allocator>, boost::geometry::model::multi_polygon<boost::geometry::model::polygon<boost::geometry::model::d2::point_xy<double, boost::geometry::cs::cartesian>, true, true, std::vector, std::vector, std::allocator, std::allocator>, std::vector, std::allocator> > >&, std::map<unsigned int, std::basic_string<char> >&, uint, uint, std::string&, bool, std::map<std::basic_string<char>, boost::geometry::index::rtree<std::pair<boost::geometry::model::box<boost::geometry::model::d2::point_xy<double> >, unsigned int>, boost::geometry::index::quadratic<16ul> > >&, std::string&)’:
src/read_shp.cpp:191:37: error: no matching function for call to ‘is_valid(MultiPolygon&, std::string&)’
    if (!geom::is_valid(multi, reason)) {
                                     ^
src/read_shp.cpp:191:37: note: candidate is:
In file included from /usr/include/boost/geometry/algorithms/is_valid.hpp:13:0,
                 from /usr/include/boost/geometry/geometry.hpp:67,
                 from /usr/include/boost/geometry.hpp:17,
                 from src/tilemaker.cpp:48:
/usr/include/boost/geometry/algorithms/detail/is_valid/interface.hpp:70:13: note: template<class Geometry> bool boost::geometry::is_valid(const Geometry&)
 inline bool is_valid(Geometry const& geometry)
             ^
/usr/include/boost/geometry/algorithms/detail/is_valid/interface.hpp:70:13: note:   template argument deduction/substitution failed:
In file included from src/tilemaker.cpp:90:0:
src/read_shp.cpp:191:37: note:   candidate expects 1 argument, 2 provided
    if (!geom::is_valid(multi, reason)) {
                                     ^
Makefile:13: recipe for target 'src/tilemaker.o' failed
make: *** [src/tilemaker.o] Error 1`

**Comment by citizenfish** [comment]
Solved

Replaced 1.56 with 1.62 and all works fine

**Comment by systemed** [comment]
That's worth knowing - thanks. Boost versions are a perennial headache and seem to be differently valid on various platforms; I'll tweak the docs slightly.
