### ISSUE TITLE
Sample Workflow blog post not reachable

### ISSUE THREAD

**Issue by daniel-j-h** [systemed/tilemaker#658]
Hey folks, it looks like the sample workflow blog post is no longer reachable. I checked a few times over the last weeks and seems like the blog post is down. We link to the following page on tilemaker.org on the sample workflow button

https://blog.kleunen.nl/blog/tilemaker-generate-map

The last functioning state I can find in the Wayback Machine is from August 2023 here:

http://web.archive.org/web/20230813125054/https://blog.kleunen.nl/blog/tilemaker-generate-map

Maybe we should change the link to the archived page or to the github readme or something similar.

![sample-workflow](https://github.com/systemed/tilemaker/assets/527241/d41efc43-f7e4-44c9-aa74-2bef62975922)

**Comment by systemed** [comment]
Unfortunately it looks like Wouter's blog has gone down since he passed away. :(

I'd removed it from the README but forgotten it was on tilemaker.org as well. Just updated - thanks for spotting.
