### ISSUE TITLE
Documented workflow for 

### ISSUE THREAD

**Issue by timlinux** [systemed/tilemaker#662]
Trying to follow the documentation at https://github.com/systemed/tilemaker/blob/master/docs/RUNNING.md#creating-a-map-with-varying-detail results in error complaining that there is no pbf file:

![image](https://github.com/systemed/tilemaker/assets/178003/673984f0-72d2-46ea-af9c-890cb64b1bd9)

**Comment by systemed** [comment]
You'll need to build from source rather than using the 3.0 release for that - there was a small bug that was fixed in https://github.com/systemed/tilemaker/commit/782f6396912f889509cc5cd8cd248c2697157b1f.

**Comment by timlinux** [comment]
Thanks @systemed that fixes the problem (link here to my [nix package](https://github.com/timlinux/nix-config/tree/main/packages/tilemaker) for any NixOS users looking for a recipe to build the more recent version). Initially the tile generation is very slow but after a few minutes it picks up speed nicely.

![image](https://github.com/systemed/tilemaker/assets/178003/a773ccae-f5f4-454e-89fe-e773dec283ea)

![image](https://github.com/systemed/tilemaker/assets/178003/d0917c5e-f1f7-45b0-b8b2-56c343a9548a)
