### ISSUE TITLE
Attribute(name, value, minzoom) writes attribute on all zoom levels

### ISSUE THREAD

**Issue by Nakaner** [systemed/tilemaker#671]
The minzoom argument of the function `Attribute(name, value, minzoom)` is not working.

How to reproduce:

* Download a motorway: `curl https://api.openstreetmap.org/api/0.6/way/4231749/full | osmium cat --input-format xml --output-format pbf -o w4231749.osm.pbf -`
* Create vector tiles from it: `./tilemaker --input w4231749.osm.pbf --output /tmp/tiles/ --bbox 8.2802,48.8782,8.3682,48.9414 --process resources/process-openmaptiles.lua --config resources/config-openmaptiles.json`
* Open the tile on zoom level 8 with `ogrinfo`: `ogrinfo -ro -al MVT:/tmp/tiles/8/133/88.pbf`

Ogrinfo will print a linestring geometry with a `surface` attribute. However, the Tilemaker process file says that the attribute is supposed to be written on zoom level 9 and larger only.

The bug was introduced by commit d62c480debf6c38cd5d2c6339bfaa995b05fb9f2 by @cldellow.

**Comment by cldellow** [comment]
Ack, thank you for diagnosing the breaking commit and for the excellent reproduction steps.

#672 should fix that, and also adds tests to catch future regressions. I think minzooms greater than 7 were not being honoured correctly.
