### ISSUE TITLE
Lua Runtime Error

### ISSUE THREAD

**Issue by Booligoosh** [systemed/tilemaker#673]
Hi, thanks for the great work as always. Getting an error when running Tilemaker:

```
lua runtime error: 
`maybe...Argument mismatch:string,boolean        candidate is:
                std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >,kaguya::VariadicArgType,
'  `maybe...Argument mismatch:string,boolean     candidate is:
                std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >,kaguya::VariadicArgType,
'  
Lua error on way 1009195265
```

Process file here, if that helps at all: https://github.com/Booligoosh/sydneybikemap/blob/tilemaker-3/tiles/process.lua

**Comment by cldellow** [comment]
I think https://github.com/Booligoosh/sydneybikemap/blob/tilemaker-3/tiles/process.lua#L539 should just be:

```lua
		LayerAsCentroid("housenumber")
```

The inscrutable error is unfortunate :(

**Comment by Booligoosh** [comment]
This solved it, thanks so much!! Yeah, a nicer error message would have been helpful
