### ISSUE TITLE
Replace Luabind with Luwra

### ISSUE THREAD

**Issue by systemed** [systemed/tilemaker#7]
Installing Luabind seems to be pretty much the pain point for everyone. [Luwra](https://github.com/vapourismo/luwra) is header-only, so should be less like dragging one's face across a bed of broken glass coated in [Dave's Insanity Sauce](http://www.chilliworld.com/SP6.asp?p_id=41) while having the last month's posts on talk@ read out to you.

**Comment by pnorman** [comment]
C++14 is possibly a bigger pain point. With gcc you need GCC 4.9 for most features or GCC 5 series for some. With clang you need 3.4 with `-std=c++1y` or 3.5 or later with `-std=c++14`.

Ubuntu 14.04 LTS comes with g++ 4.8.

osm2pgsql uses the [C lua interface](https://github.com/openstreetmap/osm2pgsql/blob/master/tagtransform.hpp#L13-L17) which only depends on liblua dev. Is this an option here?

**Comment by pnorman** [comment]
Note: lua does come with C++ bindings in the form of `lua.hpp` which is reproduced in below

```c++
extern "C" {
#include "lua.h"
#include "lualib.h"
#include "lauxlib.h"
}
```

**Comment by systemed** [comment]
Hmmm, yes, C++14 might be painful.

Tilemaker actually uses the plain C Lua bindings for the 'Read significant node tags' bit of tilemaker.cpp - it just uses Luabind to make it easier for the Lua profile to call C++ (principally for getting tags). It would be nice to remove any Luabind/whatever dependency, but the Lua C bindings aren't easy to work with tbh.

**Comment by grafi-tt** [comment]
Now luwra's master branch supports C++ 11. I and Inoue-san have other jobs and aren't going to work on tilemaker's luwra support in January at least. Therefore, if you can work on, don't mind about duplicated works.

**Comment by systemed** [comment]
Luabind now replaced. I've eventually settled on https://github.com/satoren/kaguya rather than luwra as the interface is simpler and the documentation better. (I did also look at sol2 but it requires C++14.)
