### ISSUE TITLE
Roundabouts missing if the first node reference is the same as the last one

### ISSUE THREAD

**Issue by alois-lohner** [systemed/tilemaker#707]
There is maybe a issue generating roundabouts.

If a roundabout is defined with more then one ‚way‘ definition, roundabouts are visible within a map (tilemaker-server, TileServer GL).

If a roundabout is defined with only one ‚way‘ definition, roundabouts are not part of the mbtile file. The problem seems to be, that these ‚way‘ definitions references a couple of nodes, where the first node is the same as the last one in the reference list.

Screenshot OpenStreetMap
<img width="1530" alt="Bildschirmfoto 2024-04-25 um 11 16 43" src="https://github.com/systemed/tilemaker/assets/84730363/d4c73f3a-587e-4d5b-b729-cf869ede241b">

Screenshot Tilemaker-Server  
<img width="1016" alt="Bildschirmfoto 2024-04-25 um 11 17 52" src="https://github.com/systemed/tilemaker/assets/84730363/92f26374-189b-45bb-8f22-368f5a62ad75">

By the way, in process.lua (resources/process-openmaptiles.lua) is the line to handle z10RoadValues (line 478) missing:

Should be:
		elseif z9RoadValues[h]       then minzoom = 9
		elseif z10RoadValues[h]      then minzoom = 10
		elseif z11RoadValues[h]      then minzoom = 11

is:
		elseif z9RoadValues[h]       then minzoom = 9
		elseif z11RoadValues[h]      then minzoom = 11

I used the current 3.0.0 release of tilemaker.

**Comment by systemed** [comment]
Thanks for spotting. #708 should fix this.

**Comment by alois-lohner** [comment]
#708 fixed it - thanks
