### ISSUE TITLE
Enable travis

### ISSUE THREAD

**Issue by pnorman** [systemed/tilemaker#74]
I'd like to set up some CI for tilemaker with travis. Could you enable it at https://travis-ci.org/systemed/tilemaker?

**Comment by systemed** [comment]
Done.

**Comment by systemed** [comment]
It's erroring at https://travis-ci.org/systemed/tilemaker/builds/208268852 . I presume you have some idea what this means.

**Comment by pnorman** [comment]
Yep - it's doing a default ruby project build, which of course errors out. I need to do a PR to add a .travis.yml file telling it how to build

**Comment by tomchadwin** [comment]
My PR has stubbed out the beginnings of a `.travis.yml`. See the last Travis result:

https://travis-ci.org/systemed/tilemaker/builds/216913267

### Issues
1. When I tried to use the PPA suggested in the README, the dependencies faild (see https://travis-ci.org/systemed/tilemaker/builds/216903659), and I don't know how to fix
2. I therefore switched to a PPA suggested in an answer to http://stackoverflow.com/questions/21510633/my-apt-got-messed-up-installing-boost
3. That meant I had to down to Precise from Trusty, and to boost 1.55

That gets a working platform (unless you tell me that either Precise or boost1.55 are insufficient), but I don't know where to proceed from here. If you can solve the dependencies issues from point 1 above, that would be better.

Hope it's of some use.

**Comment by pnorman** [comment]
boost 1.56 is required. I'll have a go.

**Comment by systemed** [comment]
This is currently not happy: https://travis-ci.org/systemed/tilemaker/builds/336129092

**Comment by tomchadwin** [comment]
Is that version of boost no longer in that ppa:

https://launchpad.net/~ostogvin/+archive/ubuntu/tjo-develop

Can you use the version listed there instead?

**Comment by tomchadwin** [comment]
https://github.com/systemed/tilemaker/pull/105 fixes this, but better ways might be possible.

**Comment by systemed** [comment]
LGTM but I am absolutely no expert. @pnorman?

**Comment by pnorman** [comment]
Yep, working
