### ISSUE TITLE
Bug: SegFault caused by invalid string

### ISSUE THREAD

**Issue by oobayly** [systemed/tilemaker#750]
I came across this when adding a large number of attributes to a nodes. In my case I was adding all the OSM tags with a `railway:` prefix (I'm not planning on doing always doing this, but it's useful for development). This was fine for a small region (Köln Rebenz), but would end with SIGSEGV when using the parent area (Nordrehin Westfalen).

My first thought was that it's an OOM error, but this turned out not to be the case:
* First, I used the `--store` flag, but this made no difference.
* The total memory being used was only 3.5GB. Docker has up to 32GB on my machine with a total of 64GB physical memory.
* Increasing the number of nodes greatly (by processing the entirety of Germany), but with only subsets of the `railways:` tags did work, with a similar 3.5GB usage.
* At one stage (I can't remember how), I managed to get a readable error that suggested a string issue.

So, it seems to be an issue with attributes, I:
* Rebuilt tilemaker with debug and didn't strip the symbols
* Enabled coredumps in docker and installed gdb
* Made sure to run with only a single thread
* Managed obtain a backtrace for the offending error - attached [tilemaker-backtrace.txt](https://github.com/user-attachments/files/16930540/tilemaker-backtrace.txt)
* In my case there are 301 items in the `AttributeStore->keyStore`. *I appreciate that this many not be great practice, but nor should this be causing a SegFault*.

In short, it was **`error reading variable: Cannot access memory at address 0x1a149fe`**, and was been thrown in [OutputObject::writeAttributes:49](https://github.com/systemed/tilemaker/blob/eab08d189ad97ddf5db7d915bcabe42ad3dab6af/src/output_object.cpp#L49)

Attaching a debugger, I found that address of the string `const std::string& key = attributeStore.keyStore.getKeyUnsafe(it->keyIndex);` was invalid, and attempting to read it is causing an access violation. More specifically, the iterator `it` had an invalid (negative) `keyIndex` value.
![image](https://github.com/user-attachments/assets/6de66bd9-a856-4c1e-aca2-f41829a31999)
What's interesting is that the other properties for the `AttributePair` is valid, `valueType` and the string in `stringValue`.

I'll try setting up a simple (but completely unrealistic) set up so it can be reproduced on demand.

As an aside, I'm going to create another 2 issues with associated PR that helped me with getting live debugging to work via docker.
* #751 
* #752

**Comment by cldellow** [comment]
Great, thanks for verifying the issue! I opened #760 to apply that fix + improve the failure mode. I've left the limit at 512 - if/when someone complains that it's not enough, we can revisit improving it.
