### ISSUE TITLE
Non OSM data, shapefile 

### ISSUE THREAD

**Issue by PaulArchambault** [systemed/tilemaker#80]
Hi  kind TileMaker developers, 

Sorry, i am just new using  tilemaker without good  programming skills...

I have a shape file non OSM data that i want to convert to vector tiles 

Folowing instructions CONFIGURATION.md,  my config.json looks like :
{ "layers": {
       "Iris": {
       	 	"minzoom": 11, "maxzoom": 14,
      		"source": "France_Iris_region.shp",
     	 	"simplify_below": 13, "simplify_level": 0.0003,
      		"source_columns": ["Code","Nom","Pop"]
            }
}
}

But it is not clear what kind of tilemaker command do i have to execute : what input file (pbf?) do i have to refer to ?
tilemaker [what input file???] --output/Iris_Vtiles

Thanks for your lights, best

**Comment by AgentJay** [comment]
In my own limited experience I was able to get it running by using an unrelated pbf file.

That is to say I downloaded a pbf file that was from this link:
http://download.bbbike.org/osm/bbbike/Bern/Bern.osm.pbf

then ran my config (entirely unrelated to the bern.osm.pbf file) like this:

tilemaker /tmaker/osm_data/bern.osm.pbf --output=/tmaker/tiles/myLayer/ --config=/tmaker/config/myLayerConfig.json --process=/tmaker/process.lua

Hope that helps!

**Comment by dBitech** [comment]
When following this method, you need to ensure that the pbf file encompasses the bounds needed by your shapefile.
  The Bern file above will result in a mbtile with tilejson information of 
  {"bounds":[7.17,46.73,7.77,47.17],
  "center":[7.47,46.95,11],
  "tilejson":"2.0.0"}

**Comment by systemed** [comment]
.osm.pbf files are no longer compulsory. Note that you will need to supply a bounding_box parameter in your .json file.
