### ISSUE TITLE
"Vector tile source does not use vector tile spec v2 and therefore may have some rendering errors"

### ISSUE THREAD

**Issue by robhawkes** [systemed/tilemaker#88]
I'm currently serving the exported MBTiles from `tilemaker` using `tileserver-gl-light` and visualising everything in Mapbox GL JS. I noticed that Mapbox GL JS spits out warnings for each tile along the lines of `Vector tile source does not use vector tile spec v2 and therefore may have some rendering errors`.

After digging around I found that this is because the tiles generated by `tilemaker` [have their spec version number hard-coded to `1`](https://github.com/systemed/tilemaker/blob/master/src/tilemaker.cpp#L289) causing Mapbox GL JS to get angry. If I change that hard-coded version number to `2` then the warnings disappear.

Now this is enough for me as Mapbox GL JS seems to be happy that the tiles are using [version 2 of the Mapbox Vector Style Spec](https://www.mapbox.com/vector-tiles/specification/). However it's probably worth discussing how `tilemaker` can be officially brought inline to support version 2 of the spec.

Has this been looked into yet?

**Comment by systemed** [comment]
Would be happy to make this a configurable option, probably in the .json file (and defaulting to 2 if not specified). Does anyone know (@pnorman?) whether there would be any other implications for us, or is v2 really just a tidying/formalising of the more informal v1 spec?

**Comment by robhawkes** [comment]
That would be amazing as right now I'm hard-coding a work around. I'm unsure of the state of the spec in the past but version 2 looks pretty formal and well documented now. That link in my first post should hopefully describe the spec in enough detail to see how it differs from the current implementation in `tilemaker`. For what it's worth, changing the version number to 2 stopped the Mapbox GL JS warnings so just having a config option for that would be a quick win aside from full v2 support.

**Comment by systemed** [comment]
I've just added this as a configurable option in the JSON file (`mvt_version`), defaulting to 2. Could you check and see if it works for you?

**Comment by freeExec** [comment]
MBTiles with spec v2 of the Mapbox does not accept.
> Vector Tile Layer has no extent

With setting ```mvt_version=1```, it's okay.

**Comment by systemed** [comment]
Note to self: https://github.com/mapbox/mapnik-vector-tile/issues/184 looks like something worth following up.

**Comment by systemed** [comment]
I've added support for writing the `extent` field required by Mapbox GL (JS/Native) when reading MVT v2 files (even though the .proto still calls it "optional"... hey ho).

**Comment by systemed** [comment]
Closing as I believe this is fixed now, but let me know if not.
