### ISSUE TITLE
tiles format

### ISSUE THREAD

**Issue by Alphatiger** [systemed/tilemaker#9]
can we get the vector files in geojsonformat

**Comment by kathir-bit** [comment]
can we get  the output as a folder structure .In this approach, you just organize the tiles as individual image files under a folder structure representing the scale level, row, and column...here 16 level mean 16 folders with respective zoom ...?

we can use many mapping APIs can use tiles when presented with a URL structure with variables representing the consistent position of the level, row, and column.
