### ISSUE TITLE
Support PBFs containing only nodes (no ways or relations)

### ISSUE THREAD

**Issue by robhawkes** [systemed/tilemaker#90]
When processing a PBF through `tilemaker` that contains only nodes you receive the following error:

```
Can't parse message of type "BlobHeader" because it is missing required fields: type, datasize
```

From a cursory glance this looked to be caused by an assumption in the code that there will be relations and ways inside the PBF and so [the parser doesn't exit its loop](https://github.com/systemed/tilemaker/blob/master/src/tilemaker.cpp#L597). My guess is that when the parser reaches the end of a node-only PBF then it notices the relations weren't checked and continues the loop. On that next pass a new block is requested but fails because one doesn't exist.

The easiest fix I can think of is some way to imply in the arguments or config that the input is only nodes and so to skip that final loop. A better solution would be to automatically check if there are any ways or relations and skip that final step if none are found.

This is needed because some common PBF exports will contain only nodes, such as POIs.

This is related to #40 so feel free to close if it's deemed a duplication, however I felt that the original issue doesn't specify the exact issue or how to solve it.

**Comment by systemed** [comment]
This should now be fixed with https://github.com/systemed/tilemaker/commit/3e8f142944d369fe26dff5fa5821d0acb5ef1490 .
