### ISSUE TITLE
Refactor tilemaker.cpp

### ISSUE THREAD

**Issue by systemed** [systemed/tilemaker#93]
It's a bit massive and hard-to-read. Could do with some major refactoring to break it into individual sections:

* Initialise
* Read Lua profile
* Read JSON config
* Read PBFs
  * Read nodes
  * Read ways
  * Read relations
* Write tiles (some of this has already been moved into outputProc, and WriteGeometryVisitor is a really neat approach, but there's more we could do - at the very least moving the loop and proc out of tilemaker.cpp for readability)

**Comment by TimSC** [comment]
Mostly done now in https://github.com/systemed/tilemaker/pull/117 thx for merging!
