### ISSUE TITLE
Vector tile spec warning

### ISSUE THREAD

**Issue by efsavage** [systemed/tilemaker#94]
I am getting this message in Chrome/OS X, using https://api.tiles.mapbox.com/mapbox-gl-js/v0.39.1/mapbox-gl.js:

Vector tile source "osm" layer "transportation" does not use vector tile spec v2 and therefore may have some rendering errors.

Which version of the spec does tilemaker output?

**Comment by systemed** [comment]
See #88 - it doesn't appear that tilemaker's output will be uncompliant with v2, we probably just need to bump the version number. (I'll close this as a dupe but feel free to carry on the conversation in #88.)
