### ISSUE TITLE
WARN: MBTiles not in "openmaptiles" format. Serving raw data only...

### ISSUE THREAD

**Issue by wetfire2k** [systemed/tilemaker#95]
I just exported an mbtiles and tileserver-gl complain about the error on title.
I see that mbtiles exported by tilemaker and those from openmaptiles are very different.
What can I do i order to have things working?
Thanks

**Comment by systemed** [comment]
When you create vector tiles with tilemaker, you need to specify the schema you want for those tiles - in brief, what information you want in the tiles, and at what zoom levels. 

You can use the files in the `resources` directory to create tiles in the OpenMapTiles schema. Specify them as arguments to tilemaker like this:

    --config resources/config-openmaptiles.json --process resources/process-openmaptiles.lua

**Comment by wetfire2k** [comment]
done, but after that I had to run generate-metadata from openmaptiles-tool to get things running.

**Comment by kender1314** [comment]
> When you create vector tiles with tilemaker, you need to specify the schema you want for those tiles - in brief, what information you want in the tiles, and at what zoom levels.
> 
> You can use the files in the `resources` directory to create tiles in the OpenMapTiles schema. Specify them as arguments to tilemaker like this:
> 
> ```
> --config resources/config-openmaptiles.json --process resources/process-openmaptiles.lua
> ```

Hi, How to generate city names and street names？Thanks！[https://github.com/systemed/tilemaker/issues/187](url)
