### ISSUE TITLE
Tilemaker support for Openstreetmap-carto style

### ISSUE THREAD

**Issue by RandyHBH** [systemed/tilemaker#96]
Is this possible???

**Comment by pnorman** [comment]
OpenStreetMap Carto is a CartoCSS stylesheet which uses [Mapnik and osm2pgsql](https://github.com/gravitystorm/openstreetmap-carto/blob/master/INSTALL.md). Tilemaker is a tool to create vector tiles, and doesn't style them at all. They're completely different things.

It's possible to use tilemaker to make vector tiles and then style them with the cartography of osm-carto, but you'd have to write the style and transforms yourself.

**Comment by systemed** [comment]
It would be a couple of weeks' work to port osm-carto to tilemaker I'm afraid, and even then it'd be far from a 1:1 correspondence with the raster style. I do have an ambition to create an out-of-the-box style for tilemaker but it won't be osm-carto.

Geofabrik has a vector tile version of osm-carto, which requires a PostGIS and tessera setup: https://github.com/geofabrik/openstreetmap-carto-vector-tiles/blob/master/README_VECTOR_TILES.md

Closing as not actionable here but feel free to continue the conversation.

**Comment by RandyHBH** [comment]
> It would be a couple of weeks' work to port osm-carto to tilemaker I'm afraid, and even then it'd be far from a 1:1 correspondence with the raster style. 

So is possible, but it will be a hard work, do you have some idea?

> I do have an ambition to create an out-of-the-box style for tilemaker but it won't be osm-carto.

I am quite new doing map styling, but i have some programing experience, so if you have some idea, and could point some directions, i will be glad to colaborate.

> Geofabrik has a vector tile version of osm-carto, which requires a PostGIS and tessera setup: https://github.com/geofabrik/openstreetmap-carto-vector-tiles/blob/master/README_VECTOR_TILES.md

in the meantime, i will check out the geofabrik style.
Regards

**Comment by pnorman** [comment]
The best way to put it is Tilemaker is software, OpenStreetMap Carto is not, it's a style.

**Comment by RandyHBH** [comment]
So you mean that the best will be work in the config.js and process.lua files. I'm going to read the [contributing section](https://github.com/systemed/tilemaker#contributing) and the i will contact you if i have some question.
